package com.ctsi.ssdc.admin.repository;

import com.ctsi.ssdc.admin.domain.CscpUserPost;
import com.ctsi.ssdc.admin.domain.CscpUserPostExample.Criteria;
import com.ctsi.ssdc.admin.domain.CscpUserPostExample.Criterion;
import com.ctsi.ssdc.admin.domain.CscpUserPostExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;


/**
 * CscpUserPostSqlProvider
 *
 * @author hx
 * @date 2022-08-29 10:56:22
*/

public class CscpUserPostSqlProvider {

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_post
     */
    public String countByExample(CscpUserPostExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("cscp_user_post");
        applyWhere(sql, example, false);
        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_post
     */
    public String deleteByExample(CscpUserPostExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("cscp_user_post");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_post
     */
    public String insertSelective(CscpUserPost record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("cscp_user_post");

        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=BIGINT}");
        }
        if (record.getPostId() != null) {
            sql.VALUES("post_id", "#{postId,jdbcType=BIGINT}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_post
     */
    public String selectByExample(CscpUserPostExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("user_id");
        sql.SELECT("post_id");
        sql.FROM("cscp_user_post");
        applyWhere(sql, example, false);

        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_post
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CscpUserPost record = (CscpUserPost) parameter.get("record");
        CscpUserPostExample example = (CscpUserPostExample) parameter.get("example");

        SQL sql = new SQL();
        sql.UPDATE("cscp_user_post");

        if (record.getId() != null) {
        sql.SET("id = #{id,jdbcType=BIGINT}");
        }
        if (record.getUserId() != null) {
        sql.SET("user_id = #{userId,jdbcType=BIGINT}");
        }
        if (record.getPostId() != null) {
        sql.SET("post_id = #{postId,jdbcType=BIGINT}");
        }
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_post
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_user_post");
        sql.SET("id = #{id,jdbcType=BIGINT}");
        sql.SET("user_id = #{userId,jdbcType=BIGINT}");
        sql.SET("post_id = #{postId,jdbcType=BIGINT}");

        CscpUserPostExample example = (CscpUserPostExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_post
     */
    public String updateByPrimaryKeySelective(CscpUserPost record) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_user_post");

        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=BIGINT}");
        }
        if (record.getPostId() != null) {
            sql.SET("post_id = #{postId,jdbcType=BIGINT}");
        }
        sql.WHERE("id = #{id,jdbcType=BIGINT}");

        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_post
     */
    protected void applyWhere(SQL sql, CscpUserPostExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1Th;
        String parmPhrase2;
        String parmPhrase2Th;
        String parmPhrase3;
        String parmPhrase3Th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1Th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2Th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3Th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }

    public String selectByExampleWithPage(CscpUserPostExample example) {
        String sql = selectByExample(example);
       /* Pageable page = example.getPage();
        if(page != null) {
            sql = String.format("%s limit %d,%d", sql, page.getOffset(), page.getPageSize());
        }*/
        return sql;
    }
}
