package com.ctsi.ssdc.admin.repository;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.ctsi.ssdc.admin.domain.CscpWorkGroup;
import com.ctsi.ssdc.admin.domain.CscpWorkGroupExample;
import com.ctsi.ssdc.database.annotation.InjectByDataBaseType;
import com.ctsi.ssdc.database.enums.EnumDatabaseName;

/**
 * @author MyBatis Generator
*/
@InjectByDataBaseType(includes= {EnumDatabaseName.ORACLE})
public interface CscpWorkGroupRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_work_group
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    @SelectProvider(type=CscpWorkGroupSqlProvider.class, method="countByExample")
    long countByExample(CscpWorkGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_work_group
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    @DeleteProvider(type=CscpWorkGroupSqlProvider.class, method="deleteByExample")
    int deleteByExample(CscpWorkGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_work_group
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    @Delete({
        "delete from cscp_work_group",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_work_group
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    @Insert({
        "insert into cscp_work_group (id,group_name, description, ",
        "org_id)",
        "values (#{id,jdbcType=BIGINT},#{groupName,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{orgId,jdbcType=BIGINT})"
    })
    //@Options(useGeneratedKeys=true, keyProperty="id")
    int insert(CscpWorkGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_work_group
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    @InsertProvider(type=CscpWorkGroupSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true, keyProperty="id")
    int insertSelective(CscpWorkGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_work_group
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    @SelectProvider(type=CscpWorkGroupSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="group_name", property="groupName", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="org_id", property="orgId", jdbcType=JdbcType.BIGINT)
    })
    List<CscpWorkGroup> selectByExample(CscpWorkGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_work_group
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    @Select({
        "select",
        "id, group_name, description, org_id",
        "from cscp_work_group",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="group_name", property="groupName", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="org_id", property="orgId", jdbcType=JdbcType.BIGINT)
    })
    CscpWorkGroup selectByPrimaryKey(Long id);
    
    @Select({
        "SELECT a.* ",
        "FROM cscp_work_group a, cscp_work_group_org b ",
        "where a.id = b.group_id "
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="group_name", property="groupName", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="org_id", property="orgId", jdbcType=JdbcType.BIGINT)
    })
    List<CscpWorkGroup> selectByOrgs();
    
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_work_group
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    @UpdateProvider(type=CscpWorkGroupSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CscpWorkGroup record, @Param("example") CscpWorkGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_work_group
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    @UpdateProvider(type=CscpWorkGroupSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CscpWorkGroup record, @Param("example") CscpWorkGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_work_group
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    @UpdateProvider(type=CscpWorkGroupSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CscpWorkGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_work_group
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    @Update({
        "update cscp_work_group",
        "set group_name = #{groupName,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "org_id = #{orgId,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(CscpWorkGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_work_group
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    @SelectProvider(type=CscpWorkGroupSqlProvider.class, method="selectByExampleWithPage")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="group_name", property="groupName", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="org_id", property="orgId", jdbcType=JdbcType.BIGINT)
    })
    List<CscpWorkGroup> selectByExamplewithPage(CscpWorkGroupExample example);
}