package com.ctsi.ssdc.admin.repository;

import com.ctsi.ssdc.admin.domain.CscpPost;
import com.ctsi.ssdc.admin.domain.CscpUserPost;
import com.ctsi.ssdc.admin.domain.CscpUserPostExample;
import java.util.List;

import com.ctsi.ssdc.admin.repository.CscpUserPostSqlProvider;
import com.ctsi.ssdc.model.PageResult;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

/**
 * CscpUserPostRepository
 *
 * @author hx
 * @date 2022-08-29 10:56:22
 */

@Mapper
public interface CscpUserPostRepository extends com.ctsi.ssdc.repository.BaseRepository<CscpUserPost, Long, CscpUserPostExample> {
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_post
     *
     * @date 2022-08-29 10:56:22
     */
    @SelectProvider(type= CscpUserPostSqlProvider.class, method="countByExample")
    @Override
    long countByExample(CscpUserPostExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_post
     *
     * @date 2022-08-29 10:56:22
     */
    @DeleteProvider(type=CscpUserPostSqlProvider.class, method="deleteByExample")
    @Override
    int deleteByExample(CscpUserPostExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_post
     *
     * @date 2022-08-29 10:56:22
     */
    @Delete({
            "delete from cscp_user_post",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_post
     *
     *
     * @date 2022-08-29 10:56:22
     */

    @Insert({
            "insert into cscp_user_post (id,user_id,post_id)",
            "values (#{id,jdbcType=BIGINT},#{userId,jdbcType=BIGINT}, #{postId,jdbcType=BIGINT})"
    })
    @Override
    int insert(CscpUserPost record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_post
     *
     * @date 2022-08-29 10:56:22
     */
    @InsertProvider(type=CscpUserPostSqlProvider.class, method="insertSelective")
    @Override
    int insertSelective(CscpUserPost record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_post
     *
     * @date 2022-08-29 10:56:22
     */
    @SelectProvider(type=CscpUserPostSqlProvider.class, method="selectByExample")
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
            @Result(column="post_id", property="postId", jdbcType=JdbcType.BIGINT)
    })

    @Override
    List<CscpUserPost> selectByExample(CscpUserPostExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_post
     *
     * @date 2022-08-29 10:56:22
     */
    @Select({
            "select",
            "id,",
            "user_id,",
            "post_id",
            "from cscp_user_post",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
            @Result(column="post_id", property="postId", jdbcType=JdbcType.BIGINT)
    })
    @Override
    CscpUserPost selectByPrimaryKey(Long id);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_post
     *
     * @date 2022-08-29 10:56:22
     */
    @UpdateProvider(type=CscpUserPostSqlProvider.class, method="updateByExampleSelective")
    @Override
    int updateByExampleSelective(@Param("record") CscpUserPost record, @Param("example") CscpUserPostExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_post
     *
     * @date 2022-08-29 10:56:22
     */
    @UpdateProvider(type=CscpUserPostSqlProvider.class, method="updateByExample")
    @Override
    int updateByExample(@Param("record") CscpUserPost record, @Param("example") CscpUserPostExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_post
     *
     *@date 2022-08-29 10:56:22
     */
    @UpdateProvider(type=CscpUserPostSqlProvider.class, method="updateByPrimaryKeySelective")
    @Override
    int updateByPrimaryKeySelective(CscpUserPost record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_post
     *
     * @date 2022-08-29 10:56:22
     */
    @Update({
            "update cscp_user_post",
            "set ",
            "id = #{id,jdbcType=BIGINT},",
            "user_id = #{userId,jdbcType=BIGINT},",
            "post_id = #{postId,jdbcType=BIGINT}",

            "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int updateByPrimaryKey(CscpUserPost record);

    /**
     * 批量删除
     * @param ids
     */
    @Delete("<script>" +
            "delete from cscp_user_post where id in" +
            "<foreach collection=\"ids\" item=\"id\" open=\"(\" separator=\",\" close=\")\">" +
            "#{id}" +
            "</foreach>" +
            "</script>")
    void deleteByIds(@Param("ids") List<Long> ids);


    @Select({
            "select p.post_id,p.post_name "
                    + "from cscp_post p,cscp_user_post up "
                    + "where p.post_id=up.post_id "
                    + "and up.user_id=#{userId,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column = "post_id", property = "postId"),
            @Result(column = "post_name", property = "postName"),
    })
    List<CscpPost> queryPostByUserId(Long userId);

    @Select({
            "select * from cscp_user_post",
            "where post_id = #{postId,jdbcType=BIGINT}"
    })
    List<CscpUserPost> selectPostId(Long postId);
}





