package com.ctsi.ssdc.admin.repository;

import com.ctsi.ssdc.admin.domain.CscpNotice;
import com.ctsi.ssdc.admin.domain.CscpNoticeExample;
import com.ctsi.ssdc.admin.domain.CscpNoticeExample.Criteria;
import com.ctsi.ssdc.admin.domain.CscpNoticeExample.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

/**
 * @author ctsi-biyi-generator
*/
public class CscpNoticeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_notice
     *
     * @mbg.generated Sat Jan 15 15:55:30 CST 2022
     */
    public String countByExample(CscpNoticeExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("cscp_notice");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_notice
     *
     * @mbg.generated Sat Jan 15 15:55:30 CST 2022
     */
    public String deleteByExample(CscpNoticeExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("cscp_notice");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_notice
     *
     * @mbg.generated Sat Jan 15 15:55:30 CST 2022
     */
    public String insertSelective(CscpNotice record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("cscp_notice");
        
        if (record.getNoticeId() != null) {
            sql.VALUES("notice_id", "#{noticeId,jdbcType=BIGINT}");
        }
        
        if (record.getNoticeTitle() != null) {
            sql.VALUES("notice_title", "#{noticeTitle,jdbcType=VARCHAR}");
        }
        
        if (record.getNoticeType() != null) {
            sql.VALUES("notice_type", "#{noticeType,jdbcType=CHAR}");
        }
        
        if (record.getNoticeContent() != null) {
            sql.VALUES("notice_content", "#{noticeContent,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=CHAR}");
        }
        
        if (record.getCreateBy() != null) {
            sql.VALUES("create_by", "#{createBy,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateBy() != null) {
            sql.VALUES("update_by", "#{updateBy,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getRemark() != null) {
            sql.VALUES("remark", "#{remark,jdbcType=VARCHAR}");
        }
        
        if (record.getTenantId() != null) {
            sql.VALUES("tenant_id", "#{tenantId,jdbcType=BIGINT}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_notice
     *
     * @mbg.generated Sat Jan 15 15:55:30 CST 2022
     */
    public String selectByExample(CscpNoticeExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("notice_id");
        } else {
            sql.SELECT("notice_id");
        }
        sql.SELECT("notice_title");
        sql.SELECT("notice_type");
        sql.SELECT("notice_content");
        sql.SELECT("status");
        sql.SELECT("create_by");
        sql.SELECT("create_time");
        sql.SELECT("update_by");
        sql.SELECT("update_time");
        sql.SELECT("remark");
        sql.SELECT("tenant_id");
        sql.FROM("cscp_notice");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_notice
     *
     * @mbg.generated Sat Jan 15 15:55:30 CST 2022
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CscpNotice record = (CscpNotice) parameter.get("record");
        CscpNoticeExample example = (CscpNoticeExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("cscp_notice");
        
        if (record.getNoticeId() != null) {
            sql.SET("notice_id = #{record.noticeId,jdbcType=BIGINT}");
        }
        
        if (record.getNoticeTitle() != null) {
            sql.SET("notice_title = #{record.noticeTitle,jdbcType=VARCHAR}");
        }
        
        if (record.getNoticeType() != null) {
            sql.SET("notice_type = #{record.noticeType,jdbcType=CHAR}");
        }
        
        if (record.getNoticeContent() != null) {
            sql.SET("notice_content = #{record.noticeContent,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{record.status,jdbcType=CHAR}");
        }
        
        if (record.getCreateBy() != null) {
            sql.SET("create_by = #{record.createBy,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateBy() != null) {
            sql.SET("update_by = #{record.updateBy,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getRemark() != null) {
            sql.SET("remark = #{record.remark,jdbcType=VARCHAR}");
        }
        
        if (record.getTenantId() != null) {
            sql.SET("tenant_id = #{record.tenantId,jdbcType=BIGINT}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_notice
     *
     * @mbg.generated Sat Jan 15 15:55:30 CST 2022
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_notice");
        
        sql.SET("notice_id = #{record.noticeId,jdbcType=BIGINT}");
        sql.SET("notice_title = #{record.noticeTitle,jdbcType=VARCHAR}");
        sql.SET("notice_type = #{record.noticeType,jdbcType=CHAR}");
        sql.SET("notice_content = #{record.noticeContent,jdbcType=VARCHAR}");
        sql.SET("status = #{record.status,jdbcType=CHAR}");
        sql.SET("create_by = #{record.createBy,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("update_by = #{record.updateBy,jdbcType=VARCHAR}");
        sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        sql.SET("remark = #{record.remark,jdbcType=VARCHAR}");
        sql.SET("tenant_id = #{record.tenantId,jdbcType=BIGINT}");
        
        CscpNoticeExample example = (CscpNoticeExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_notice
     *
     * @mbg.generated Sat Jan 15 15:55:30 CST 2022
     */
    public String updateByPrimaryKeySelective(CscpNotice record) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_notice");
        
        if (record.getNoticeTitle() != null) {
            sql.SET("notice_title = #{noticeTitle,jdbcType=VARCHAR}");
        }
        
        if (record.getNoticeType() != null) {
            sql.SET("notice_type = #{noticeType,jdbcType=CHAR}");
        }
        
        if (record.getNoticeContent() != null) {
            sql.SET("notice_content = #{noticeContent,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=CHAR}");
        }
        
        if (record.getCreateBy() != null) {
            sql.SET("create_by = #{createBy,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateBy() != null) {
            sql.SET("update_by = #{updateBy,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getRemark() != null) {
            sql.SET("remark = #{remark,jdbcType=VARCHAR}");
        }
        
        if (record.getTenantId() != null) {
            sql.SET("tenant_id = #{tenantId,jdbcType=BIGINT}");
        }
        
        sql.WHERE("notice_id = #{noticeId,jdbcType=BIGINT}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_notice
     *
     * @mbg.generated Sat Jan 15 15:55:30 CST 2022
     */
    protected void applyWhere(SQL sql, CscpNoticeExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1Th;
        String parmPhrase2;
        String parmPhrase2Th;
        String parmPhrase3;
        String parmPhrase3Th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1Th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2Th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3Th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}