package com.ctsi.ssdc.admin.repository;

import java.util.List;

import com.ctsi.ssdc.admin.domain.dto.CscpUserWorkGroupDTO;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.ctsi.ssdc.admin.domain.CscpUserWorkGroup;
import com.ctsi.ssdc.admin.domain.CscpUserWorkGroupExample;
import com.ctsi.ssdc.database.annotation.InjectByDataBaseType;
import com.ctsi.ssdc.database.enums.EnumDatabaseName;

/**
 * @author MyBatis Generator
*/
@InjectByDataBaseType(includes= {EnumDatabaseName.ORACLE})
public interface CscpUserWorkGroupRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_work_group
     *
     * @mbg.generated Sat Apr 28 14:39:47 CST 2018
     */
    @SelectProvider(type=CscpUserWorkGroupSqlProvider.class, method="countByExample")
    long countByExample(CscpUserWorkGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_work_group
     *
     * @mbg.generated Sat Apr 28 14:39:47 CST 2018
     */
    @DeleteProvider(type=CscpUserWorkGroupSqlProvider.class, method="deleteByExample")
    int deleteByExample(CscpUserWorkGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_work_group
     *
     * @mbg.generated Sat Apr 28 14:39:47 CST 2018
     */
    @Delete({
        "delete from cscp_user_work_group",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_work_group
     *
     * @mbg.generated Sat Apr 28 14:39:47 CST 2018
     */
    @Insert({
        "insert into cscp_user_work_group (id,user_id, group_id)",
        "values (#{id,jdbcType=BIGINT},#{userId,jdbcType=BIGINT}, #{groupId,jdbcType=BIGINT})"
    })
    //@Options(useGeneratedKeys=true, keyProperty="id")
    int insert(CscpUserWorkGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_work_group
     *
     * @mbg.generated Sat Apr 28 14:39:47 CST 2018
     */
    @InsertProvider(type=CscpUserWorkGroupSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true, keyProperty="id")
    int insertSelective(CscpUserWorkGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_work_group
     *
     * @mbg.generated Sat Apr 28 14:39:47 CST 2018
     */
    @SelectProvider(type=CscpUserWorkGroupSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
        @Result(column="group_id", property="groupId", jdbcType=JdbcType.BIGINT)
    })
    List<CscpUserWorkGroup> selectByExample(CscpUserWorkGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_work_group
     *
     * @mbg.generated Sat Apr 28 14:39:47 CST 2018
     */
    @Select({
        "select",
        "id, user_id, group_id",
        "from cscp_user_work_group",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
        @Result(column="group_id", property="groupId", jdbcType=JdbcType.BIGINT)
    })
    CscpUserWorkGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_work_group
     *
     * @mbg.generated Sat Apr 28 14:39:47 CST 2018
     */
    @UpdateProvider(type=CscpUserWorkGroupSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CscpUserWorkGroup record,
                                 @Param("example") CscpUserWorkGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_work_group
     *
     * @mbg.generated Sat Apr 28 14:39:47 CST 2018
     */
    @UpdateProvider(type=CscpUserWorkGroupSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CscpUserWorkGroup record,
                        @Param("example") CscpUserWorkGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_work_group
     *
     * @mbg.generated Sat Apr 28 14:39:47 CST 2018
     */
    @UpdateProvider(type=CscpUserWorkGroupSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CscpUserWorkGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_work_group
     *
     * @mbg.generated Sat Apr 28 14:39:47 CST 2018
     */
    @Update({
        "update cscp_user_work_group",
        "set user_id = #{userId,jdbcType=BIGINT},",
          "group_id = #{groupId,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(CscpUserWorkGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_work_group
     *
     * @mbg.generated Sat Apr 28 14:39:47 CST 2018
     */
    @SelectProvider(type=CscpUserWorkGroupSqlProvider.class, method="selectByExampleWithPage")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
        @Result(column="group_id", property="groupId", jdbcType=JdbcType.BIGINT)
    })
    List<CscpUserWorkGroup> selectByExamplewithPage(CscpUserWorkGroupExample example);

    @Select({
          "select * from cscp_user_work_group where user_id = #{userId}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
            @Result(column="group_id", property="groupId", jdbcType=JdbcType.BIGINT)
    })
    List<CscpUserWorkGroupDTO>  selectUserWorkGroupByUserId(Long userId);

    @Delete({"delete from cscp_user_work_group where user_id = #{userId} "})
    int deleteByUserId(Long userId);
}