package com.ctsi.ssdc.admin.repository;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.ctsi.ssdc.admin.domain.CscpUserOrg;
import com.ctsi.ssdc.admin.domain.CscpUserOrgExample;
import com.ctsi.ssdc.database.annotation.InjectByDataBaseType;
import com.ctsi.ssdc.database.enums.EnumDatabaseName;

/**
 * @author MyBatis Generator
*/
@InjectByDataBaseType(includes= {EnumDatabaseName.ORACLE})
public interface CscpUserOrgRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_org
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    @SelectProvider(type=CscpUserOrgSqlProvider.class, method="countByExample")
    long countByExample(CscpUserOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_org
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    @DeleteProvider(type=CscpUserOrgSqlProvider.class, method="deleteByExample")
    int deleteByExample(CscpUserOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_org
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    @Delete({
        "delete from cscp_user_org",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);
    
    @Delete({
        "truncate table cscp_user_org"
    })
    int truncateCscpUserOrg();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_org
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    @Insert({
        "insert into cscp_user_org (id,user_id, org_id)",
        "values (#{id,jdbcType=BIGINT},#{userId,jdbcType=BIGINT}, #{orgId,jdbcType=BIGINT})"
    })
    //@Options(useGeneratedKeys=true, keyProperty="id")
    int insert(CscpUserOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_org
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    @InsertProvider(type=CscpUserOrgSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true, keyProperty="id")
    int insertSelective(CscpUserOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_org
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    @SelectProvider(type=CscpUserOrgSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
        @Result(column="org_id", property="orgId", jdbcType=JdbcType.BIGINT)
    })
    List<CscpUserOrg> selectByExample(CscpUserOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_org
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    @Select({
        "select",
        "id, user_id, org_id",
        "from cscp_user_org",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
        @Result(column="org_id", property="orgId", jdbcType=JdbcType.BIGINT)
    })
    CscpUserOrg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_org
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    @UpdateProvider(type=CscpUserOrgSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CscpUserOrg record, @Param("example") CscpUserOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_org
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    @UpdateProvider(type=CscpUserOrgSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CscpUserOrg record, @Param("example") CscpUserOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_org
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    @UpdateProvider(type=CscpUserOrgSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CscpUserOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_org
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    @Update({
        "update cscp_user_org",
        "set user_id = #{userId,jdbcType=BIGINT},",
          "org_id = #{orgId,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(CscpUserOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_org
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    @SelectProvider(type=CscpUserOrgSqlProvider.class, method="selectByExampleWithPage")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
        @Result(column="org_id", property="orgId", jdbcType=JdbcType.BIGINT)
    })
    List<CscpUserOrg> selectByExamplewithPage(CscpUserOrgExample example);

    @Select({
            "select * from cscp_user_org where user_id = #{userId} limit 1"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
            @Result(column="org_id", property="orgId", jdbcType=JdbcType.BIGINT)
    })
    CscpUserOrg selectUserOrgByUserId(Long userId);

    @Delete({"delete from cscp_user_org where user_id = #{userId} "})
    int deleteByUserId(Long userId);

    /**
     * 机构人员唯一校验
     * @param userId
     * @return
     */
    @Select({"<script>select count(1) from cscp_user_org  where user_id = #{userId}",
            "<if test='orgId != null' > and org_id != #{orgId} </if></script>"})
    int userOnlyOne(@Param("orgId")Long orgId ,@Param("userId") Long userId);
}