package com.ctsi.ssdc.admin.repository;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.jdbc.SQL;

import com.ctsi.ssdc.admin.domain.CscpMenus;
import com.ctsi.ssdc.admin.domain.CscpMenusExample;
import com.ctsi.ssdc.admin.domain.CscpMenusExample.Criteria;
import com.ctsi.ssdc.admin.domain.CscpMenusExample.Criterion;

/**
 * @author MyBatis Generator
*/
public class CscpMenusSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_menus
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public String countByExample(CscpMenusExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("cscp_menus");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_menus
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public String deleteByExample(CscpMenusExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("cscp_menus");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_menus
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public String insertSelective(CscpMenus record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("cscp_menus");
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getIcon() != null) {
            sql.VALUES("icon", "#{icon,jdbcType=VARCHAR}");
        }
        
        if (record.getTitle() != null) {
            sql.VALUES("title", "#{title,jdbcType=VARCHAR}");
        }
        
        if (record.getUrl() != null) {
            sql.VALUES("url", "#{url,jdbcType=VARCHAR}");
        }
        
        if (record.getHttpMethod() != null) {
            sql.VALUES("http_method", "#{httpMethod,jdbcType=VARCHAR}");
        }
        
        if (record.getComponent() != null) {
            sql.VALUES("component", "#{component,jdbcType=VARCHAR}");
        }
        
        if (record.getParentId() != null) {
            sql.VALUES("parent_id", "#{parentId,jdbcType=BIGINT}");
        }
        
        if (record.getType() != null) {
            sql.VALUES("type", "#{type,jdbcType=VARCHAR}");
        }
        
        if (record.getPermissionCode() != null) {
            sql.VALUES("permission_code", "#{permissionCode,jdbcType=VARCHAR}");
        }
        
        if (record.getOrderby() != null) {
            sql.VALUES("orderby", "#{orderby,jdbcType=BIGINT}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_menus
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public String selectByExample(CscpMenusExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("name");
        sql.SELECT("icon");
        sql.SELECT("title");
        sql.SELECT("url");
        sql.SELECT("http_method");
        sql.SELECT("component");
        sql.SELECT("parent_id");
        sql.SELECT("type");
        sql.SELECT("permission_code");
        sql.SELECT("orderby");
        sql.FROM("cscp_menus");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_menus
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CscpMenus record = (CscpMenus) parameter.get("record");
        CscpMenusExample example = (CscpMenusExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("cscp_menus");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=BIGINT}");
        }
        
        if (record.getName() != null) {
            sql.SET("name = #{record.name,jdbcType=VARCHAR}");
        }
        
        if (record.getIcon() != null) {
            sql.SET("icon = #{record.icon,jdbcType=VARCHAR}");
        }
        
        if (record.getTitle() != null) {
            sql.SET("title = #{record.title,jdbcType=VARCHAR}");
        }
        
        if (record.getUrl() != null) {
            sql.SET("url = #{record.url,jdbcType=VARCHAR}");
        }
        
        if (record.getHttpMethod() != null) {
            sql.SET("http_method = #{record.httpMethod,jdbcType=VARCHAR}");
        }
        
        if (record.getComponent() != null) {
            sql.SET("component = #{record.component,jdbcType=VARCHAR}");
        }
        
        if (record.getParentId() != null) {
            sql.SET("parent_id = #{record.parentId,jdbcType=BIGINT}");
        }
        
        if (record.getType() != null) {
            sql.SET("type = #{record.type,jdbcType=VARCHAR}");
        }
        
        if (record.getPermissionCode() != null) {
            sql.SET("permission_code = #{record.permissionCode,jdbcType=VARCHAR}");
        }
        
        if (record.getOrderby() != null) {
            sql.SET("orderby = #{record.orderby,jdbcType=BIGINT}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_menus
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_menus");
        
        sql.SET("id = #{record.id,jdbcType=BIGINT}");
        sql.SET("name = #{record.name,jdbcType=VARCHAR}");
        sql.SET("icon = #{record.icon,jdbcType=VARCHAR}");
        sql.SET("title = #{record.title,jdbcType=VARCHAR}");
        sql.SET("url = #{record.url,jdbcType=VARCHAR}");
        sql.SET("http_method = #{record.httpMethod,jdbcType=VARCHAR}");
        sql.SET("component = #{record.component,jdbcType=VARCHAR}");
        sql.SET("parent_id = #{record.parentId,jdbcType=BIGINT}");
        sql.SET("type = #{record.type,jdbcType=VARCHAR}");
        sql.SET("permission_code = #{record.permissionCode,jdbcType=VARCHAR}");
        sql.SET("orderby = #{record.orderby,jdbcType=BIGINT}");
        
        CscpMenusExample example = (CscpMenusExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_menus
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public String updateByPrimaryKeySelective(CscpMenus record) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_menus");
        
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getIcon() != null) {
            sql.SET("icon = #{icon,jdbcType=VARCHAR}");
        }
        
        if (record.getTitle() != null) {
            sql.SET("title = #{title,jdbcType=VARCHAR}");
        }
        
        if (record.getUrl() != null) {
            sql.SET("url = #{url,jdbcType=VARCHAR}");
        }
        
        if (record.getHttpMethod() != null) {
            sql.SET("http_method = #{httpMethod,jdbcType=VARCHAR}");
        }
        
        if (record.getComponent() != null) {
            sql.SET("component = #{component,jdbcType=VARCHAR}");
        }
        
        if (record.getParentId() != null) {
            sql.SET("parent_id = #{parentId,jdbcType=BIGINT}");
        }
        
        if (record.getType() != null) {
            sql.SET("type = #{type,jdbcType=VARCHAR}");
        }
        
        if (record.getPermissionCode() != null) {
            sql.SET("permission_code = #{permissionCode,jdbcType=VARCHAR}");
        }
        
        if (record.getOrderby() != null) {
            sql.SET("orderby = #{orderby,jdbcType=BIGINT}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_menus
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    protected void applyWhere(SQL sql, CscpMenusExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1Th;
        String parmPhrase2;
        String parmPhrase2Th;
        String parmPhrase3;
        String parmPhrase3Th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} " +
                    "and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} " +
                    "and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and " +
                    "#{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and " +
                    "#{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1Th,
                                    criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2Th, criterion.getCondition(),
                                    i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3Th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_menus
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public String selectByExampleWithPage(CscpMenusExample example) {
        return selectByExample(example);
    }
}