package com.ctsi.ssdc.admin.repository;

import com.ctsi.ssdc.admin.domain.CscpTenant;
import com.ctsi.ssdc.admin.domain.CscpTenantExample;
import com.ctsi.ssdc.admin.domain.CscpTenantExample.Criteria;
import com.ctsi.ssdc.admin.domain.CscpTenantExample.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

/**
 * @author ctsi-biyi-generator
*/
public class CscpTenantSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_tenant
     *
     * @mbg.generated Thu Jan 06 14:30:38 CST 2022
     */
    public String countByExample(CscpTenantExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("cscp_tenant");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_tenant
     *
     * @mbg.generated Thu Jan 06 14:30:38 CST 2022
     */
    public String deleteByExample(CscpTenantExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("cscp_tenant");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_tenant
     *
     * @mbg.generated Thu Jan 06 14:30:38 CST 2022
     */
    public String insertSelective(CscpTenant record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("cscp_tenant");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getTenantAccount() != null) {
            sql.VALUES("tenant_account", "#{tenantAccount,jdbcType=VARCHAR}");
        }
        
        if (record.getTenantName() != null) {
            sql.VALUES("tenant_name", "#{tenantName,jdbcType=VARCHAR}");
        }
        
        if (record.getContacts() != null) {
            sql.VALUES("contacts", "#{contacts,jdbcType=VARCHAR}");
        }
        
        if (record.getPhone() != null) {
            sql.VALUES("phone", "#{phone,jdbcType=VARCHAR}");
        }
        
        if (record.getExpireTime() != null) {
            sql.VALUES("expire_time", "#{expireTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getActiveFlag() != null) {
            sql.VALUES("active_flag", "#{activeFlag,jdbcType=CHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_tenant
     *
     * @mbg.generated Thu Jan 06 14:30:38 CST 2022
     */
    public String selectByExample(CscpTenantExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("ct.id");
        } else {
            sql.SELECT("ct.id");
        }
        sql.SELECT("ct.tenant_account");
        sql.SELECT("ct.tenant_name");
        sql.SELECT("ct.contacts");
        sql.SELECT("ct.phone");
        sql.SELECT("ct.expire_time");
        sql.SELECT("ct.active_flag");
        sql.FROM("cscp_tenant ct, cscp_user_detail cud");
        sql.WHERE("ct.id = cud.tenant_id AND cud.admin_flag = '1'");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_tenant
     *
     * @mbg.generated Thu Jan 06 14:30:38 CST 2022
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CscpTenant record = (CscpTenant) parameter.get("record");
        CscpTenantExample example = (CscpTenantExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("cscp_tenant");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=BIGINT}");
        }
        
        if (record.getTenantAccount() != null) {
            sql.SET("tenant_account = #{record.tenantAccount,jdbcType=VARCHAR}");
        }
        
        if (record.getTenantName() != null) {
            sql.SET("tenant_name = #{record.tenantName,jdbcType=VARCHAR}");
        }
        
        if (record.getContacts() != null) {
            sql.SET("contacts = #{record.contacts,jdbcType=VARCHAR}");
        }
        
        if (record.getPhone() != null) {
            sql.SET("phone = #{record.phone,jdbcType=VARCHAR}");
        }
        
        if (record.getExpireTime() != null) {
            sql.SET("expire_time = #{record.expireTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getActiveFlag() != null) {
            sql.SET("active_flag = #{record.activeFlag,jdbcType=CHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_tenant
     *
     * @mbg.generated Thu Jan 06 14:30:38 CST 2022
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_tenant");
        
        sql.SET("id = #{record.id,jdbcType=BIGINT}");
        sql.SET("tenant_account = #{record.tenantAccount,jdbcType=VARCHAR}");
        sql.SET("tenant_name = #{record.tenantName,jdbcType=VARCHAR}");
        sql.SET("contacts = #{record.contacts,jdbcType=VARCHAR}");
        sql.SET("phone = #{record.phone,jdbcType=VARCHAR}");
        sql.SET("expire_time = #{record.expireTime,jdbcType=TIMESTAMP}");
        sql.SET("active_flag = #{record.activeFlag,jdbcType=CHAR}");
        
        CscpTenantExample example = (CscpTenantExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_tenant
     *
     * @mbg.generated Thu Jan 06 14:30:38 CST 2022
     */
    public String updateByPrimaryKeySelective(CscpTenant record) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_tenant");
        
        if (record.getTenantAccount() != null) {
            sql.SET("tenant_account = #{tenantAccount,jdbcType=VARCHAR}");
        }
        
        if (record.getTenantName() != null) {
            sql.SET("tenant_name = #{tenantName,jdbcType=VARCHAR}");
        }
        
        if (record.getContacts() != null) {
            sql.SET("contacts = #{contacts,jdbcType=VARCHAR}");
        }
        
        if (record.getPhone() != null) {
            sql.SET("phone = #{phone,jdbcType=VARCHAR}");
        }
        
        if (record.getExpireTime() != null) {
            sql.SET("expire_time = #{expireTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getActiveFlag() != null) {
            sql.SET("active_flag = #{activeFlag,jdbcType=CHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_tenant
     *
     * @mbg.generated Thu Jan 06 14:30:38 CST 2022
     */
    protected void applyWhere(SQL sql, CscpTenantExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1Th;
        String parmPhrase2;
        String parmPhrase2Th;
        String parmPhrase3;
        String parmPhrase3Th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1Th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2Th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3Th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}