package com.ctsi.ssdc.admin.repository;

import com.ctsi.ssdc.admin.domain.CscpRoleDept;
import com.ctsi.ssdc.admin.domain.CscpRoleDeptExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

/**
 * @author ctsi-biyi-generator
*/
@Mapper
public interface CscpRoleDeptRepository extends com.ctsi.ssdc.repository.BaseRepository<CscpRoleDept, Long, CscpRoleDeptExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_role_dept
     *
     * @mbg.generated Tue Jan 11 14:51:44 CST 2022
     */
    @SelectProvider(type=CscpRoleDeptSqlProvider.class, method="countByExample")
    @Override
    long countByExample(CscpRoleDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_role_dept
     *
     * @mbg.generated Tue Jan 11 14:51:44 CST 2022
     */
    @DeleteProvider(type=CscpRoleDeptSqlProvider.class, method="deleteByExample")
    @Override
    int deleteByExample(CscpRoleDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_role_dept
     *
     * @mbg.generated Tue Jan 11 14:51:44 CST 2022
     */
    @Delete({
        "delete from cscp_role_dept",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_role_dept
     *
     * @mbg.generated Tue Jan 11 14:51:44 CST 2022
     */
    @Insert({
        "insert into cscp_role_dept (id, role_id, ",
        "dept_id)",
        "values (#{id,jdbcType=BIGINT}, #{roleId,jdbcType=BIGINT}, ",
        "#{deptId,jdbcType=BIGINT})"
    })
    @Override
    int insert(CscpRoleDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_role_dept
     *
     * @mbg.generated Tue Jan 11 14:51:44 CST 2022
     */
    @InsertProvider(type=CscpRoleDeptSqlProvider.class, method="insertSelective")
    @Override
    int insertSelective(CscpRoleDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_role_dept
     *
     * @mbg.generated Tue Jan 11 14:51:44 CST 2022
     */
    @SelectProvider(type=CscpRoleDeptSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="role_id", property="roleId", jdbcType=JdbcType.BIGINT),
        @Result(column="dept_id", property="deptId", jdbcType=JdbcType.BIGINT)
    })
    @Override
    List<CscpRoleDept> selectByExample(CscpRoleDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_role_dept
     *
     * @mbg.generated Tue Jan 11 14:51:44 CST 2022
     */
    @Select({
        "select",
        "id, role_id, dept_id",
        "from cscp_role_dept",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="role_id", property="roleId", jdbcType=JdbcType.BIGINT),
        @Result(column="dept_id", property="deptId", jdbcType=JdbcType.BIGINT)
    })
    @Override
    CscpRoleDept selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_role_dept
     *
     * @mbg.generated Tue Jan 11 14:51:44 CST 2022
     */
    @UpdateProvider(type=CscpRoleDeptSqlProvider.class, method="updateByExampleSelective")
    @Override
    int updateByExampleSelective(@Param("record") CscpRoleDept record, @Param("example") CscpRoleDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_role_dept
     *
     * @mbg.generated Tue Jan 11 14:51:44 CST 2022
     */
    @UpdateProvider(type=CscpRoleDeptSqlProvider.class, method="updateByExample")
    @Override
    int updateByExample(@Param("record") CscpRoleDept record, @Param("example") CscpRoleDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_role_dept
     *
     * @mbg.generated Tue Jan 11 14:51:44 CST 2022
     */
    @UpdateProvider(type=CscpRoleDeptSqlProvider.class, method="updateByPrimaryKeySelective")
    @Override
    int updateByPrimaryKeySelective(CscpRoleDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_role_dept
     *
     * @mbg.generated Tue Jan 11 14:51:44 CST 2022
     */
    @Update({
        "update cscp_role_dept",
        "set role_id = #{roleId,jdbcType=BIGINT},",
          "dept_id = #{deptId,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int updateByPrimaryKey(CscpRoleDept record);


    /**
     * 通过角色ID删除角色和部门关联
     *
     * @param roleId 角色ID
     * @return 结果
     */
    @Delete({
            "delete from cscp_role_dept where role_id=#{roleId}"
    })
    int deleteRoleDeptByRoleId(Long roleId);


    /**
     * 批量新增角色部门信息
     *
     * @param roleDeptList 角色部门列表
     * @return 结果
     */
    @Insert({"<script>",
            "insert into cscp_role_dept(role_id, dept_id) values",
            "<foreach item=\"item\" index=\"index\" collection=\"list\" separator=\",\">",
            "(#{item.roleId},#{item.deptId})",
            "</foreach>",
            "</script>",
    })
    int batchRoleDept(List<CscpRoleDept> roleDeptList);


    /**
     * 批量删除部门角色关联
     * @param deptIds
     */

    @Delete("<script>" +
            "delete from cscp_role_dept where dept_id in" +
            "<foreach collection=\"deptIds\" item=\"id\" open=\"(\" separator=\",\" close=\")\">" +
            "#{id}" +
            "</foreach>" +
            "</script>")
    void  deleteByDeptIds(@Param("deptIds")List<Long> deptIds);
}