package com.ctsi.ssdc.quartz.repository;

import java.util.List;

import com.ctsi.ssdc.quartz.domain.CscpJobLog;
import com.ctsi.ssdc.quartz.domain.CscpJobLogExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

/**
 * SysJobLogRepository
 *
 * @author hx
 * @date 2022-05-30 17:05:20
 */

@Mapper
public interface CscpJobLogRepository extends com.ctsi.ssdc.repository.BaseRepository<CscpJobLog, Long, CscpJobLogExample> {
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sys_job_log
     *
     * @date 2022-05-30 17:05:20
     */
    @SelectProvider(type= CscpJobLogSqlProvider.class, method="countByExample")
    @Override
    long countByExample(CscpJobLogExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sys_job_log
     *
     * @date 2022-05-30 17:05:20
     */
    @DeleteProvider(type= CscpJobLogSqlProvider.class, method="deleteByExample")
    @Override
    int deleteByExample(CscpJobLogExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sys_job_log
     *
     * @date 2022-05-30 17:05:20
     */
    @Delete({
            "delete from sys_job_log",
            "where job_log_id = #{jobLogId,jdbcType=BIGINT}"
    })
    @Override
    int deleteByPrimaryKey(Long jobLogId);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sys_job_log
     *
     *
     * @date 2022-05-30 17:05:20
     */
    @Insert({
            "insert into sys_job_log (",
            "job_message,",
            "exception_info,",
            "invoke_target,",
            "job_group,",
            "status,",
            "execution_time,",
            "job_name,",
            "job_log_id",
            ") values (",
            "#{jobMessage,jdbcType=VARCHAR}, ",
            "#{exceptionInfo,jdbcType=VARCHAR}, ",
            "#{invokeTarget,jdbcType=VARCHAR}, ",
            "#{jobGroup,jdbcType=VARCHAR}, ",
            "#{status,jdbcType=VARCHAR}, ",
            "#{executionTime,jdbcType=DATE}, ",
            "#{jobName,jdbcType=VARCHAR}, ",
            "#{jobLogId,jdbcType=BIGINT}",

            ")"

    })
    @Override
    int insert(CscpJobLog record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sys_job_log
     *
     * @date 2022-05-30 17:05:20
     */
    @InsertProvider(type= CscpJobLogSqlProvider.class, method="insertSelective")
    @Override
    int insertSelective(CscpJobLog record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sys_job_log
     *
     * @date 2022-05-30 17:05:20
     */
    @SelectProvider(type= CscpJobLogSqlProvider.class, method="selectByExample")
    @Results({
            @Result(column="job_message", property="jobMessage", jdbcType=JdbcType.VARCHAR,id=true ),
            @Result(column="exception_info", property="exceptionInfo", jdbcType=JdbcType.VARCHAR),
            @Result(column="invoke_target", property="invokeTarget", jdbcType=JdbcType.VARCHAR),
            @Result(column="job_group", property="jobGroup", jdbcType=JdbcType.VARCHAR),
            @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
            @Result(column="execution_time", property="executionTime", jdbcType=JdbcType.DATE),
            @Result(column="job_name", property="jobName", jdbcType=JdbcType.VARCHAR),
            @Result(column="job_log_id", property="jobLogId", jdbcType=JdbcType.BIGINT)
    })

    @Override
    List<CscpJobLog> selectByExample(CscpJobLogExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sys_job_log
     *
     * @date 2022-05-30 17:05:20
     */
    @Select({
            "select",
            "job_message,",
            "exception_info,",
            "invoke_target,",
            "job_group,",
            "status,",
            "execution_time,",
            "job_name,",
            "job_log_id",
            "from sys_job_log",
            "where job_log_id = #{jobLogId,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column="job_message", property="jobMessage", jdbcType=JdbcType.VARCHAR,id=true ),
            @Result(column="exception_info", property="exceptionInfo", jdbcType=JdbcType.VARCHAR),
            @Result(column="invoke_target", property="invokeTarget", jdbcType=JdbcType.VARCHAR),
            @Result(column="job_group", property="jobGroup", jdbcType=JdbcType.VARCHAR),
            @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
            @Result(column="execution_time", property="executionTime", jdbcType=JdbcType.DATE),
            @Result(column="job_name", property="jobName", jdbcType=JdbcType.VARCHAR),
            @Result(column="job_log_id", property="jobLogId", jdbcType=JdbcType.BIGINT)
    })
    @Override
    CscpJobLog selectByPrimaryKey(Long jobLogId);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sys_job_log
     *
     * @date 2022-05-30 17:05:20
     */
    @UpdateProvider(type= CscpJobLogSqlProvider.class, method="updateByExampleSelective")
    @Override
    int updateByExampleSelective(@Param("record") CscpJobLog record, @Param("example") CscpJobLogExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sys_job_log
     *
     * @date 2022-05-30 17:05:20
     */
    @UpdateProvider(type= CscpJobLogSqlProvider.class, method="updateByExample")
    @Override
    int updateByExample(@Param("record") CscpJobLog record, @Param("example") CscpJobLogExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sys_job_log
     *
     *@date 2022-05-30 17:05:20
     */
    @UpdateProvider(type= CscpJobLogSqlProvider.class, method="updateByPrimaryKeySelective")
    @Override
    int updateByPrimaryKeySelective(CscpJobLog record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table sys_job_log
     *
     * @date 2022-05-30 17:05:20
     */
    @Update({
            "update sys_job_log",
            "set ",
            "job_message = #{jobMessage,jdbcType=VARCHAR},",
            "exception_info = #{exceptionInfo,jdbcType=VARCHAR},",
            "invoke_target = #{invokeTarget,jdbcType=VARCHAR},",
            "job_group = #{jobGroup,jdbcType=VARCHAR},",
            "status = #{status,jdbcType=VARCHAR},",
            "execution_time = #{executionTime,jdbcType=DATE},",
            "job_name = #{jobName,jdbcType=VARCHAR},",
            "job_log_id = #{jobLogId,jdbcType=BIGINT}",

            "where job_log_id = #{jobLogId,jdbcType=BIGINT}"
    })
    @Override
    int updateByPrimaryKey(CscpJobLog record);

    /**
     * 批量删除
     * @param jobLogIds
     */
    @Delete("<script>" +
            "delete from sys_job_log where job_log_id in" +
            "<foreach collection=\"jobLogIds\" item=\"jobLogId\" open=\"(\" separator=\",\" close=\")\">" +
            "#{jobLogId}" +
            "</foreach>" +
            "</script>")
    void deleteByIds(@Param("jobLogIds") List<Long> jobLogIds);


}





