package com.ctsi.ssdc.quartz.repository;

import com.ctsi.ssdc.quartz.domain.CscpJob;
import com.ctsi.ssdc.quartz.domain.CscpJobExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

/**
 * @author ctsi-biyi-generator
*/
@Mapper
public interface CscpJobRepository extends com.ctsi.ssdc.repository.BaseRepository<CscpJob, Long, CscpJobExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysJob
     *
     * @mbg.generated Tue Oct 26 15:45:00 CST 2021
     */
    @SelectProvider(type= CscpJobSqlProvider.class, method="countByExample")
    @Override
    long countByExample(CscpJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Tue Oct 26 15:45:00 CST 2021
     */
    @DeleteProvider(type= CscpJobSqlProvider.class, method="deleteByExample")
    @Override
    int deleteByExample(CscpJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Tue Oct 26 15:45:00 CST 2021
     */
    @Delete({
        "delete from sys_job",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Tue Oct 26 15:45:00 CST 2021
     */
    @Insert({
        "insert into sys_job (id, job_name, ",
        "job_group, invoke_target, ",
        "cron_expression, misfire_policy, ",
        "concurrent,status)",
        "values (#{id,jdbcType=BIGINT}, #{jobName,jdbcType=VARCHAR}, ",
        "#{jobGroup,jdbcType=VARCHAR}, #{invokeTarget,jdbcType=VARCHAR}, ",
        "#{cronExpression,jdbcType=VARCHAR}, #{misfirePolicy,jdbcType=VARCHAR}, ",
        "#{concurrent,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR})"
    })
    @Override
    int insert(CscpJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Tue Oct 26 15:45:00 CST 2021
     */
    @InsertProvider(type= CscpJobSqlProvider.class, method="insertSelective")
    @Override
    int insertSelective(CscpJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Tue Oct 26 15:45:00 CST 2021
     */
    @SelectProvider(type= CscpJobSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="job_name", property="jobName", jdbcType=JdbcType.VARCHAR),
        @Result(column="job_group", property="jobGroup", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoke_target", property="invokeTarget", jdbcType=JdbcType.VARCHAR),
        @Result(column="cron_expression", property="cronExpression", jdbcType=JdbcType.VARCHAR),
        @Result(column="misfire_policy", property="misfirePolicy", jdbcType=JdbcType.VARCHAR),
        @Result(column="concurrent", property="concurrent", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR)
    })
    @Override
    List<CscpJob> selectByExample(CscpJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Tue Oct 26 15:45:00 CST 2021
     */
    @Select({
        "select",
        "id, job_name, job_group, invoke_target, cron_expression, misfire_policy, concurrent, status",
        "from sys_job",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="job_name", property="jobName", jdbcType=JdbcType.VARCHAR),
        @Result(column="job_group", property="jobGroup", jdbcType=JdbcType.VARCHAR),
        @Result(column="invoke_target", property="invokeTarget", jdbcType=JdbcType.VARCHAR),
        @Result(column="cron_expression", property="cronExpression", jdbcType=JdbcType.VARCHAR),
        @Result(column="misfire_policy", property="misfirePolicy", jdbcType=JdbcType.VARCHAR),
        @Result(column="concurrent", property="concurrent", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR)
    })
    @Override
    CscpJob selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Tue Oct 26 15:45:00 CST 2021
     */
    @UpdateProvider(type= CscpJobSqlProvider.class, method="updateByExampleSelective")
    @Override
    int updateByExampleSelective(@Param("record") CscpJob record, @Param("example") CscpJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Tue Oct 26 15:45:00 CST 2021
     */
    @UpdateProvider(type= CscpJobSqlProvider.class, method="updateByExample")
    @Override
    int updateByExample(@Param("record") CscpJob record, @Param("example") CscpJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Tue Oct 26 15:45:00 CST 2021
     */
    @UpdateProvider(type= CscpJobSqlProvider.class, method="updateByPrimaryKeySelective")
    @Override
    int updateByPrimaryKeySelective(CscpJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Tue Oct 26 15:45:00 CST 2021
     */
    @Update({
        "update sys_job",
        "set job_name = #{jobName,jdbcType=VARCHAR},",
          "job_group = #{jobGroup,jdbcType=VARCHAR},",
          "invoke_target = #{invokeTarget,jdbcType=VARCHAR},",
          "cron_expression = #{cronExpression,jdbcType=VARCHAR},",
          "misfire_policy = #{misfirePolicy,jdbcType=VARCHAR},",
          "concurrent = #{concurrent,jdbcType=VARCHAR},", "status = #{status,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int updateByPrimaryKey(CscpJob record);

    /**
     * 批量删除
     * @param ids
     */
    @Delete("<script>" +
            "delete from  sys_job  where id in" +
            "<foreach collection=\"ids\" item=\"id\" open=\"(\" separator=\",\" close=\")\">" +
            "#{id}" +
            "</foreach>" +
            "</script>")
    void deleteByIds(@Param("ids")  Long[] ids);
}