package com.ctsi.ssdc.sensitiveword.repository;

import java.util.List;
import java.util.Map;

import com.ctsi.ssdc.sensitiveword.domain.CscpSensitiveWord;
import com.ctsi.ssdc.sensitiveword.domain.CscpSensitiveWordExample;
import org.apache.ibatis.jdbc.SQL;


/**
 * @author ctsi-biyi-generator
*/
public class CscpSensitiveWordSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_sensitive_word
     *
     */
    public String countByExample(CscpSensitiveWordExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("cscp_sensitive_word");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_sensitive_word
     *
     */
    public String deleteByExample(CscpSensitiveWordExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("cscp_sensitive_word");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_sensitive_word
     *
     */
    public String insertSelective(CscpSensitiveWord record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("cscp_sensitive_word");
        
        if (record.getSenTypeId() != null) {
            sql.VALUES("sen_type_id", "#{senTypeId,jdbcType=BIGINT}");
        }
        
        if (record.getSenContent() != null) {
            sql.VALUES("sen_content", "#{senContent,jdbcType=VARCHAR}");
        }
        
        if (record.getSenReplace() != null) {
            sql.VALUES("sen_replace", "#{senReplace,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_sensitive_word
     *
     */
    public String selectByExample(CscpSensitiveWordExample example) {
    	SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("a.id");
        } else {
            sql.SELECT("a.id");
        }
        sql.SELECT("sen_type_id");
        sql.SELECT("sen_type_name");
        sql.SELECT("sen_content");
        sql.SELECT("sen_replace");
        sql.SELECT("a.update_time");
        sql.FROM("cscp_sensitive_word a left join cscp_sensitive_word_type b on a.sen_type_id = b.id ");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_sensitive_word
     *
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CscpSensitiveWord record = (CscpSensitiveWord) parameter.get("record");
        CscpSensitiveWordExample example = (CscpSensitiveWordExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("cscp_sensitive_word");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=BIGINT}");
        }
        
        if (record.getSenTypeId() != null) {
            sql.SET("sen_type_id = #{record.senTypeId,jdbcType=BIGINT}");
        }
        
        if (record.getSenContent() != null) {
            sql.SET("sen_content = #{record.senContent,jdbcType=VARCHAR}");
        }
        
        if (record.getSenReplace() != null) {
            sql.SET("sen_replace = #{record.senReplace,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_sensitive_word
     *
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_sensitive_word");
        
        sql.SET("id = #{record.id,jdbcType=BIGINT}");
        sql.SET("sen_type_id = #{record.senTypeId,jdbcType=BIGINT}");
        sql.SET("sen_content = #{record.senContent,jdbcType=VARCHAR}");
        sql.SET("sen_replace = #{record.senReplace,jdbcType=VARCHAR}");
        sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        
        CscpSensitiveWordExample example = (CscpSensitiveWordExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_sensitive_word
     *
     */
    public String updateByPrimaryKeySelective(CscpSensitiveWord record) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_sensitive_word");
        
        if (record.getSenTypeId() != null) {
            sql.SET("sen_type_id = #{senTypeId,jdbcType=BIGINT}");
        }
        
        if (record.getSenContent() != null) {
            sql.SET("sen_content = #{senContent,jdbcType=VARCHAR}");
        }
        
        if (record.getSenReplace() != null) {
            sql.SET("sen_replace = #{senReplace,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_sensitive_word
     *
     */
    protected void applyWhere(SQL sql, CscpSensitiveWordExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1Th;
        String parmPhrase2;
        String parmPhrase2Th;
        String parmPhrase3;
        String parmPhrase3Th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<CscpSensitiveWordExample.Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            CscpSensitiveWordExample.Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<CscpSensitiveWordExample.Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    CscpSensitiveWordExample.Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1Th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2Th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3Th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}