package com.ctsi.flow.param.model;

import com.ctsi.ssdc.criteria.*;

import com.ctsi.ssdc.example.BaseExample;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.annotations.ApiParam;
import java.util.ArrayList;
import java.util.List;
import org.apache.commons.lang3.StringUtils;

/**
 * ActOperatePermExample
 *
 * @author hx
 * @date 2022-07-22 09:25:13
 */

public class ActOperatePermExample extends BaseExample {

    /**
     * This field was generated by  Generator.
     * This field corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    protected String orderByClause;

    /**
     * This field was generated by  Generator.
     * This field corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    protected boolean distinct;

    /**
     * This field was generated by  Generator.
     * This field corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by  Generator.
     * This field corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    private static final String LIKE_FORMAT = "%%%s%%";


        /**
         *
         * This field was generated by  Generator.
         * This field corresponds to the database column cscp_operate_perm.id
         *
         * @date 2022-07-22 09:25:13
         */
    private LongCriteria id;

        /**
         *
         * This field was generated by  Generator.
         * This field corresponds to the database column cscp_operate_perm.task_definition_Key
         *
         * @date 2022-07-22 09:25:13
         */
    private StringCriteria taskDefinitionKey;

        /**
         *
         * This field was generated by  Generator.
         * This field corresponds to the database column cscp_operate_perm.task_definition_name
         *
         * @date 2022-07-22 09:25:13
         */
    private StringCriteria taskDefinitionName;

        /**
         *
         * This field was generated by  Generator.
         * This field corresponds to the database column cscp_operate_perm.perms
         *
         * @date 2022-07-22 09:25:13
         */
    private StringCriteria perms;


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    public ActOperatePermExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    @Override
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    public LongCriteria getId() {
        return id;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    public void setId(LongCriteria id) {
        this. id = id;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    private void buildIdCriteria(Criteria criteria) {
        if (this.getId() == null) {
            return;
        }
        if (this.getId().getEquals() != null) {
            criteria.andIdEqualTo(this.getId().getEquals());
        } else {
            if (this.getId().getGreaterOrEqualThan() != null) {
                criteria.andIdGreaterThanOrEqualTo(this.getId().getGreaterOrEqualThan());
            }
            if (this.getId().getLessOrEqualThan() != null) {
                criteria.andIdLessThanOrEqualTo(this.getId().getLessOrEqualThan());
            }
        }
    }
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    public StringCriteria getTaskDefinitionKey() {
        return taskDefinitionKey;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    public void setTaskDefinitionKey(StringCriteria taskDefinitionKey) {
        this. taskDefinitionKey = taskDefinitionKey;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    private void buildTaskDefinitionKeyCriteria(Criteria criteria) {
        if (this.getTaskDefinitionKey() == null) {
            return;
        }
        if (this.getTaskDefinitionKey().getEquals() != null) {
            criteria.andTaskDefinitionKeyEqualTo(this.getTaskDefinitionKey().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getTaskDefinitionKey().getContains())) {
                criteria.andTaskDefinitionKeyLike(String.format(LIKE_FORMAT, this.getTaskDefinitionKey().getContains()));
            }
        }
    }
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    public StringCriteria getTaskDefinitionName() {
        return taskDefinitionName;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    public void setTaskDefinitionName(StringCriteria taskDefinitionName) {
        this. taskDefinitionName = taskDefinitionName;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    private void buildTaskDefinitionNameCriteria(Criteria criteria) {
        if (this.getTaskDefinitionName() == null) {
            return;
        }
        if (this.getTaskDefinitionName().getEquals() != null) {
            criteria.andTaskDefinitionNameEqualTo(this.getTaskDefinitionName().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getTaskDefinitionName().getContains())) {
                criteria.andTaskDefinitionNameLike(String.format(LIKE_FORMAT, this.getTaskDefinitionName().getContains()));
            }
        }
    }
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    public StringCriteria getPerms() {
        return perms;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    public void setPerms(StringCriteria perms) {
        this. perms = perms;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    private void buildPermsCriteria(Criteria criteria) {
        if (this.getPerms() == null) {
            return;
        }
        if (this.getPerms().getEquals() != null) {
            criteria.andPermsEqualTo(this.getPerms().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getPerms().getContains())) {
                criteria.andPermsLike(String.format(LIKE_FORMAT, this.getPerms().getContains()));
            }
        }
    }
    /**
      * This method was generated by  Generator.
      * This method corresponds to the database table cscp_hx_form_column
      *
      * @date Thu Feb 17 14:02:06 CST 2022
      */
    @Override
    public Object buildCriteria() {
        Criteria criteria = this.createCriteria();
        this.buildIdCriteria(criteria);
        this.buildTaskDefinitionKeyCriteria(criteria);
        this.buildTaskDefinitionNameCriteria(criteria);
        this.buildPermsCriteria(criteria);
        return criteria;
    }

    protected abstract static class BaseGeneratedCriteria {
        protected List<Criterion> criteria;

        protected BaseGeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }


        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyIsNull() {
            addCriterion("task_definition_Key is null");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyIsNotNull() {
            addCriterion("task_definition_Key is not null");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyEqualTo(String value) {
            addCriterion("task_definition_Key =", value, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyNotEqualTo(String value) {
            addCriterion("task_definition_Key <>", value, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyGreaterThan(String value) {
            addCriterion("task_definition_Key >", value, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyGreaterThanOrEqualTo(String value) {
            addCriterion("task_definition_Key >=", value, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyLessThan(String value) {
            addCriterion("task_definition_Key <", value, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyLessThanOrEqualTo(String value) {
            addCriterion("task_definition_Key <=", value, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyLike(String value) {
            addCriterion("task_definition_Key like", value, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyNotLike(String value) {
            addCriterion("task_definition_Key not like", value, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyIn(List<String> values) {
            addCriterion("task_definition_Key in", values, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyNotIn(List<String> values) {
            addCriterion("task_definition_Key not in", values, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyBetween(String value1, String value2) {
            addCriterion("task_definition_Key between", value1, value2, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyNotBetween(String value1, String value2) {
            addCriterion("task_definition_Key not between", value1, value2, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionNameIsNull() {
            addCriterion("task_definition_name is null");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionNameIsNotNull() {
            addCriterion("task_definition_name is not null");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionNameEqualTo(String value) {
            addCriterion("task_definition_name =", value, "taskDefinitionName");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionNameNotEqualTo(String value) {
            addCriterion("task_definition_name <>", value, "taskDefinitionName");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionNameGreaterThan(String value) {
            addCriterion("task_definition_name >", value, "taskDefinitionName");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionNameGreaterThanOrEqualTo(String value) {
            addCriterion("task_definition_name >=", value, "taskDefinitionName");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionNameLessThan(String value) {
            addCriterion("task_definition_name <", value, "taskDefinitionName");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionNameLessThanOrEqualTo(String value) {
            addCriterion("task_definition_name <=", value, "taskDefinitionName");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionNameLike(String value) {
            addCriterion("task_definition_name like", value, "taskDefinitionName");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionNameNotLike(String value) {
            addCriterion("task_definition_name not like", value, "taskDefinitionName");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionNameIn(List<String> values) {
            addCriterion("task_definition_name in", values, "taskDefinitionName");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionNameNotIn(List<String> values) {
            addCriterion("task_definition_name not in", values, "taskDefinitionName");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionNameBetween(String value1, String value2) {
            addCriterion("task_definition_name between", value1, value2, "taskDefinitionName");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionNameNotBetween(String value1, String value2) {
            addCriterion("task_definition_name not between", value1, value2, "taskDefinitionName");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionFlagEqualTo(String value) {
            addCriterion("task_definition_flag =", value, "taskDefinitionFlag");
            return (Criteria) this;
        }

        public Criteria andPermsIsNull() {
            addCriterion("perms is null");
            return (Criteria) this;
        }

        public Criteria andPermsIsNotNull() {
            addCriterion("perms is not null");
            return (Criteria) this;
        }

        public Criteria andPermsEqualTo(String value) {
            addCriterion("perms =", value, "perms");
            return (Criteria) this;
        }

        public Criteria andPermsNotEqualTo(String value) {
            addCriterion("perms <>", value, "perms");
            return (Criteria) this;
        }

        public Criteria andPermsGreaterThan(String value) {
            addCriterion("perms >", value, "perms");
            return (Criteria) this;
        }

        public Criteria andPermsGreaterThanOrEqualTo(String value) {
            addCriterion("perms >=", value, "perms");
            return (Criteria) this;
        }

        public Criteria andPermsLessThan(String value) {
            addCriterion("perms <", value, "perms");
            return (Criteria) this;
        }

        public Criteria andPermsLessThanOrEqualTo(String value) {
            addCriterion("perms <=", value, "perms");
            return (Criteria) this;
        }

        public Criteria andPermsLike(String value) {
            addCriterion("perms like", value, "perms");
            return (Criteria) this;
        }

        public Criteria andPermsNotLike(String value) {
            addCriterion("perms not like", value, "perms");
            return (Criteria) this;
        }

        public Criteria andPermsIn(List<String> values) {
            addCriterion("perms in", values, "perms");
            return (Criteria) this;
        }

        public Criteria andPermsNotIn(List<String> values) {
            addCriterion("perms not in", values, "perms");
            return (Criteria) this;
        }

        public Criteria andPermsBetween(String value1, String value2) {
            addCriterion("perms between", value1, value2, "perms");
            return (Criteria) this;
        }

        public Criteria andPermsNotBetween(String value1, String value2) {
            addCriterion("perms not between", value1, value2, "perms");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by  Generator.
     * This class corresponds to the database table  cscp_operate_perm
     *
     * @date do_not_delete_during_merge 2022-07-22 09:25:13
     */
    public static class Criteria extends BaseGeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by  Generator.
     * This class corresponds to the database table  cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    public static class Criterion {
        @ApiParam(hidden = true)
        private String condition;

        @ApiParam(hidden = true)
        private Object value;

        @ApiParam(hidden = true)
        private Object secondValue;

        @ApiParam(hidden = true)
        private boolean noValue;

        @ApiParam(hidden = true)
        private boolean singleValue;

        @ApiParam(hidden = true)
        private boolean betweenValue;

        @ApiParam(hidden = true)
        private boolean listValue;

        @ApiParam(hidden = true)
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

    }
}
