package com.ctsi.flow.param.model;

import com.ctsi.ssdc.criteria.*;

import java.time.ZonedDateTime;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.ctsi.ssdc.example.BaseExample;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.annotations.ApiParam;
import java.util.ArrayList;
import java.util.List;
import org.apache.commons.lang3.StringUtils;

/**
 * CscpFlowTaskAssignRuleExample
 *
 * @author hx
 * @date 2022-08-05 10:19:18
 */

public class CscpFlowTaskAssignRuleExample extends BaseExample {

    /**
     * This field was generated by  Generator.
     * This field corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    protected String orderByClause;

    /**
     * This field was generated by  Generator.
     * This field corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    protected boolean distinct;

    /**
     * This field was generated by  Generator.
     * This field corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by  Generator.
     * This field corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    private static final String LIKE_FORMAT = "%%%s%%";


        /**
         *
         * This field was generated by  Generator.
         * This field corresponds to the database column cscp_flow_task_assign_rule.task_definition_key
         *
         * @date 2022-08-05 10:19:18
         */
    private StringCriteria taskDefinitionKey;

        /**
         *
         * This field was generated by  Generator.
         * This field corresponds to the database column cscp_flow_task_assign_rule.process_definition_id
         *
         * @date 2022-08-05 10:19:18
         */
    private StringCriteria processDefinitionId;

        /**
         *
         * This field was generated by  Generator.
         * This field corresponds to the database column cscp_flow_task_assign_rule.options
         *
         * @date 2022-08-05 10:19:18
         */
    private StringCriteria options;

        /**
         *
         * This field was generated by  Generator.
         * This field corresponds to the database column cscp_flow_task_assign_rule.creator
         *
         * @date 2022-08-05 10:19:18
         */
    private StringCriteria creator;

        /**
         *
         * This field was generated by  Generator.
         * This field corresponds to the database column cscp_flow_task_assign_rule.updater
         *
         * @date 2022-08-05 10:19:18
         */
    private StringCriteria updater;

        /**
         *
         * This field was generated by  Generator.
         * This field corresponds to the database column cscp_flow_task_assign_rule.type
         *
         * @date 2022-08-05 10:19:18
         */
    private IntegerCriteria type;

        /**
         *
         * This field was generated by  Generator.
         * This field corresponds to the database column cscp_flow_task_assign_rule.model_id
         *
         * @date 2022-08-05 10:19:18
         */
    private StringCriteria modelId;

        /**
         *
         * This field was generated by  Generator.
         * This field corresponds to the database column cscp_flow_task_assign_rule.id
         *
         * @date 2022-08-05 10:19:18
         */
    private LongCriteria id;

        /**
         *
         * This field was generated by  Generator.
         * This field corresponds to the database column cscp_flow_task_assign_rule.tenant_id
         *
         * @date 2022-08-05 10:19:18
         */
    private LongCriteria tenantId;

        /**
         *
         * This field was generated by  Generator.
         * This field corresponds to the database column cscp_flow_task_assign_rule.update_time
         *
         * @date 2022-08-05 10:19:18
         */
    private ZonedDateTimeCriteria updateTime;

        /**
         *
         * This field was generated by  Generator.
         * This field corresponds to the database column cscp_flow_task_assign_rule.create_time
         *
         * @date 2022-08-05 10:19:18
         */
    private ZonedDateTimeCriteria createTime;


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public CscpFlowTaskAssignRuleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    @Override
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public StringCriteria getTaskDefinitionKey() {
        return taskDefinitionKey;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public void setTaskDefinitionKey(StringCriteria taskDefinitionKey) {
        this. taskDefinitionKey = taskDefinitionKey;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    private void buildTaskDefinitionKeyCriteria(Criteria criteria) {
        if (this.getTaskDefinitionKey() == null) {
            return;
        }
        if (this.getTaskDefinitionKey().getEquals() != null) {
            criteria.andTaskDefinitionKeyEqualTo(this.getTaskDefinitionKey().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getTaskDefinitionKey().getContains())) {
                criteria.andTaskDefinitionKeyLike(String.format(LIKE_FORMAT, this.getTaskDefinitionKey().getContains()));
            }
        }
    }
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public StringCriteria getProcessDefinitionId() {
        return processDefinitionId;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public void setProcessDefinitionId(StringCriteria processDefinitionId) {
        this. processDefinitionId = processDefinitionId;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    private void buildProcessDefinitionIdCriteria(Criteria criteria) {
        if (this.getProcessDefinitionId() == null) {
            return;
        }
        if (this.getProcessDefinitionId().getEquals() != null) {
            criteria.andProcessDefinitionIdEqualTo(this.getProcessDefinitionId().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getProcessDefinitionId().getContains())) {
                criteria.andProcessDefinitionIdLike(String.format(LIKE_FORMAT, this.getProcessDefinitionId().getContains()));
            }
        }
    }
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public StringCriteria getOptions() {
        return options;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public void setOptions(StringCriteria options) {
        this. options = options;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    private void buildOptionsCriteria(Criteria criteria) {
        if (this.getOptions() == null) {
            return;
        }
        if (this.getOptions().getEquals() != null) {
            criteria.andOptionsEqualTo(this.getOptions().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getOptions().getContains())) {
                criteria.andOptionsLike(String.format(LIKE_FORMAT, this.getOptions().getContains()));
            }
        }
    }
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public StringCriteria getCreator() {
        return creator;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public void setCreator(StringCriteria creator) {
        this. creator = creator;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    private void buildCreatorCriteria(Criteria criteria) {
        if (this.getCreator() == null) {
            return;
        }
        if (this.getCreator().getEquals() != null) {
            criteria.andCreatorEqualTo(this.getCreator().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getCreator().getContains())) {
                criteria.andCreatorLike(String.format(LIKE_FORMAT, this.getCreator().getContains()));
            }
        }
    }
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public StringCriteria getUpdater() {
        return updater;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public void setUpdater(StringCriteria updater) {
        this. updater = updater;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    private void buildUpdaterCriteria(Criteria criteria) {
        if (this.getUpdater() == null) {
            return;
        }
        if (this.getUpdater().getEquals() != null) {
            criteria.andUpdaterEqualTo(this.getUpdater().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getUpdater().getContains())) {
                criteria.andUpdaterLike(String.format(LIKE_FORMAT, this.getUpdater().getContains()));
            }
        }
    }
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public IntegerCriteria getType() {
        return type;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public void setType(IntegerCriteria type) {
        this. type = type;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    private void buildTypeCriteria(Criteria criteria) {
        if (this.getType() == null) {
            return;
        }
        if (this.getType().getEquals() != null) {
            criteria.andTypeEqualTo(this.getType().getEquals());
        } else {
            if (this.getType().getGreaterOrEqualThan() != null) {
                criteria.andTypeGreaterThanOrEqualTo(this.getType().getGreaterOrEqualThan());
            }
            if (this.getType().getLessOrEqualThan() != null) {
                criteria.andTypeLessThanOrEqualTo(this.getType().getLessOrEqualThan());
            }
        }
    }
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public StringCriteria getModelId() {
        return modelId;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public void setModelId(StringCriteria modelId) {
        this. modelId = modelId;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    private void buildModelIdCriteria(Criteria criteria) {
        if (this.getModelId() == null) {
            return;
        }
        if (this.getModelId().getEquals() != null) {
            criteria.andModelIdEqualTo(this.getModelId().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getModelId().getContains())) {
                criteria.andModelIdLike(String.format(LIKE_FORMAT, this.getModelId().getContains()));
            }
        }
    }
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public LongCriteria getId() {
        return id;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public void setId(LongCriteria id) {
        this. id = id;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    private void buildIdCriteria(Criteria criteria) {
        if (this.getId() == null) {
            return;
        }
        if (this.getId().getEquals() != null) {
            criteria.andIdEqualTo(this.getId().getEquals());
        } else {
            if (this.getId().getGreaterOrEqualThan() != null) {
                criteria.andIdGreaterThanOrEqualTo(this.getId().getGreaterOrEqualThan());
            }
            if (this.getId().getLessOrEqualThan() != null) {
                criteria.andIdLessThanOrEqualTo(this.getId().getLessOrEqualThan());
            }
        }
    }
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public LongCriteria getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public void setTenantId(LongCriteria tenantId) {
        this. tenantId = tenantId;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    private void buildTenantIdCriteria(Criteria criteria) {
        if (this.getTenantId() == null) {
            return;
        }
        if (this.getTenantId().getEquals() != null) {
            criteria.andTenantIdEqualTo(this.getTenantId().getEquals());
        } else {
            if (this.getTenantId().getGreaterOrEqualThan() != null) {
                criteria.andTenantIdGreaterThanOrEqualTo(this.getTenantId().getGreaterOrEqualThan());
            }
            if (this.getTenantId().getLessOrEqualThan() != null) {
                criteria.andTenantIdLessThanOrEqualTo(this.getTenantId().getLessOrEqualThan());
            }
        }
    }
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public ZonedDateTimeCriteria getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public void setUpdateTime(ZonedDateTimeCriteria updateTime) {
        this. updateTime = updateTime;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    private void buildUpdateTimeCriteria(Criteria criteria) {
        if (this.getUpdateTime() == null) {
            return;
        }
        if (this.getUpdateTime().getEquals() != null) {
            criteria.andUpdateTimeEqualTo(this.getUpdateTime().getEquals());
        } else {
            if (this.getUpdateTime().getGreaterOrEqualThan() != null) {
                criteria.andUpdateTimeGreaterThanOrEqualTo(this.getUpdateTime().getGreaterOrEqualThan());
            }
            if (this.getUpdateTime().getLessOrEqualThan() != null) {
                criteria.andUpdateTimeLessThanOrEqualTo(this.getUpdateTime().getLessOrEqualThan());
            }
        }
    }
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public ZonedDateTimeCriteria getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public void setCreateTime(ZonedDateTimeCriteria createTime) {
        this. createTime = createTime;
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    private void buildCreateTimeCriteria(Criteria criteria) {
        if (this.getCreateTime() == null) {
            return;
        }
        if (this.getCreateTime().getEquals() != null) {
            criteria.andCreateTimeEqualTo(this.getCreateTime().getEquals());
        } else {
            if (this.getCreateTime().getGreaterOrEqualThan() != null) {
                criteria.andCreateTimeGreaterThanOrEqualTo(this.getCreateTime().getGreaterOrEqualThan());
            }
            if (this.getCreateTime().getLessOrEqualThan() != null) {
                criteria.andCreateTimeLessThanOrEqualTo(this.getCreateTime().getLessOrEqualThan());
            }
        }
    }
    /**
      * This method was generated by  Generator.
      * This method corresponds to the database table cscp_hx_form_column
      *
      * @date Thu Feb 17 14:02:06 CST 2022
      */
    @Override
    public Object buildCriteria() {
        Criteria criteria = this.createCriteria();
        this.buildTaskDefinitionKeyCriteria(criteria);
        this.buildProcessDefinitionIdCriteria(criteria);
        this.buildOptionsCriteria(criteria);
        this.buildCreatorCriteria(criteria);
        this.buildUpdaterCriteria(criteria);
        this.buildTypeCriteria(criteria);
        this.buildModelIdCriteria(criteria);
        this.buildIdCriteria(criteria);
        this.buildTenantIdCriteria(criteria);
        this.buildUpdateTimeCriteria(criteria);
        this.buildCreateTimeCriteria(criteria);
        return criteria;
    }

    protected abstract static class BaseGeneratedCriteria {
        protected List<Criterion> criteria;

        protected BaseGeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }


        public Criteria andTaskDefinitionKeyIsNull() {
            addCriterion("task_definition_key is null");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyIsNotNull() {
            addCriterion("task_definition_key is not null");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyEqualTo(String value) {
            addCriterion("task_definition_key =", value, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyNotEqualTo(String value) {
            addCriterion("task_definition_key <>", value, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyGreaterThan(String value) {
            addCriterion("task_definition_key >", value, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyGreaterThanOrEqualTo(String value) {
            addCriterion("task_definition_key >=", value, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyLessThan(String value) {
            addCriterion("task_definition_key <", value, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyLessThanOrEqualTo(String value) {
            addCriterion("task_definition_key <=", value, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyLike(String value) {
            addCriterion("task_definition_key like", value, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyNotLike(String value) {
            addCriterion("task_definition_key not like", value, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyIn(List<String> values) {
            addCriterion("task_definition_key in", values, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyNotIn(List<String> values) {
            addCriterion("task_definition_key not in", values, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyBetween(String value1, String value2) {
            addCriterion("task_definition_key between", value1, value2, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andTaskDefinitionKeyNotBetween(String value1, String value2) {
            addCriterion("task_definition_key not between", value1, value2, "taskDefinitionKey");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdIsNull() {
            addCriterion("process_definition_id is null");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdIsNotNull() {
            addCriterion("process_definition_id is not null");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdEqualTo(String value) {
            addCriterion("process_definition_id =", value, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdNotEqualTo(String value) {
            addCriterion("process_definition_id <>", value, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdGreaterThan(String value) {
            addCriterion("process_definition_id >", value, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdGreaterThanOrEqualTo(String value) {
            addCriterion("process_definition_id >=", value, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdLessThan(String value) {
            addCriterion("process_definition_id <", value, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdLessThanOrEqualTo(String value) {
            addCriterion("process_definition_id <=", value, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdLike(String value) {
            addCriterion("process_definition_id like", value, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdNotLike(String value) {
            addCriterion("process_definition_id not like", value, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdIn(List<String> values) {
            addCriterion("process_definition_id in", values, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdNotIn(List<String> values) {
            addCriterion("process_definition_id not in", values, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdBetween(String value1, String value2) {
            addCriterion("process_definition_id between", value1, value2, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andProcessDefinitionIdNotBetween(String value1, String value2) {
            addCriterion("process_definition_id not between", value1, value2, "processDefinitionId");
            return (Criteria) this;
        }

        public Criteria andOptionsIsNull() {
            addCriterion("options is null");
            return (Criteria) this;
        }

        public Criteria andOptionsIsNotNull() {
            addCriterion("options is not null");
            return (Criteria) this;
        }

        public Criteria andOptionsEqualTo(String value) {
            addCriterion("options =", value, "options");
            return (Criteria) this;
        }

        public Criteria andOptionsNotEqualTo(String value) {
            addCriterion("options <>", value, "options");
            return (Criteria) this;
        }

        public Criteria andOptionsGreaterThan(String value) {
            addCriterion("options >", value, "options");
            return (Criteria) this;
        }

        public Criteria andOptionsGreaterThanOrEqualTo(String value) {
            addCriterion("options >=", value, "options");
            return (Criteria) this;
        }

        public Criteria andOptionsLessThan(String value) {
            addCriterion("options <", value, "options");
            return (Criteria) this;
        }

        public Criteria andOptionsLessThanOrEqualTo(String value) {
            addCriterion("options <=", value, "options");
            return (Criteria) this;
        }

        public Criteria andOptionsLike(String value) {
            addCriterion("options like", value, "options");
            return (Criteria) this;
        }

        public Criteria andOptionsNotLike(String value) {
            addCriterion("options not like", value, "options");
            return (Criteria) this;
        }

        public Criteria andOptionsIn(List<String> values) {
            addCriterion("options in", values, "options");
            return (Criteria) this;
        }

        public Criteria andOptionsNotIn(List<String> values) {
            addCriterion("options not in", values, "options");
            return (Criteria) this;
        }

        public Criteria andOptionsBetween(String value1, String value2) {
            addCriterion("options between", value1, value2, "options");
            return (Criteria) this;
        }

        public Criteria andOptionsNotBetween(String value1, String value2) {
            addCriterion("options not between", value1, value2, "options");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("updater is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("updater is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("updater =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("updater <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("updater >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("updater >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("updater <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("updater <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("updater like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("updater not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("updater in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("updater not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("updater between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("updater not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andModelIdIsNull() {
            addCriterion("model_id is null");
            return (Criteria) this;
        }

        public Criteria andModelIdIsNotNull() {
            addCriterion("model_id is not null");
            return (Criteria) this;
        }

        public Criteria andModelIdEqualTo(String value) {
            addCriterion("model_id =", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotEqualTo(String value) {
            addCriterion("model_id <>", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdGreaterThan(String value) {
            addCriterion("model_id >", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdGreaterThanOrEqualTo(String value) {
            addCriterion("model_id >=", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdLessThan(String value) {
            addCriterion("model_id <", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdLessThanOrEqualTo(String value) {
            addCriterion("model_id <=", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdLike(String value) {
            addCriterion("model_id like", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotLike(String value) {
            addCriterion("model_id not like", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdIn(List<String> values) {
            addCriterion("model_id in", values, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotIn(List<String> values) {
            addCriterion("model_id not in", values, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdBetween(String value1, String value2) {
            addCriterion("model_id between", value1, value2, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotBetween(String value1, String value2) {
            addCriterion("model_id not between", value1, value2, "modelId");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNull() {
            addCriterion("tenant_id is null");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNotNull() {
            addCriterion("tenant_id is not null");
            return (Criteria) this;
        }

        public Criteria andTenantIdEqualTo(Long value) {
            addCriterion("tenant_id =", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotEqualTo(Long value) {
            addCriterion("tenant_id <>", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThan(Long value) {
            addCriterion("tenant_id >", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThanOrEqualTo(Long value) {
            addCriterion("tenant_id >=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThan(Long value) {
            addCriterion("tenant_id <", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThanOrEqualTo(Long value) {
            addCriterion("tenant_id <=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdIn(List<Long> values) {
            addCriterion("tenant_id in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotIn(List<Long> values) {
            addCriterion("tenant_id not in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdBetween(Long value1, Long value2) {
            addCriterion("tenant_id between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotBetween(Long value1, Long value2) {
            addCriterion("tenant_id not between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(ZonedDateTime value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(ZonedDateTime value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(ZonedDateTime value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(ZonedDateTime value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(ZonedDateTime value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(ZonedDateTime value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<ZonedDateTime> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<ZonedDateTime> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(ZonedDateTime value1, ZonedDateTime value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(ZonedDateTime value1, ZonedDateTime value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(ZonedDateTime value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(ZonedDateTime value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(ZonedDateTime value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(ZonedDateTime value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(ZonedDateTime value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(ZonedDateTime value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<ZonedDateTime> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<ZonedDateTime> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(ZonedDateTime value1, ZonedDateTime value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(ZonedDateTime value1, ZonedDateTime value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by  Generator.
     * This class corresponds to the database table  cscp_flow_task_assign_rule
     *
     * @date do_not_delete_during_merge 2022-08-05 10:19:18
     */
    public static class Criteria extends BaseGeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by  Generator.
     * This class corresponds to the database table  cscp_flow_task_assign_rule
     *
     * @date 2022-08-05 10:19:18
     */
    public static class Criterion {
        @ApiParam(hidden = true)
        private String condition;

        @ApiParam(hidden = true)
        private Object value;

        @ApiParam(hidden = true)
        private Object secondValue;

        @ApiParam(hidden = true)
        private boolean noValue;

        @ApiParam(hidden = true)
        private boolean singleValue;

        @ApiParam(hidden = true)
        private boolean betweenValue;

        @ApiParam(hidden = true)
        private boolean listValue;

        @ApiParam(hidden = true)
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

    }
}
