package com.ctsi.flow.approve.repository;

import com.ctsi.flow.approve.domain.Approve;
import com.ctsi.flow.approve.domain.ApproveExample.Criteria;
import com.ctsi.flow.approve.domain.ApproveExample.Criterion;
import com.ctsi.flow.approve.domain.ApproveExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;


/**
 * ApproveSqlProvider
 *
 * @author hx
 * @date 2022-11-03 19:50:16
*/

public class ApproveSqlProvider {

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table approve
     */
    public String countByExample(ApproveExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("approve");
        applyWhere(sql, example, false);
        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table approve
     */
    public String deleteByExample(ApproveExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("approve");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table approve
     */
    public String insertSelective(Approve record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("approve");

        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        if (record.getDay() != null) {
            sql.VALUES("day", "#{day,jdbcType=INTEGER}");
        }
        if (record.getReason() != null) {
            sql.VALUES("reason", "#{reason,jdbcType=VARCHAR}");
        }
        if (record.getFromArea() != null) {
            sql.VALUES("from_area", "#{fromArea,jdbcType=VARCHAR}");
        }
        if (record.getToArea() != null) {
            sql.VALUES("to_area", "#{toArea,jdbcType=VARCHAR}");
        }
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=INTEGER}");
        }
        if (record.getInstanceId() != null) {
            sql.VALUES("instance_id", "#{instanceId,jdbcType=VARCHAR}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table approve
     */
    public String selectByExample(ApproveExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("day");
        sql.SELECT("reason");
        sql.SELECT("from_area");
        sql.SELECT("to_area");
        sql.SELECT("user_id");
        sql.SELECT("instance_id");
        sql.FROM("approve");
        applyWhere(sql, example, false);

        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table approve
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Approve record = (Approve) parameter.get("record");
        ApproveExample example = (ApproveExample) parameter.get("example");

        SQL sql = new SQL();
        sql.UPDATE("approve");

        if (record.getId() != null) {
        sql.SET("id = #{id,jdbcType=BIGINT}");
        }
        if (record.getDay() != null) {
        sql.SET("day = #{day,jdbcType=INTEGER}");
        }
        if (record.getReason() != null) {
        sql.SET("reason = #{reason,jdbcType=VARCHAR}");
        }
        if (record.getFromArea() != null) {
        sql.SET("from_area = #{fromArea,jdbcType=VARCHAR}");
        }
        if (record.getToArea() != null) {
        sql.SET("to_area = #{toArea,jdbcType=VARCHAR}");
        }
        if (record.getUserId() != null) {
        sql.SET("user_id = #{userId,jdbcType=INTEGER}");
        }
        if (record.getInstanceId() != null) {
        sql.SET("instance_id = #{instanceId,jdbcType=VARCHAR}");
        }
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table approve
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("approve");
        sql.SET("id = #{id,jdbcType=BIGINT}");
        sql.SET("day = #{day,jdbcType=INTEGER}");
        sql.SET("reason = #{reason,jdbcType=VARCHAR}");
        sql.SET("from_area = #{fromArea,jdbcType=VARCHAR}");
        sql.SET("to_area = #{toArea,jdbcType=VARCHAR}");
        sql.SET("user_id = #{userId,jdbcType=INTEGER}");
        sql.SET("instance_id = #{instanceId,jdbcType=VARCHAR}");

        ApproveExample example = (ApproveExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table approve
     */
    public String updateByPrimaryKeySelective(Approve record) {
        SQL sql = new SQL();
        sql.UPDATE("approve");

        if (record.getDay() != null) {
            sql.SET("day = #{day,jdbcType=INTEGER}");
        }
        if (record.getReason() != null) {
            sql.SET("reason = #{reason,jdbcType=VARCHAR}");
        }
        if (record.getFromArea() != null) {
            sql.SET("from_area = #{fromArea,jdbcType=VARCHAR}");
        }
        if (record.getToArea() != null) {
            sql.SET("to_area = #{toArea,jdbcType=VARCHAR}");
        }
        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=INTEGER}");
        }
        if (record.getInstanceId() != null) {
            sql.SET("instance_id = #{instanceId,jdbcType=VARCHAR}");
        }
        sql.WHERE("id = #{id,jdbcType=BIGINT}");

        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table approve
     */
    protected void applyWhere(SQL sql, ApproveExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1Th;
        String parmPhrase2;
        String parmPhrase2Th;
        String parmPhrase3;
        String parmPhrase3Th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1Th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2Th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3Th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}
