package com.ctsi.flow.approve.repository;

import com.ctsi.flow.approve.domain.Approve;
import com.ctsi.flow.approve.domain.ApproveExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

/**
 * ApproveRepository
 *
 * @author hx
 * @date 2022-11-03 19:50:16
 */

@Mapper
public interface ApproveRepository extends com.ctsi.ssdc.repository.BaseRepository<Approve, Long, ApproveExample> {
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table approve
     *
     * @date 2022-11-03 19:50:16
     */
    @SelectProvider(type=ApproveSqlProvider.class, method="countByExample")
    @Override
    long countByExample(ApproveExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table approve
     *
     * @date 2022-11-03 19:50:16
     */
    @DeleteProvider(type=ApproveSqlProvider.class, method="deleteByExample")
    @Override
    int deleteByExample(ApproveExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table approve
     *
     * @date 2022-11-03 19:50:16
     */
    @Delete({
            "delete from approve",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table approve
     *
     *
     * @date 2022-11-03 19:50:16
     */
    @Insert({
            "insert into approve (",
            "id,",
            "day,",
            "reason,",
            "from_area,",
            "to_area,",
            "user_id,",
            "instance_id",
            ") values (",
            "#{id,jdbcType=BIGINT}, ",
            "#{day,jdbcType=INTEGER}, ",
            "#{reason,jdbcType=VARCHAR}, ",
            "#{fromArea,jdbcType=VARCHAR}, ",
            "#{toArea,jdbcType=VARCHAR}, ",
            "#{userId,jdbcType=INTEGER}, ",
            "#{instanceId,jdbcType=VARCHAR}",

            ")"

    })
    @Override
    int insert(Approve record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table approve
     *
     * @date 2022-11-03 19:50:16
     */
    @InsertProvider(type=ApproveSqlProvider.class, method="insertSelective")
    @Override
    int insertSelective(Approve record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table approve
     *
     * @date 2022-11-03 19:50:16
     */
    @SelectProvider(type=ApproveSqlProvider.class, method="selectByExample")
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="day", property="day", jdbcType=JdbcType.INTEGER),
            @Result(column="reason", property="reason", jdbcType=JdbcType.VARCHAR),
            @Result(column="from_area", property="fromArea", jdbcType=JdbcType.VARCHAR),
            @Result(column="to_area", property="toArea", jdbcType=JdbcType.VARCHAR),
            @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
            @Result(column="instance_id", property="instanceId", jdbcType=JdbcType.VARCHAR)
    })

    @Override
    List<Approve> selectByExample(ApproveExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table approve
     *
     * @date 2022-11-03 19:50:16
     */
    @Select({
            "select",
            "id,",
            "day,",
            "reason,",
            "from_area,",
            "to_area,",
            "user_id,",
            "instance_id",
            "from approve",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="day", property="day", jdbcType=JdbcType.INTEGER),
            @Result(column="reason", property="reason", jdbcType=JdbcType.VARCHAR),
            @Result(column="from_area", property="fromArea", jdbcType=JdbcType.VARCHAR),
            @Result(column="to_area", property="toArea", jdbcType=JdbcType.VARCHAR),
            @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
            @Result(column="instance_id", property="instanceId", jdbcType=JdbcType.VARCHAR)
    })
    @Override
    Approve selectByPrimaryKey(Long id);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table approve
     *
     * @date 2022-11-03 19:50:16
     */
    @UpdateProvider(type=ApproveSqlProvider.class, method="updateByExampleSelective")
    @Override
    int updateByExampleSelective(@Param("record") Approve record, @Param("example") ApproveExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table approve
     *
     * @date 2022-11-03 19:50:16
     */
    @UpdateProvider(type=ApproveSqlProvider.class, method="updateByExample")
    @Override
    int updateByExample(@Param("record") Approve record, @Param("example") ApproveExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table approve
     *
     *@date 2022-11-03 19:50:16
     */
    @UpdateProvider(type=ApproveSqlProvider.class, method="updateByPrimaryKeySelective")
    @Override
    int updateByPrimaryKeySelective(Approve record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table approve
     *
     * @date 2022-11-03 19:50:16
     */
    @Update({
            "update approve",
            "set ",
            "id = #{id,jdbcType=BIGINT},",
            "day = #{day,jdbcType=INTEGER},",
            "reason = #{reason,jdbcType=VARCHAR},",
            "from_area = #{fromArea,jdbcType=VARCHAR},",
            "to_area = #{toArea,jdbcType=VARCHAR},",
            "user_id = #{userId,jdbcType=INTEGER},",
            "instance_id = #{instanceId,jdbcType=VARCHAR}",

            "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int updateByPrimaryKey(Approve record);

    /**
     * 批量删除
     * @param ids
     */
    @Delete("<script>" +
            "delete from approve where id in" +
            "<foreach collection=\"ids\" item=\"id\" open=\"(\" separator=\",\" close=\")\">" +
            "#{id}" +
            "</foreach>" +
            "</script>")
    void deleteByIds(@Param("ids") List<Long> ids);


}





