package com.ctsi.flow.repository;

import com.ctsi.flow.param.model.ActOperatePerm;
import com.ctsi.flow.param.model.ActOperatePermExample;
import com.ctsi.flow.param.model.ActOperatePermExample.Criteria;
import com.ctsi.flow.param.model.ActOperatePermExample.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;


/**
 * ActOperatePermSqlProvider
 *
 * @author hx
 * @date 2022-07-22 09:25:13
 */

public class ActOperatePermSqlProvider {

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     */
    public String countByExample(ActOperatePermExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("cscp_operate_perm");
        applyWhere(sql, example, false);
        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     */
    public String deleteByExample(ActOperatePermExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("cscp_operate_perm");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     */
    public String insertSelective(ActOperatePerm record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("cscp_operate_perm");

        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        if (record.getTaskDefinitionKey() != null) {
            sql.VALUES("task_definition_Key", "#{taskDefinitionKey,jdbcType=VARCHAR}");
        }
        if (record.getTaskDefinitionName() != null) {
            sql.VALUES("task_definition_name", "#{taskDefinitionName,jdbcType=VARCHAR}");
        }
        if (record.getPerms() != null) {
            sql.VALUES("perms", "#{perms,jdbcType=VARCHAR}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     */
    public String selectByExample(ActOperatePermExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("task_definition_Key");
        sql.SELECT("task_definition_name");
        sql.SELECT("perms");
        sql.FROM("cscp_operate_perm");
        applyWhere(sql, example, false);

        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ActOperatePerm record = (ActOperatePerm) parameter.get("record");
        ActOperatePermExample example = (ActOperatePermExample) parameter.get("example");

        SQL sql = new SQL();
        sql.UPDATE("cscp_operate_perm");

        if (record.getId() != null) {
            sql.SET("id = #{id,jdbcType=BIGINT}");
        }
        if (record.getTaskDefinitionKey() != null) {
            sql.SET("task_definition_Key = #{taskDefinitionKey,jdbcType=VARCHAR}");
        }
        if (record.getTaskDefinitionName() != null) {
            sql.SET("task_definition_name = #{taskDefinitionName,jdbcType=VARCHAR}");
        }
        if (record.getPerms() != null) {
            sql.SET("perms = #{perms,jdbcType=VARCHAR}");
        }
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_operate_perm");
        sql.SET("id = #{id,jdbcType=BIGINT}");
        sql.SET("task_definition_Key = #{taskDefinitionKey,jdbcType=VARCHAR}");
        sql.SET("task_definition_name = #{taskDefinitionName,jdbcType=VARCHAR}");
        sql.SET("perms = #{perms,jdbcType=VARCHAR}");

        ActOperatePermExample example = (ActOperatePermExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     */
    public String updateByPrimaryKeySelective(ActOperatePerm record) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_operate_perm");

        if (record.getTaskDefinitionKey() != null) {
            sql.SET("task_definition_Key = #{taskDefinitionKey,jdbcType=VARCHAR}");
        }
        if (record.getTaskDefinitionName() != null) {
            sql.SET("task_definition_name = #{taskDefinitionName,jdbcType=VARCHAR}");
        }
        if (record.getPerms() != null) {
            sql.SET("perms = #{perms,jdbcType=VARCHAR}");
        }
        sql.WHERE("id = #{id,jdbcType=BIGINT}");

        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     */
    protected void applyWhere(SQL sql, ActOperatePermExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1Th;
        String parmPhrase2;
        String parmPhrase2Th;
        String parmPhrase3;
        String parmPhrase3Th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1Th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2Th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3Th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}
