package com.ctsi.flow.repository;

import com.ctsi.flow.param.model.ActOperatePerm;
import com.ctsi.flow.param.model.ActOperatePermExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

/**
 * ActOperatePermRepository
 *
 * @author hx
 * @date 2022-07-22 09:25:13
 */

@Mapper
public interface ActOperatePermRepository extends com.ctsi.ssdc.repository.BaseRepository<ActOperatePerm, Long, ActOperatePermExample> {
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    @SelectProvider(type=ActOperatePermSqlProvider.class, method="countByExample")
    @Override
    long countByExample(ActOperatePermExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    @DeleteProvider(type=ActOperatePermSqlProvider.class, method="deleteByExample")
    @Override
    int deleteByExample(ActOperatePermExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    @Delete({
            "delete from cscp_operate_perm",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     *
     * @date 2022-07-22 09:25:13
     */
    @Insert({
            "insert into cscp_operate_perm (",
            "id,",
            "task_definition_Key,",
            "task_definition_name,",
            "perms,",
            "task_definition_flag",
            ") values (",
            "#{id,jdbcType=BIGINT}, ",
            "#{taskDefinitionKey,jdbcType=VARCHAR}, ",
            "#{taskDefinitionName,jdbcType=VARCHAR}, ",
            "#{perms,jdbcType=VARCHAR},",
            "#{taskDefinitionFlag,jdbcType=VARCHAR}",

            ")"

    })
    @Override
    int insert(ActOperatePerm record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    @InsertProvider(type=ActOperatePermSqlProvider.class, method="insertSelective")
    @Override
    int insertSelective(ActOperatePerm record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    @SelectProvider(type=ActOperatePermSqlProvider.class, method="selectByExample")
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="task_definition_Key", property="taskDefinitionKey", jdbcType=JdbcType.VARCHAR),
            @Result(column="task_definition_name", property="taskDefinitionName", jdbcType=JdbcType.VARCHAR),
            @Result(column="perms", property="perms", jdbcType=JdbcType.VARCHAR)
    })

    @Override
    List<ActOperatePerm> selectByExample(ActOperatePermExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    @Select({
            "select",
            "id,",
            "task_definition_Key,",
            "task_definition_name,",
            "perms",
            "from cscp_operate_perm",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="task_definition_Key", property="taskDefinitionKey", jdbcType=JdbcType.VARCHAR),
            @Result(column="task_definition_name", property="taskDefinitionName", jdbcType=JdbcType.VARCHAR),
            @Result(column="perms", property="perms", jdbcType=JdbcType.VARCHAR)
    })
    @Override
    ActOperatePerm selectByPrimaryKey(Long id);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    @UpdateProvider(type=ActOperatePermSqlProvider.class, method="updateByExampleSelective")
    @Override
    int updateByExampleSelective(@Param("record") ActOperatePerm record, @Param("example") ActOperatePermExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    @UpdateProvider(type=ActOperatePermSqlProvider.class, method="updateByExample")
    @Override
    int updateByExample(@Param("record") ActOperatePerm record, @Param("example") ActOperatePermExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     *@date 2022-07-22 09:25:13
     */
    @UpdateProvider(type=ActOperatePermSqlProvider.class, method="updateByPrimaryKeySelective")
    @Override
    int updateByPrimaryKeySelective(ActOperatePerm record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_operate_perm
     *
     * @date 2022-07-22 09:25:13
     */
    @Update({
            "update cscp_operate_perm",
            "set ",
            "id = #{id,jdbcType=BIGINT},",
            "task_definition_Key = #{taskDefinitionKey,jdbcType=VARCHAR},",
            "task_definition_name = #{taskDefinitionName,jdbcType=VARCHAR},",
            "perms = #{perms,jdbcType=VARCHAR}",

            "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int updateByPrimaryKey(ActOperatePerm record);

    /**
     * 批量删除
     * @param ids
     */
    @Delete("<script>" +
            "delete from cscp_operate_perm where id in" +
            "<foreach collection=\"ids\" item=\"id\" open=\"(\" separator=\",\" close=\")\">" +
            "#{id}" +
            "</foreach>" +
            "</script>")
    void deleteByIds(@Param("ids") List<Long> ids);


}





