package com.ctsi.flow.repository;

import com.ctsi.flow.param.model.ActRdTurnTask;
import com.ctsi.flow.param.model.ActRdTurnTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.springframework.web.bind.annotation.RequestParam;

/**
 * ActRdTurnTaskRepository
 *
 * @author hx
 * @date 2022-07-28 18:44:24
 */

@Mapper
public interface ActRdTurnTaskRepository extends com.ctsi.ssdc.repository.BaseRepository<ActRdTurnTask, Long, ActRdTurnTaskExample> {
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_rd_turn_task
     *
     * @date 2022-07-28 18:44:24
     */
    @SelectProvider(type=ActRdTurnTaskSqlProvider.class, method="countByExample")
    @Override
    long countByExample(ActRdTurnTaskExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_rd_turn_task
     *
     * @date 2022-07-28 18:44:24
     */
    @DeleteProvider(type=ActRdTurnTaskSqlProvider.class, method="deleteByExample")
    @Override
    int deleteByExample(ActRdTurnTaskExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_rd_turn_task
     *
     * @date 2022-07-28 18:44:24
     */
    @Delete({
            "delete from cscp_rd_turn_task",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_rd_turn_task
     *
     *
     * @date 2022-07-28 18:44:24
     */
    @Insert({
            "insert into cscp_rd_turn_task (",
            "id,",
            "user_id,",
            "form_id,",
            "process_id,",
            "process_instid,",
            "process_name,",
            "type,",
            "create_time,",
            "cur_assignee,",
            "last_assignee",
            ") values (",
            "#{id,jdbcType=BIGINT}, ",
            "#{userId,jdbcType=BIGINT}, ",
            "#{formId,jdbcType=VARCHAR}, ",
            "#{processId,jdbcType=VARCHAR}, ",
            "#{processInstid,jdbcType=VARCHAR}, ",
            "#{processName,jdbcType=VARCHAR}, ",
            "#{type,jdbcType=VARCHAR}, ",
            "#{createTime,jdbcType=DATE},",
            "#{curAssignee,jdbcType=BIGINT},",
            "#{lastAssignee,jdbcType=BIGINT}",

            ")"

    })
    @Override
    int insert(ActRdTurnTask record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_rd_turn_task
     *
     * @date 2022-07-28 18:44:24
     */
    @InsertProvider(type=ActRdTurnTaskSqlProvider.class, method="insertSelective")
    @Override
    int insertSelective(ActRdTurnTask record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_rd_turn_task
     *
     * @date 2022-07-28 18:44:24
     */
    @SelectProvider(type=ActRdTurnTaskSqlProvider.class, method="selectByExample")
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
            @Result(column="form_id", property="formId", jdbcType=JdbcType.VARCHAR),
            @Result(column="process_id", property="processId", jdbcType=JdbcType.VARCHAR),
            @Result(column="process_instid", property="processInstid", jdbcType=JdbcType.VARCHAR),
            @Result(column="process_name", property="processName", jdbcType=JdbcType.VARCHAR),
            @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
            @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE)
    })

    @Override
    List<ActRdTurnTask> selectByExample(ActRdTurnTaskExample example);

    @Select({
            "select",
            "p1.id,",
            "p1.user_id,",
            "p1.form_id,",
            "p1.process_id,",
            "p1.process_instid,",
            "p1.process_name,",
            "p1.type,",
            "p1.create_time,",
            "p2.username curAssigneeName,",
            "p3.username lastAssigneeName",
            "from cscp_rd_turn_task p1",
            "left join cscp_user p2 on p1.cur_assignee = p2.id",
            "left join cscp_user p3 on p1.last_assignee = p3.id",
            "where p1.user_id = #{userId,jdbcType=BIGINT} and p1.type = #{type,jdbcType=VARCHAR}",
            "order by p1.create_time desc"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
            @Result(column="form_id", property="formId", jdbcType=JdbcType.VARCHAR),
            @Result(column="process_id", property="processId", jdbcType=JdbcType.VARCHAR),
            @Result(column="process_instid", property="processInstid", jdbcType=JdbcType.VARCHAR),
            @Result(column="process_name", property="processName", jdbcType=JdbcType.VARCHAR),
            @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
            @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
            @Result(column="curAssigneeName", property="curAssigneeName", jdbcType=JdbcType.VARCHAR),
            @Result(column="lastAssigneeName", property="lastAssigneeName", jdbcType=JdbcType.VARCHAR)
    })
    List<ActRdTurnTask> selectRdTurnTask(ActRdTurnTask actRdTurnTask);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_rd_turn_task
     *
     * @date 2022-07-28 18:44:24
     */
    @Select({
            "select",
            "id,",
            "user_id,",
            "form_id,",
            "process_id,",
            "process_instid,",
            "process_name,",
            "type,",
            "create_time",
            "from cscp_rd_turn_task",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
            @Result(column="form_id", property="formId", jdbcType=JdbcType.VARCHAR),
            @Result(column="process_id", property="processId", jdbcType=JdbcType.VARCHAR),
            @Result(column="process_instid", property="processInstid", jdbcType=JdbcType.VARCHAR),
            @Result(column="process_name", property="processName", jdbcType=JdbcType.VARCHAR),
            @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
            @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE)
    })
    @Override
    ActRdTurnTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_rd_turn_task
     *
     * @date 2022-07-28 18:44:24
     */
    @UpdateProvider(type=ActRdTurnTaskSqlProvider.class, method="updateByExampleSelective")
    @Override
    int updateByExampleSelective(@Param("record") ActRdTurnTask record, @Param("example") ActRdTurnTaskExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_rd_turn_task
     *
     * @date 2022-07-28 18:44:24
     */
    @UpdateProvider(type=ActRdTurnTaskSqlProvider.class, method="updateByExample")
    @Override
    int updateByExample(@Param("record") ActRdTurnTask record, @Param("example") ActRdTurnTaskExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_rd_turn_task
     *
     *@date 2022-07-28 18:44:24
     */
    @UpdateProvider(type=ActRdTurnTaskSqlProvider.class, method="updateByPrimaryKeySelective")
    @Override
    int updateByPrimaryKeySelective(ActRdTurnTask record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_rd_turn_task
     *
     * @date 2022-07-28 18:44:24
     */
    @Update({
            "update cscp_rd_turn_task",
            "set ",
            "id = #{id,jdbcType=BIGINT},",
            "user_id = #{userId,jdbcType=BIGINT},",
            "form_id = #{formId,jdbcType=VARCHAR},",
            "process_id = #{processId,jdbcType=VARCHAR},",
            "process_instid = #{processInstid,jdbcType=VARCHAR},",
            "process_name = #{processName,jdbcType=VARCHAR},",
            "type = #{type,jdbcType=VARCHAR},",
            "create_time = #{createTime,jdbcType=DATE}",

            "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int updateByPrimaryKey(ActRdTurnTask record);

    /**
     * 批量删除
     * @param ids
     */
    @Delete("<script>" +
            "delete from cscp_rd_turn_task where id in" +
            "<foreach collection=\"ids\" item=\"id\" open=\"(\" separator=\",\" close=\")\">" +
            "#{id}" +
            "</foreach>" +
            "</script>")
    void deleteByIds(@Param("ids") List<Long> ids);


    @Select("<script>" +
            " select form_id from cscp_flow_process_def_ext where process_definition_id = #{id}" +
            "</script>")
    String qryFormIdByProcessDefinitionId(@RequestParam("id") String id);
}





