package com.ctsi.flow.repository;

import com.ctsi.flow.param.model.ActRdTurnTask;
import com.ctsi.flow.param.model.ActRdTurnTaskExample;
import com.ctsi.flow.param.model.ActRdTurnTaskExample.Criteria;
import com.ctsi.flow.param.model.ActRdTurnTaskExample.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;


/**
 * ActRdTurnTaskSqlProvider
 *
 * @author hx
 * @date 2022-07-28 18:44:24
 */

public class ActRdTurnTaskSqlProvider {

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_rd_turn_task
     */
    public String countByExample(ActRdTurnTaskExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("cscp_rd_turn_task");
        applyWhere(sql, example, false);
        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_rd_turn_task
     */
    public String deleteByExample(ActRdTurnTaskExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("cscp_rd_turn_task");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_rd_turn_task
     */
    public String insertSelective(ActRdTurnTask record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("cscp_rd_turn_task");

        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=BIGINT}");
        }
        if (record.getFormId() != null) {
            sql.VALUES("form_id", "#{formId,jdbcType=VARCHAR}");
        }
        if (record.getProcessId() != null) {
            sql.VALUES("process_id", "#{processId,jdbcType=VARCHAR}");
        }
        if (record.getProcessInstid() != null) {
            sql.VALUES("process_instid", "#{processInstid,jdbcType=VARCHAR}");
        }
        if (record.getProcessName() != null) {
            sql.VALUES("process_name", "#{processName,jdbcType=VARCHAR}");
        }
        if (record.getType() != null) {
            sql.VALUES("type", "#{type,jdbcType=VARCHAR}");
        }
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=DATE}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_rd_turn_task
     */
    public String selectByExample(ActRdTurnTaskExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("user_id");
        sql.SELECT("form_id");
        sql.SELECT("process_id");
        sql.SELECT("process_instid");
        sql.SELECT("process_name");
        sql.SELECT("type");
        sql.SELECT("create_time");
        sql.FROM("cscp_rd_turn_task");
        applyWhere(sql, example, false);

        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_rd_turn_task
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ActRdTurnTask record = (ActRdTurnTask) parameter.get("record");
        ActRdTurnTaskExample example = (ActRdTurnTaskExample) parameter.get("example");

        SQL sql = new SQL();
        sql.UPDATE("cscp_rd_turn_task");

        if (record.getId() != null) {
            sql.SET("id = #{id,jdbcType=BIGINT}");
        }
        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=BIGINT}");
        }
        if (record.getFormId() != null) {
            sql.SET("form_id = #{formId,jdbcType=VARCHAR}");
        }
        if (record.getProcessId() != null) {
            sql.SET("process_id = #{processId,jdbcType=VARCHAR}");
        }
        if (record.getProcessInstid() != null) {
            sql.SET("process_instid = #{processInstid,jdbcType=VARCHAR}");
        }
        if (record.getProcessName() != null) {
            sql.SET("process_name = #{processName,jdbcType=VARCHAR}");
        }
        if (record.getType() != null) {
            sql.SET("type = #{type,jdbcType=VARCHAR}");
        }
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=DATE}");
        }
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_rd_turn_task
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_rd_turn_task");
        sql.SET("id = #{id,jdbcType=BIGINT}");
        sql.SET("user_id = #{userId,jdbcType=BIGINT}");
        sql.SET("form_id = #{formId,jdbcType=VARCHAR}");
        sql.SET("process_id = #{processId,jdbcType=VARCHAR}");
        sql.SET("process_instid = #{processInstid,jdbcType=VARCHAR}");
        sql.SET("process_name = #{processName,jdbcType=VARCHAR}");
        sql.SET("type = #{type,jdbcType=VARCHAR}");
        sql.SET("create_time = #{createTime,jdbcType=DATE}");

        ActRdTurnTaskExample example = (ActRdTurnTaskExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_rd_turn_task
     */
    public String updateByPrimaryKeySelective(ActRdTurnTask record) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_rd_turn_task");

        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=BIGINT}");
        }
        if (record.getFormId() != null) {
            sql.SET("form_id = #{formId,jdbcType=VARCHAR}");
        }
        if (record.getProcessId() != null) {
            sql.SET("process_id = #{processId,jdbcType=VARCHAR}");
        }
        if (record.getProcessInstid() != null) {
            sql.SET("process_instid = #{processInstid,jdbcType=VARCHAR}");
        }
        if (record.getProcessName() != null) {
            sql.SET("process_name = #{processName,jdbcType=VARCHAR}");
        }
        if (record.getType() != null) {
            sql.SET("type = #{type,jdbcType=VARCHAR}");
        }
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=DATE}");
        }
        sql.WHERE("id = #{id,jdbcType=BIGINT}");

        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_rd_turn_task
     */
    protected void applyWhere(SQL sql, ActRdTurnTaskExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1Th;
        String parmPhrase2;
        String parmPhrase2Th;
        String parmPhrase3;
        String parmPhrase3Th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1Th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2Th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3Th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}
