package com.ctsi.flow.repository;

import com.ctsi.flow.param.model.CscpUserAct;
import com.ctsi.flow.param.model.CscpUserActExample;
import com.ctsi.flow.param.model.CscpUserActExample.Criteria;
import com.ctsi.flow.param.model.CscpUserActExample.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;


/**
 * CscpUserActSqlProvider
 *
 * @author hx
 * @date 2022-07-26 15:55:12
*/

public class CscpUserActSqlProvider {

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_act
     */
    public String countByExample(CscpUserActExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("cscp_user_act");
        applyWhere(sql, example, false);
        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_act
     */
    public String deleteByExample(CscpUserActExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("cscp_user_act");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_act
     */
    public String insertSelective(CscpUserAct record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("cscp_user_act");

        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=BIGINT}");
        }
        if (record.getProcDefId() != null) {
            sql.VALUES("proc_def_id", "#{procDefId,jdbcType=VARCHAR}");
        }
        if (record.getProcDefName() != null) {
            sql.VALUES("proc_def_name", "#{procDefName,jdbcType=VARCHAR}");
        }
        if (record.getFormId() != null) {
            sql.VALUES("form_id", "#{formId,jdbcType=BIGINT}");
        }
        if (record.getDefinedId() != null) {
            sql.VALUES("defined_id", "#{definedId,jdbcType=VARCHAR}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_act
     */
    public String selectByExample(CscpUserActExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("user_id");
        sql.SELECT("proc_def_id");
        sql.SELECT("proc_def_name");
        sql.SELECT("form_id");
        sql.SELECT("defined_id");
        sql.FROM("cscp_user_act");
        applyWhere(sql, example, false);

        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_act
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CscpUserAct record = (CscpUserAct) parameter.get("record");
        CscpUserActExample example = (CscpUserActExample) parameter.get("example");

        SQL sql = new SQL();
        sql.UPDATE("cscp_user_act");

        if (record.getId() != null) {
        sql.SET("id = #{id,jdbcType=BIGINT}");
        }
        if (record.getUserId() != null) {
        sql.SET("user_id = #{userId,jdbcType=BIGINT}");
        }
        if (record.getProcDefId() != null) {
        sql.SET("proc_def_id = #{procDefId,jdbcType=VARCHAR}");
        }
        if (record.getProcDefName() != null) {
        sql.SET("proc_def_name = #{procDefName,jdbcType=VARCHAR}");
        }
        if (record.getFormId() != null) {
        sql.SET("form_id = #{formId,jdbcType=BIGINT}");
        }
        if (record.getDefinedId() != null) {
        sql.SET("defined_id = #{definedId,jdbcType=VARCHAR}");
        }
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_act
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_user_act");
        sql.SET("id = #{id,jdbcType=BIGINT}");
        sql.SET("user_id = #{userId,jdbcType=BIGINT}");
        sql.SET("proc_def_id = #{procDefId,jdbcType=VARCHAR}");
        sql.SET("proc_def_name = #{procDefName,jdbcType=VARCHAR}");
        sql.SET("form_id = #{formId,jdbcType=BIGINT}");
        sql.SET("defined_id = #{definedId,jdbcType=VARCHAR}");

        CscpUserActExample example = (CscpUserActExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_act
     */
    public String updateByPrimaryKeySelective(CscpUserAct record) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_user_act");

        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=BIGINT}");
        }
        if (record.getProcDefId() != null) {
            sql.SET("proc_def_id = #{procDefId,jdbcType=VARCHAR}");
        }
        if (record.getProcDefName() != null) {
            sql.SET("proc_def_name = #{procDefName,jdbcType=VARCHAR}");
        }
        if (record.getFormId() != null) {
            sql.SET("form_id = #{formId,jdbcType=BIGINT}");
        }
        if (record.getDefinedId() != null) {
            sql.SET("defined_id = #{definedId,jdbcType=VARCHAR}");
        }
        sql.WHERE("id = #{id,jdbcType=BIGINT}");

        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_user_act
     */
    protected void applyWhere(SQL sql, CscpUserActExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1Th;
        String parmPhrase2;
        String parmPhrase2Th;
        String parmPhrase3;
        String parmPhrase3Th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1Th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2Th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3Th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}
