package com.ctsi.flow.repository;

import com.ctsi.flow.param.model.CscpFlowProcessDefExt;
import com.ctsi.flow.param.model.CscpFlowProcessDefExtExample.Criteria;
import com.ctsi.flow.param.model.CscpFlowProcessDefExtExample.Criterion;
import com.ctsi.flow.param.model.CscpFlowProcessDefExtExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;


/**
 * CscpFlowProcessDefExtSqlProvider
 *
 * @author hx
 * @date 2022-08-05 10:08:04
*/

public class CscpFlowProcessDefExtSqlProvider {

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_process_def_ext
     */
    public String countByExample(CscpFlowProcessDefExtExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("cscp_flow_process_def_ext");
        applyWhere(sql, example, false);
        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_process_def_ext
     */
    public String deleteByExample(CscpFlowProcessDefExtExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("cscp_flow_process_def_ext");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_process_def_ext
     */
    public String insertSelective(CscpFlowProcessDefExt record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("cscp_flow_process_def_ext");

        if (record.getDescription() != null) {
            sql.VALUES("description", "#{description,jdbcType=VARCHAR}");
        }
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=DATE}");
        }
        if (record.getCreator() != null) {
            sql.VALUES("creator", "#{creator,jdbcType=VARCHAR}");
        }
        if (record.getModelId() != null) {
            sql.VALUES("model_id", "#{modelId,jdbcType=VARCHAR}");
        }
        if (record.getFormId() != null) {
            sql.VALUES("form_id", "#{formId,jdbcType=BIGINT}");
        }
        if (record.getProcessDefinitionId() != null) {
            sql.VALUES("process_definition_id", "#{processDefinitionId,jdbcType=VARCHAR}");
        }
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        if (record.getTenantId() != null) {
            sql.VALUES("tenant_id", "#{tenantId,jdbcType=BIGINT}");
        }
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=DATE}");
        }
        if (record.getUpdater() != null) {
            sql.VALUES("updater", "#{updater,jdbcType=VARCHAR}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_process_def_ext
     */
    public String selectByExample(CscpFlowProcessDefExtExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("description");
        sql.SELECT("create_time");
        sql.SELECT("creator");
        sql.SELECT("model_id");
        sql.SELECT("form_id");
        sql.SELECT("process_definition_id");
        sql.SELECT("tenant_id");
        sql.SELECT("update_time");
        sql.SELECT("updater");
        sql.FROM("cscp_flow_process_def_ext");
        applyWhere(sql, example, false);

        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_process_def_ext
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CscpFlowProcessDefExt record = (CscpFlowProcessDefExt) parameter.get("record");
        CscpFlowProcessDefExtExample example = (CscpFlowProcessDefExtExample) parameter.get("example");

        SQL sql = new SQL();
        sql.UPDATE("cscp_flow_process_def_ext");

        if (record.getDescription() != null) {
        sql.SET("description = #{description,jdbcType=VARCHAR}");
        }
        if (record.getCreateTime() != null) {
        sql.SET("create_time = #{createTime,jdbcType=DATE}");
        }
        if (record.getCreator() != null) {
        sql.SET("creator = #{creator,jdbcType=VARCHAR}");
        }
        if (record.getModelId() != null) {
        sql.SET("model_id = #{modelId,jdbcType=VARCHAR}");
        }
        if (record.getFormId() != null) {
        sql.SET("form_id = #{formId,jdbcType=BIGINT}");
        }
        if (record.getProcessDefinitionId() != null) {
        sql.SET("process_definition_id = #{processDefinitionId,jdbcType=VARCHAR}");
        }
        if (record.getId() != null) {
        sql.SET("id = #{id,jdbcType=BIGINT}");
        }
        if (record.getTenantId() != null) {
        sql.SET("tenant_id = #{tenantId,jdbcType=BIGINT}");
        }
        if (record.getUpdateTime() != null) {
        sql.SET("update_time = #{updateTime,jdbcType=DATE}");
        }
        if (record.getUpdater() != null) {
        sql.SET("updater = #{updater,jdbcType=VARCHAR}");
        }
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_process_def_ext
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_flow_process_def_ext");
        sql.SET("description = #{description,jdbcType=VARCHAR}");
        sql.SET("create_time = #{createTime,jdbcType=DATE}");
        sql.SET("creator = #{creator,jdbcType=VARCHAR}");
        sql.SET("model_id = #{modelId,jdbcType=VARCHAR}");
        sql.SET("form_id = #{formId,jdbcType=BIGINT}");
        sql.SET("process_definition_id = #{processDefinitionId,jdbcType=VARCHAR}");
        sql.SET("id = #{id,jdbcType=BIGINT}");
        sql.SET("tenant_id = #{tenantId,jdbcType=BIGINT}");
        sql.SET("update_time = #{updateTime,jdbcType=DATE}");
        sql.SET("updater = #{updater,jdbcType=VARCHAR}");

        CscpFlowProcessDefExtExample example = (CscpFlowProcessDefExtExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_process_def_ext
     */
    public String updateByPrimaryKeySelective(CscpFlowProcessDefExt record) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_flow_process_def_ext");

        if (record.getDescription() != null) {
            sql.SET("description = #{description,jdbcType=VARCHAR}");
        }
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=DATE}");
        }
        if (record.getCreator() != null) {
            sql.SET("creator = #{creator,jdbcType=VARCHAR}");
        }
        if (record.getModelId() != null) {
            sql.SET("model_id = #{modelId,jdbcType=VARCHAR}");
        }
        if (record.getFormId() != null) {
            sql.SET("form_id = #{formId,jdbcType=BIGINT}");
        }
        if (record.getProcessDefinitionId() != null) {
            sql.SET("process_definition_id = #{processDefinitionId,jdbcType=VARCHAR}");
        }
        if (record.getTenantId() != null) {
            sql.SET("tenant_id = #{tenantId,jdbcType=BIGINT}");
        }
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=DATE}");
        }
        if (record.getUpdater() != null) {
            sql.SET("updater = #{updater,jdbcType=VARCHAR}");
        }
        sql.WHERE("id = #{id,jdbcType=BIGINT}");

        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_process_def_ext
     */
    protected void applyWhere(SQL sql, CscpFlowProcessDefExtExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1Th;
        String parmPhrase2;
        String parmPhrase2Th;
        String parmPhrase3;
        String parmPhrase3Th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1Th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2Th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3Th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}
