package com.ctsi.ssdc.dic.repository;

import com.ctsi.ssdc.dic.domain.CscpHxDicItem;
import com.ctsi.ssdc.dic.domain.CscpHxDicItemExample.Criteria;
import com.ctsi.ssdc.dic.domain.CscpHxDicItemExample.Criterion;
import com.ctsi.ssdc.dic.domain.CscpHxDicItemExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

/**
 * @author ctsi-biyi-generator
*/
public class CscpHxDicItemSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public String countByExample(CscpHxDicItemExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("cscp_hx_dic_item");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public String deleteByExample(CscpHxDicItemExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("cscp_hx_dic_item");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public String insertSelective(CscpHxDicItem record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("cscp_hx_dic_item");
        
        if (record.getItemId() != null) {
            sql.VALUES("item_id", "#{itemId,jdbcType=BIGINT}");
        }
        
        if (record.getDicId() != null) {
            sql.VALUES("dic_id", "#{dicId,jdbcType=BIGINT}");
        }
        
        if (record.getItemCode() != null) {
            sql.VALUES("item_code", "#{itemCode,jdbcType=VARCHAR}");
        }
        
        if (record.getItemValue() != null) {
            sql.VALUES("item_value", "#{itemValue,jdbcType=VARCHAR}");
        }
        
        if (record.getItemSort() != null) {
            sql.VALUES("item_sort", "#{itemSort,jdbcType=INTEGER}");
        }
        
        if (record.getDescription() != null) {
            sql.VALUES("description", "#{description,jdbcType=VARCHAR}");
        }
        
        if (record.getItemParentId() != null) {
            sql.VALUES("item_parent_id", "#{itemParentId,jdbcType=BIGINT}");
        }
        
        if (record.getAncestors() != null) {
            sql.VALUES("ancestors", "#{ancestors,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public String selectByExample(CscpHxDicItemExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("item_id");
        } else {
            sql.SELECT("item_id");
        }
        sql.SELECT("dic_id");
        sql.SELECT("item_code");
        sql.SELECT("item_value");
        sql.SELECT("item_sort");
        sql.SELECT("description");
        sql.SELECT("item_parent_id");
        sql.SELECT("ancestors");
        sql.FROM("cscp_hx_dic_item");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CscpHxDicItem record = (CscpHxDicItem) parameter.get("record");
        CscpHxDicItemExample example = (CscpHxDicItemExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("cscp_hx_dic_item");
        
        if (record.getItemId() != null) {
            sql.SET("item_id = #{record.itemId,jdbcType=BIGINT}");
        }
        
        if (record.getDicId() != null) {
            sql.SET("dic_id = #{record.dicId,jdbcType=BIGINT}");
        }
        
        if (record.getItemCode() != null) {
            sql.SET("item_code = #{record.itemCode,jdbcType=VARCHAR}");
        }
        
        if (record.getItemValue() != null) {
            sql.SET("item_value = #{record.itemValue,jdbcType=VARCHAR}");
        }
        
        if (record.getItemSort() != null) {
            sql.SET("item_sort = #{record.itemSort,jdbcType=INTEGER}");
        }
        
        if (record.getDescription() != null) {
            sql.SET("description = #{record.description,jdbcType=VARCHAR}");
        }
        
        if (record.getItemParentId() != null) {
            sql.SET("item_parent_id = #{record.itemParentId,jdbcType=BIGINT}");
        }
        
        if (record.getAncestors() != null) {
            sql.SET("ancestors = #{record.ancestors,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_hx_dic_item");
        
        sql.SET("item_id = #{record.itemId,jdbcType=BIGINT}");
        sql.SET("dic_id = #{record.dicId,jdbcType=BIGINT}");
        sql.SET("item_code = #{record.itemCode,jdbcType=VARCHAR}");
        sql.SET("item_value = #{record.itemValue,jdbcType=VARCHAR}");
        sql.SET("item_sort = #{record.itemSort,jdbcType=INTEGER}");
        sql.SET("description = #{record.description,jdbcType=VARCHAR}");
        sql.SET("item_parent_id = #{record.itemParentId,jdbcType=BIGINT}");
        sql.SET("ancestors = #{record.ancestors,jdbcType=VARCHAR}");
        
        CscpHxDicItemExample example = (CscpHxDicItemExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public String updateByPrimaryKeySelective(CscpHxDicItem record) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_hx_dic_item");
        
        if (record.getDicId() != null) {
            sql.SET("dic_id = #{dicId,jdbcType=BIGINT}");
        }
        
        if (record.getItemCode() != null) {
            sql.SET("item_code = #{itemCode,jdbcType=VARCHAR}");
        }
        
        if (record.getItemValue() != null) {
            sql.SET("item_value = #{itemValue,jdbcType=VARCHAR}");
        }
        
        if (record.getItemSort() != null) {
            sql.SET("item_sort = #{itemSort,jdbcType=INTEGER}");
        }
        
        if (record.getDescription() != null) {
            sql.SET("description = #{description,jdbcType=VARCHAR}");
        }
        
        if (record.getItemParentId() != null) {
            sql.SET("item_parent_id = #{itemParentId,jdbcType=BIGINT}");
        }
        
        if (record.getAncestors() != null) {
            sql.SET("ancestors = #{ancestors,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("item_id = #{itemId,jdbcType=BIGINT}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    protected void applyWhere(SQL sql, CscpHxDicItemExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1Th;
        String parmPhrase2;
        String parmPhrase2Th;
        String parmPhrase3;
        String parmPhrase3Th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1Th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2Th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3Th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}