package com.ctsi.ssdc.dic.repository;

import com.ctsi.ssdc.dic.domain.CscpHxDicCustom;
import com.ctsi.ssdc.dic.domain.CscpHxDicCustomExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

/**
 * @author ctsi-biyi-generator
*/
@Mapper
public interface CscpHxDicCustomRepository extends com.ctsi.ssdc.repository.BaseRepository<CscpHxDicCustom, Long, CscpHxDicCustomExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_custom
     *
     * @mbg.generated Fri Feb 11 14:36:02 CST 2022
     */
    @SelectProvider(type=CscpHxDicCustomSqlProvider.class, method="countByExample")
    @Override
    long countByExample(CscpHxDicCustomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_custom
     *
     * @mbg.generated Fri Feb 11 14:36:02 CST 2022
     */
    @DeleteProvider(type=CscpHxDicCustomSqlProvider.class, method="deleteByExample")
    @Override
    int deleteByExample(CscpHxDicCustomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_custom
     *
     * @mbg.generated Fri Feb 11 14:36:02 CST 2022
     */
    @Delete({
        "delete from cscp_hx_dic_custom",
        "where dic_id = #{dicId,jdbcType=BIGINT}"
    })
    @Override
    int deleteByPrimaryKey(Long dicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_custom
     *
     * @mbg.generated Fri Feb 11 14:36:02 CST 2022
     */
    @Insert({
        "insert into cscp_hx_dic_custom (dic_id, dic_name, ",
        "dic_code, dic_sort, ",
        "dic_class, dic_method, ",
        "description)",
        "values (#{dicId,jdbcType=BIGINT}, #{dicName,jdbcType=VARCHAR}, ",
        "#{dicCode,jdbcType=VARCHAR}, #{dicSort,jdbcType=INTEGER}, ",
        "#{dicClass,jdbcType=VARCHAR}, #{dicMethod,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR})"
    })
    @Override
    int insert(CscpHxDicCustom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_custom
     *
     * @mbg.generated Fri Feb 11 14:36:02 CST 2022
     */
    @InsertProvider(type=CscpHxDicCustomSqlProvider.class, method="insertSelective")
    @Override
    int insertSelective(CscpHxDicCustom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_custom
     *
     * @mbg.generated Fri Feb 11 14:36:02 CST 2022
     */
    @SelectProvider(type=CscpHxDicCustomSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="dic_id", property="dicId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="dic_name", property="dicName", jdbcType=JdbcType.VARCHAR),
        @Result(column="dic_code", property="dicCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="dic_sort", property="dicSort", jdbcType=JdbcType.INTEGER),
        @Result(column="dic_class", property="dicClass", jdbcType=JdbcType.VARCHAR),
        @Result(column="dic_method", property="dicMethod", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR)
    })
    @Override
    List<CscpHxDicCustom> selectByExample(CscpHxDicCustomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_custom
     *
     * @mbg.generated Fri Feb 11 14:36:02 CST 2022
     */
    @Select({
        "select",
        "dic_id, dic_name, dic_code, dic_sort, dic_class, dic_method, description",
        "from cscp_hx_dic_custom",
        "where dic_id = #{dicId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="dic_id", property="dicId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="dic_name", property="dicName", jdbcType=JdbcType.VARCHAR),
        @Result(column="dic_code", property="dicCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="dic_sort", property="dicSort", jdbcType=JdbcType.INTEGER),
        @Result(column="dic_class", property="dicClass", jdbcType=JdbcType.VARCHAR),
        @Result(column="dic_method", property="dicMethod", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR)
    })
    @Override
    CscpHxDicCustom selectByPrimaryKey(Long dicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_custom
     *
     * @mbg.generated Fri Feb 11 14:36:02 CST 2022
     */
    @UpdateProvider(type=CscpHxDicCustomSqlProvider.class, method="updateByExampleSelective")
    @Override
    int updateByExampleSelective(@Param("record") CscpHxDicCustom record, @Param("example") CscpHxDicCustomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_custom
     *
     * @mbg.generated Fri Feb 11 14:36:02 CST 2022
     */
    @UpdateProvider(type=CscpHxDicCustomSqlProvider.class, method="updateByExample")
    @Override
    int updateByExample(@Param("record") CscpHxDicCustom record, @Param("example") CscpHxDicCustomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_custom
     *
     * @mbg.generated Fri Feb 11 14:36:02 CST 2022
     */
    @UpdateProvider(type=CscpHxDicCustomSqlProvider.class, method="updateByPrimaryKeySelective")
    @Override
    int updateByPrimaryKeySelective(CscpHxDicCustom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_custom
     *
     * @mbg.generated Fri Feb 11 14:36:02 CST 2022
     */
    @Update({
        "update cscp_hx_dic_custom",
        "set dic_name = #{dicName,jdbcType=VARCHAR},",
          "dic_code = #{dicCode,jdbcType=VARCHAR},",
          "dic_sort = #{dicSort,jdbcType=INTEGER},",
          "dic_class = #{dicClass,jdbcType=VARCHAR},",
          "dic_method = #{dicMethod,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR}",
        "where dic_id = #{dicId,jdbcType=BIGINT}"
    })
    @Override
    int updateByPrimaryKey(CscpHxDicCustom record);
}