package com.ctsi.ssdc.dic.repository;

import com.ctsi.ssdc.dic.domain.CscpHxDic;
import com.ctsi.ssdc.dic.domain.CscpHxDicExample;
import com.ctsi.ssdc.dic.domain.CscpHxDicExample.Criteria;
import com.ctsi.ssdc.dic.domain.CscpHxDicExample.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

/**
 * @author ctsi-biyi-generator
*/
public class CscpHxDicSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic
     *
     * @mbg.generated Thu Feb 10 14:19:22 CST 2022
     */
    public String countByExample(CscpHxDicExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("cscp_hx_dic");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic
     *
     * @mbg.generated Thu Feb 10 14:19:22 CST 2022
     */
    public String deleteByExample(CscpHxDicExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("cscp_hx_dic");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic
     *
     * @mbg.generated Thu Feb 10 14:19:22 CST 2022
     */
    public String insertSelective(CscpHxDic record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("cscp_hx_dic");
        
        if (record.getDicId() != null) {
            sql.VALUES("dic_id", "#{dicId,jdbcType=BIGINT}");
        }
        
        if (record.getDicName() != null) {
            sql.VALUES("dic_name", "#{dicName,jdbcType=VARCHAR}");
        }
        
        if (record.getDicCode() != null) {
            sql.VALUES("dic_code", "#{dicCode,jdbcType=VARCHAR}");
        }
        
        if (record.getDicSort() != null) {
            sql.VALUES("dic_sort", "#{dicSort,jdbcType=INTEGER}");
        }
        
        if (record.getDicAttr() != null) {
            sql.VALUES("dic_attr", "#{dicAttr,jdbcType=VARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.VALUES("description", "#{description,jdbcType=VARCHAR}");
        }

        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic
     *
     * @mbg.generated Thu Feb 10 14:19:22 CST 2022
     */
    public String selectByExample(CscpHxDicExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("dic_id");
        } else {
            sql.SELECT("dic_id");
        }
        sql.SELECT("dic_name");
        sql.SELECT("dic_code");
        sql.SELECT("dic_sort");
        sql.SELECT("dic_attr");
        sql.SELECT("description");
        sql.FROM("cscp_hx_dic");
        applyWhere(sql, example, false);

        sql.ORDER_BY("dic_sort");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic
     *
     * @mbg.generated Thu Feb 10 14:19:22 CST 2022
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CscpHxDic record = (CscpHxDic) parameter.get("record");
        CscpHxDicExample example = (CscpHxDicExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("cscp_hx_dic");
        
        if (record.getDicId() != null) {
            sql.SET("dic_id = #{record.dicId,jdbcType=BIGINT}");
        }
        
        if (record.getDicName() != null) {
            sql.SET("dic_name = #{record.dicName,jdbcType=VARCHAR}");
        }
        
        if (record.getDicCode() != null) {
            sql.SET("dic_code = #{record.dicCode,jdbcType=VARCHAR}");
        }
        
        if (record.getDicSort() != null) {
            sql.SET("dic_sort = #{record.dicSort,jdbcType=INTEGER}");
        }
        
        if (record.getDicAttr() != null) {
            sql.SET("dic_attr = #{record.dicAttr,jdbcType=VARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.SET("description = #{record.description,jdbcType=VARCHAR}");
        }

        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic
     *
     * @mbg.generated Thu Feb 10 14:19:22 CST 2022
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_hx_dic");
        
        sql.SET("dic_id = #{record.dicId,jdbcType=BIGINT}");
        sql.SET("dic_name = #{record.dicName,jdbcType=VARCHAR}");
        sql.SET("dic_code = #{record.dicCode,jdbcType=VARCHAR}");
        sql.SET("dic_sort = #{record.dicSort,jdbcType=INTEGER}");
        sql.SET("dic_attr = #{record.dicAttr,jdbcType=VARCHAR}");
        sql.SET("description = #{record.description,jdbcType=VARCHAR}");
        sql.SET("dic_parent_id = #{record.dicParentId,jdbcType=BIGINT}");
        sql.SET("ancestors = #{record.ancestors,jdbcType=VARCHAR}");
        
        CscpHxDicExample example = (CscpHxDicExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic
     *
     * @mbg.generated Thu Feb 10 14:19:22 CST 2022
     */
    public String updateByPrimaryKeySelective(CscpHxDic record) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_hx_dic");
        
        if (record.getDicName() != null) {
            sql.SET("dic_name = #{dicName,jdbcType=VARCHAR}");
        }
        
        if (record.getDicCode() != null) {
            sql.SET("dic_code = #{dicCode,jdbcType=VARCHAR}");
        }
        
        if (record.getDicSort() != null) {
            sql.SET("dic_sort = #{dicSort,jdbcType=INTEGER}");
        }
        
        if (record.getDicAttr() != null) {
            sql.SET("dic_attr = #{dicAttr,jdbcType=VARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.SET("description = #{description,jdbcType=VARCHAR}");
        }

        
        sql.WHERE("dic_id = #{dicId,jdbcType=BIGINT}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic
     *
     * @mbg.generated Thu Feb 10 14:19:22 CST 2022
     */
    protected void applyWhere(SQL sql, CscpHxDicExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1Th;
        String parmPhrase2;
        String parmPhrase2Th;
        String parmPhrase3;
        String parmPhrase3Th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1Th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2Th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3Th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}