package com.ctsi.ssdc.dic.repository;

import com.ctsi.ssdc.dic.domain.CscpHxSqldicBaseinfo;
import com.ctsi.ssdc.dic.domain.CscpHxSqldicBaseinfoExample.Criteria;
import com.ctsi.ssdc.dic.domain.CscpHxSqldicBaseinfoExample.Criterion;
import com.ctsi.ssdc.dic.domain.CscpHxSqldicBaseinfoExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

/**
 * @author ctsi-biyi-generator
*/
public class CscpHxSqldicBaseinfoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_sqldic_baseinfo
     *
     * @mbg.generated Wed Feb 09 15:11:18 CST 2022
     */
    public String countByExample(CscpHxSqldicBaseinfoExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("cscp_hx_sqldic_baseinfo");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_sqldic_baseinfo
     *
     * @mbg.generated Wed Feb 09 15:11:18 CST 2022
     */
    public String deleteByExample(CscpHxSqldicBaseinfoExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("cscp_hx_sqldic_baseinfo");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_sqldic_baseinfo
     *
     * @mbg.generated Wed Feb 09 15:11:18 CST 2022
     */
    public String insertSelective(CscpHxSqldicBaseinfo record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("cscp_hx_sqldic_baseinfo");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getDicSelectSql() != null) {
            sql.VALUES("dic_select_sql", "#{dicSelectSql,jdbcType=VARCHAR}");
        }
        
        if (record.getDicName() != null) {
            sql.VALUES("dic_name", "#{dicName,jdbcType=VARCHAR}");
        }
        
        if (record.getDicCode() != null) {
            sql.VALUES("dic_code", "#{dicCode,jdbcType=VARCHAR}");
        }
        
        if (record.getDicNotes() != null) {
            sql.VALUES("dic_notes", "#{dicNotes,jdbcType=VARCHAR}");
        }
        
        if (record.getDicItemCodeColumn() != null) {
            sql.VALUES("dic_item_code_column", "#{dicItemCodeColumn,jdbcType=VARCHAR}");
        }
        
        if (record.getDicItemValueColumn() != null) {
            sql.VALUES("dic_item_value_column", "#{dicItemValueColumn,jdbcType=VARCHAR}");
        }
        
        if (record.getDicItemValueNotes() != null) {
            sql.VALUES("dic_item_value_notes", "#{dicItemValueNotes,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateUser() != null) {
            sql.VALUES("create_user", "#{createUser,jdbcType=BIGINT}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateUser() != null) {
            sql.VALUES("update_user", "#{updateUser,jdbcType=BIGINT}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_sqldic_baseinfo
     *
     * @mbg.generated Wed Feb 09 15:11:18 CST 2022
     */
    public String selectByExample(CscpHxSqldicBaseinfoExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("dic_select_sql");
        sql.SELECT("dic_name");
        sql.SELECT("dic_code");
        sql.SELECT("dic_notes");
        sql.SELECT("dic_item_code_column");
        sql.SELECT("dic_item_value_column");
        sql.SELECT("dic_item_value_notes");
        sql.SELECT("create_time");
        sql.SELECT("create_user");
        sql.SELECT("update_time");
        sql.SELECT("update_user");
        sql.FROM("cscp_hx_sqldic_baseinfo");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_sqldic_baseinfo
     *
     * @mbg.generated Wed Feb 09 15:11:18 CST 2022
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CscpHxSqldicBaseinfo record = (CscpHxSqldicBaseinfo) parameter.get("record");
        CscpHxSqldicBaseinfoExample example = (CscpHxSqldicBaseinfoExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("cscp_hx_sqldic_baseinfo");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=BIGINT}");
        }
        
        if (record.getDicSelectSql() != null) {
            sql.SET("dic_select_sql = #{record.dicSelectSql,jdbcType=VARCHAR}");
        }
        
        if (record.getDicName() != null) {
            sql.SET("dic_name = #{record.dicName,jdbcType=VARCHAR}");
        }
        
        if (record.getDicCode() != null) {
            sql.SET("dic_code = #{record.dicCode,jdbcType=VARCHAR}");
        }
        
        if (record.getDicNotes() != null) {
            sql.SET("dic_notes = #{record.dicNotes,jdbcType=VARCHAR}");
        }
        
        if (record.getDicItemCodeColumn() != null) {
            sql.SET("dic_item_code_column = #{record.dicItemCodeColumn,jdbcType=VARCHAR}");
        }
        
        if (record.getDicItemValueColumn() != null) {
            sql.SET("dic_item_value_column = #{record.dicItemValueColumn,jdbcType=VARCHAR}");
        }
        
        if (record.getDicItemValueNotes() != null) {
            sql.SET("dic_item_value_notes = #{record.dicItemValueNotes,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateUser() != null) {
            sql.SET("create_user = #{record.createUser,jdbcType=BIGINT}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateUser() != null) {
            sql.SET("update_user = #{record.updateUser,jdbcType=BIGINT}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_sqldic_baseinfo
     *
     * @mbg.generated Wed Feb 09 15:11:18 CST 2022
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_hx_sqldic_baseinfo");
        
        sql.SET("id = #{record.id,jdbcType=BIGINT}");
        sql.SET("dic_select_sql = #{record.dicSelectSql,jdbcType=VARCHAR}");
        sql.SET("dic_name = #{record.dicName,jdbcType=VARCHAR}");
        sql.SET("dic_code = #{record.dicCode,jdbcType=VARCHAR}");
        sql.SET("dic_notes = #{record.dicNotes,jdbcType=VARCHAR}");
        sql.SET("dic_item_code_column = #{record.dicItemCodeColumn,jdbcType=VARCHAR}");
        sql.SET("dic_item_value_column = #{record.dicItemValueColumn,jdbcType=VARCHAR}");
        sql.SET("dic_item_value_notes = #{record.dicItemValueNotes,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("create_user = #{record.createUser,jdbcType=BIGINT}");
        sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        sql.SET("update_user = #{record.updateUser,jdbcType=BIGINT}");
        
        CscpHxSqldicBaseinfoExample example = (CscpHxSqldicBaseinfoExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_sqldic_baseinfo
     *
     * @mbg.generated Wed Feb 09 15:11:18 CST 2022
     */
    public String updateByPrimaryKeySelective(CscpHxSqldicBaseinfo record) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_hx_sqldic_baseinfo");
        
        if (record.getDicSelectSql() != null) {
            sql.SET("dic_select_sql = #{dicSelectSql,jdbcType=VARCHAR}");
        }
        
        if (record.getDicName() != null) {
            sql.SET("dic_name = #{dicName,jdbcType=VARCHAR}");
        }
        
        if (record.getDicCode() != null) {
            sql.SET("dic_code = #{dicCode,jdbcType=VARCHAR}");
        }
        
        if (record.getDicNotes() != null) {
            sql.SET("dic_notes = #{dicNotes,jdbcType=VARCHAR}");
        }
        
        if (record.getDicItemCodeColumn() != null) {
            sql.SET("dic_item_code_column = #{dicItemCodeColumn,jdbcType=VARCHAR}");
        }
        
        if (record.getDicItemValueColumn() != null) {
            sql.SET("dic_item_value_column = #{dicItemValueColumn,jdbcType=VARCHAR}");
        }
        
        if (record.getDicItemValueNotes() != null) {
            sql.SET("dic_item_value_notes = #{dicItemValueNotes,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateUser() != null) {
            sql.SET("create_user = #{createUser,jdbcType=BIGINT}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateUser() != null) {
            sql.SET("update_user = #{updateUser,jdbcType=BIGINT}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_sqldic_baseinfo
     *
     * @mbg.generated Wed Feb 09 15:11:18 CST 2022
     */
    protected void applyWhere(SQL sql, CscpHxSqldicBaseinfoExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1Th;
        String parmPhrase2;
        String parmPhrase2Th;
        String parmPhrase3;
        String parmPhrase3Th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1Th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2Th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3Th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}