package com.ctsi.ssdc.errorcode.repository;

import com.ctsi.ssdc.errorcode.domain.CscpErrorCode;
import com.ctsi.ssdc.errorcode.domain.CscpErrorCodeExample;
import com.ctsi.ssdc.errorcode.domain.CscpErrorCodeExample.Criteria;
import com.ctsi.ssdc.errorcode.domain.CscpErrorCodeExample.Criterion;
import com.ctsi.ssdc.errorcode.exception.enums.ErrorCodeTypeEnum;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;


/**
 * CscpErrorCodeSqlProvider
 *
 * @author hx
 * @date 2022-09-05 15:56:17
 */

public class CscpErrorCodeSqlProvider {

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_error_code
     */
    public String countByExample(CscpErrorCodeExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("cscp_error_code");
        applyWhere(sql, example, false);
        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_error_code
     */
    public String deleteByExample(CscpErrorCodeExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("cscp_error_code");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_error_code
     */
    public String insertSelective(CscpErrorCode record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("cscp_error_code");

        if (record.getCodeId() != null) {
            sql.VALUES("code_id", "#{codeId,jdbcType=BIGINT}");
        }
        if (record.getCodeType() != null) {
            sql.VALUES("code_type", "#{codeType,jdbcType=VARCHAR}");
        }
        if (record.getApplicationName() != null) {
            sql.VALUES("application_name", "#{applicationName,jdbcType=VARCHAR}");
        }
        if (record.getCode() != null) {
            sql.VALUES("code", "#{code,jdbcType=INTEGER}");
        }
        if (record.getCodeMessage() != null) {
            sql.VALUES("code_message", "#{codeMessage,jdbcType=VARCHAR}");
        }
        if (record.getRemark() != null) {
            sql.VALUES("remark", "#{remark,jdbcType=VARCHAR}");
        }
        if (record.getCreateBy() != null) {
            sql.VALUES("create_by", "#{createBy,jdbcType=VARCHAR}");
        }
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=DATE}");
        }
        if (record.getUpdateBy() != null) {
            sql.VALUES("update_by", "#{updateBy,jdbcType=VARCHAR}");
        }
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=DATE}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_error_code
     */
    public String selectByExample(CscpErrorCodeExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("code_id");
        } else {
            sql.SELECT("code_id");
        }
        sql.SELECT("code_type");
        sql.SELECT("application_name");
        sql.SELECT("code");
        sql.SELECT("code_message");
        sql.SELECT("remark");
        sql.SELECT("create_by");
        sql.SELECT("create_time");
        sql.SELECT("update_by");
        sql.SELECT("update_time");
        sql.FROM("cscp_error_code");
        applyWhere(sql, example, false);

        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_error_code
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CscpErrorCode record = (CscpErrorCode) parameter.get("record");
        CscpErrorCodeExample example = (CscpErrorCodeExample) parameter.get("example");

        SQL sql = new SQL();
        sql.UPDATE("cscp_error_code");

        if (record.getCodeId() != null) {
            sql.SET("code_id = #{codeId,jdbcType=BIGINT}");
        }
        if (record.getCodeType() != null) {
            sql.SET("code_type = #{codeType,jdbcType=VARCHAR}");
        }
        if (record.getApplicationName() != null) {
            sql.SET("application_name = #{applicationName,jdbcType=VARCHAR}");
        }
        if (record.getCode() != null) {
            sql.SET("code = #{code,jdbcType=INTEGER}");
        }
        if (record.getCodeMessage() != null) {
            sql.SET("code_message = #{codeMessage,jdbcType=VARCHAR}");
        }
        if (record.getRemark() != null) {
            sql.SET("remark = #{remark,jdbcType=VARCHAR}");
        }
        if (record.getCreateBy() != null) {
            sql.SET("create_by = #{createBy,jdbcType=VARCHAR}");
        }
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=DATE}");
        }
        if (record.getUpdateBy() != null) {
            sql.SET("update_by = #{updateBy,jdbcType=VARCHAR}");
        }
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=DATE}");
        }
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_error_code
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_error_code");
        sql.SET("code_id = #{codeId,jdbcType=BIGINT}");
        sql.SET("code_type = #{codeType,jdbcType=VARCHAR}");
        sql.SET("application_name = #{applicationName,jdbcType=VARCHAR}");
        sql.SET("code = #{code,jdbcType=INTEGER}");
        sql.SET("code_message = #{codeMessage,jdbcType=VARCHAR}");
        sql.SET("remark = #{remark,jdbcType=VARCHAR}");
        sql.SET("create_by = #{createBy,jdbcType=VARCHAR}");
        sql.SET("create_time = #{createTime,jdbcType=DATE}");
        sql.SET("update_by = #{updateBy,jdbcType=VARCHAR}");
        sql.SET("update_time = #{updateTime,jdbcType=DATE}");

        CscpErrorCodeExample example = (CscpErrorCodeExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_error_code
     */
    public String updateByPrimaryKeySelective(CscpErrorCode record) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_error_code");

        if (record.getCodeType() != null) {
            sql.SET("code_type = #{codeType,jdbcType=VARCHAR}");
        }
        if (record.getApplicationName() != null) {
            sql.SET("application_name = #{applicationName,jdbcType=VARCHAR}");
        }
        if (record.getCode() != null) {
            sql.SET("code = #{code,jdbcType=INTEGER}");
        }
        if (record.getCodeMessage() != null) {
            sql.SET("code_message = #{codeMessage,jdbcType=VARCHAR}");
        }
        if (record.getRemark() != null) {
            sql.SET("remark = #{remark,jdbcType=VARCHAR}");
        }
        if (record.getCreateBy() != null) {
            sql.SET("create_by = #{createBy,jdbcType=VARCHAR}");
        }
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=DATE}");
        }
        if (record.getUpdateBy() != null) {
            sql.SET("update_by = #{updateBy,jdbcType=VARCHAR}");
        }
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=DATE}");
        }
        sql.WHERE("code_id = #{codeId,jdbcType=BIGINT}");

        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_error_code
     */
    protected void applyWhere(SQL sql, CscpErrorCodeExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1Th;
        String parmPhrase2;
        String parmPhrase2Th;
        String parmPhrase3;
        String parmPhrase3Th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1Th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2Th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3Th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}
