package com.ctsi.ssdc.admin.domain;


import com.ctsi.ssdc.annocation.AutoId;
import com.ctsi.ssdc.util.LongtoStringSerialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.io.Serializable;
import java.util.Objects;

/**
 * @author MyBatis Generator
*/
public class CscpUserRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_role.id
     *
     * @mbg.generated Mon May 07 08:50:32 CST 2018
     */
    @AutoId(primaryKey = "id")
    @JsonSerialize(using = LongtoStringSerialize.class)
    //change
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_role.user_id
     *
     * @mbg.generated Mon May 07 08:50:32 CST 2018
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    //chnange
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_role.role_id
     *
     * @mbg.generated Mon May 07 08:50:32 CST 2018
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    //chnange
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_user_role
     *
     * @mbg.generated Mon May 07 08:50:32 CST 2018
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getRoleId() {
        return roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    public static long getSerialVersionUid() {
        return serialVersionUID;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof CscpUserRole)){
            return false;
        }
        CscpUserRole that = (CscpUserRole) o;
        return Objects.equals(id, that.id) &&
                Objects.equals(userId, that.userId) &&
                Objects.equals(roleId, that.roleId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, userId, roleId);
    }
}