package com.ctsi.ssdc.admin.domain;



import com.ctsi.ssdc.annocation.AutoId;
import com.ctsi.ssdc.util.LongtoStringSerialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.io.Serializable;
import java.time.ZonedDateTime;
import java.util.Objects;

/**
 * @author MyBatis Generator
*/

public class CscpUserDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.id
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    @AutoId(primaryKey = "id")
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.user_id
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.family_name
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    private String familyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.name
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.mobile
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.email
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.img_path
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    private String imgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.last_login
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    private ZonedDateTime lastLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.disc_title
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    private String discTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.disc_detail
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    private String discDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.register_time
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    private ZonedDateTime registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    
    private String username;

    /**
     * 用户管理员标志
     * 0：普通用户
     * 1：普通租户下的管理员
     * 2：租户管理员（超级管理员）
     */
    private String adminFlag;

    /**
     *  部门id
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long deptId;

    /**
     *  租户id
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long tenantId;


    /**
     *  第三方登录用户标志
     */
    private Long thirdType = 0L;

    public Long getThirdType() {
        return thirdType;
    }

    public void setThirdType(Long thirdType) {
        this.thirdType = thirdType;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public Long getDeptId() {
        return deptId;
    }

    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    public String getAdminFlag() {
        return adminFlag;
    }

    public void setAdminFlag(String adminFlag) {
        this.adminFlag = adminFlag;
    }

    private static final Long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getFamilyName() {
        return familyName;
    }

    public void setFamilyName(String familyName) {
        this.familyName = familyName;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getImgPath() {
        return imgPath;
    }

    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }

    public ZonedDateTime getLastLogin() {
        return lastLogin;
    }

    public void setLastLogin(ZonedDateTime lastLogin) {
        this.lastLogin = lastLogin;
    }

    public String getDiscTitle() {
        return discTitle;
    }

    public void setDiscTitle(String discTitle) {
        this.discTitle = discTitle;
    }

    public String getDiscDetail() {
        return discDetail;
    }

    public void setDiscDetail(String discDetail) {
        this.discDetail = discDetail;
    }

    public ZonedDateTime getRegisterTime() {
        return registerTime;
    }

    public void setRegisterTime(ZonedDateTime registerTime) {
        this.registerTime = registerTime;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public static long getSerialVersionUid() {
        return serialVersionUID;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof CscpUserDetail)) {
            return false;
        }
        CscpUserDetail that = (CscpUserDetail) o;
        return Objects.equals(id, that.id) &&
                Objects.equals(userId, that.userId) &&
                Objects.equals(familyName, that.familyName) &&
                Objects.equals(name, that.name) &&
                Objects.equals(mobile, that.mobile) &&
                Objects.equals(email, that.email) &&
                Objects.equals(imgPath, that.imgPath) &&
                Objects.equals(lastLogin, that.lastLogin) &&
                Objects.equals(discTitle, that.discTitle) &&
                Objects.equals(discDetail, that.discDetail) &&
                Objects.equals(registerTime, that.registerTime) &&
                Objects.equals(username, that.username) &&
                Objects.equals(adminFlag,that.adminFlag) &&
                Objects.equals(deptId,that.deptId) &&
                Objects.equals(tenantId,that.tenantId)&&
                Objects.equals(thirdType,that.thirdType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, userId, familyName, name, mobile,
                email, imgPath, lastLogin, discTitle, discDetail, registerTime, username, adminFlag,deptId,tenantId,thirdType);
    }
}