package com.ctsi.ssdc.admin.domain;


import com.ctsi.ssdc.annocation.AutoId;
import com.ctsi.ssdc.util.LongtoStringSerialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.io.Serializable;
import java.util.Objects;

/**
 * @author ctsi-biyi-generator
*/
public class CscpRoleMenu implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_role_menu.id
     *
     * @mbg.generated Wed Feb 13 10:04:08 CST 2019
     */
    @AutoId(primaryKey = "id")
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_role_menu.role_id
     *
     * @mbg.generated Wed Feb 13 10:04:08 CST 2019
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_role_menu.menu_id
     *
     * @mbg.generated Wed Feb 13 10:04:08 CST 2019
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long menuId;

    public static long getSerialVersionUid() {
        return serialVersionUID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getRoleId() {
        return roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    public Long getMenuId() {
        return menuId;
    }

    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof CscpRoleMenu)) {
            return false;
        }
        CscpRoleMenu that = (CscpRoleMenu) o;
        return Objects.equals(id, that.id) &&
                Objects.equals(roleId, that.roleId) &&
                Objects.equals(menuId, that.menuId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, roleId, menuId);
    }
}