package com.ctsi.ssdc.admin.domain;


import com.ctsi.ssdc.annocation.AutoId;
import com.ctsi.ssdc.util.LongtoStringSerialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.io.Serializable;
import java.util.Objects;

/**
 * @author MyBatis Generator
*/

public class CscpOrg implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_org.id
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    @AutoId(primaryKey = "id")
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_org.org_name
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    private String orgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_org.description
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_org.parent_id
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_org
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */

    private Integer orderby;

    public Integer getOrderby() {
        return orderby;
    }

    public void setOrderby(Integer orderby) {
        this.orderby = orderby;
    }

    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getParentId() {
        return parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    public static long getSerialVersionUid() {
        return serialVersionUID;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof CscpOrg)){
            return false;
        }
        CscpOrg cscpOrg = (CscpOrg) o;
        return Objects.equals(id, cscpOrg.id) &&
                Objects.equals(orgName, cscpOrg.orgName) &&
                Objects.equals(description, cscpOrg.description) &&
                Objects.equals(parentId, cscpOrg.parentId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, orgName, description, parentId);
    }
}