package com.ctsi.ssdc.admin.domain;


import com.ctsi.ssdc.annocation.AutoId;
import com.ctsi.ssdc.util.LongtoStringSerialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.io.Serializable;
import java.time.ZonedDateTime;
import java.util.Objects;

/**
 * 操作日志
 * @author MyBatis Generator
*/
public class CscpLogOperation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.id
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    @AutoId(primaryKey = "id")
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long id;

    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.userid
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.username
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.uri
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    private String uri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.ip
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.params
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    private String params;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.method
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.message
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.status
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.time
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    private ZonedDateTime time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.error
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    private String error;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_log_operation
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_log_operation.id
     *
     * @return the value of cscp_log_operation.id
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserid() {
        return userid;
    }

    public void setUserid(Long userid) {
        this.userid = userid;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public String getParams() {
        return params;
    }

    public void setParams(String params) {
        this.params = params;
    }

    public String getMethod() {
        return method;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public ZonedDateTime getTime() {
        return time;
    }

    public void setTime(ZonedDateTime time) {
        this.time = time;
    }

    public String getError() {
        return error;
    }

    public void setError(String error) {
        this.error = error;
    }

    public static long getSerialVersionUid() {
        return serialVersionUID;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof CscpLogOperation)) {
            return false;
        }
        CscpLogOperation that = (CscpLogOperation) o;
        return Objects.equals(getId(), that.getId()) &&
                Objects.equals(getTenantId(), that.getTenantId()) &&
                Objects.equals(getUserid(), that.getUserid()) &&
                Objects.equals(getUsername(), that.getUsername()) &&
                Objects.equals(getUri(), that.getUri()) &&
                Objects.equals(getIp(), that.getIp()) &&
                Objects.equals(getParams(), that.getParams()) &&
                Objects.equals(getMethod(), that.getMethod()) &&
                Objects.equals(getMessage(), that.getMessage()) &&
                Objects.equals(getStatus(), that.getStatus()) &&
                Objects.equals(getTime(), that.getTime()) &&
                Objects.equals(getError(), that.getError());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), getTenantId(),getUserid(), getUsername(),
                getUri(), getIp(), getParams(), getMethod(),
                getMessage(), getStatus(), getTime(), getError());
    }
}