package com.ctsi.ssdc.admin.domain;


import com.ctsi.ssdc.annocation.AutoId;
import com.ctsi.ssdc.util.LongtoStringSerialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;


import java.io.Serializable;
import java.util.Objects;

/**
 * @author MyBatis Generator
*/
public class CscpUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user.id
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    @AutoId(primaryKey = "id")
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user.username
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user.password
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_user
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public static long getSerialVersionUid() {
        return serialVersionUID;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof CscpUser)) {
            return false;
        }
        CscpUser cscpUser = (CscpUser) o;
        return Objects.equals(id, cscpUser.id) &&
                Objects.equals(username, cscpUser.username) &&
                Objects.equals(password, cscpUser.password);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, username, password);
    }
}