package com.ctsi.ssdc.admin.domain;


import com.ctsi.ssdc.annocation.AutoId;
import com.ctsi.ssdc.util.LongtoStringSerialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.io.Serializable;
import java.util.Objects;

/**
 * @author MyBatis Generator
*/

public class CscpWorkGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_work_group.id
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    @AutoId(primaryKey = "id")
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_work_group.group_name
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_work_group.description
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_work_group.org_id
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_work_group
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getOrgId() {
        return orgId;
    }

    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    public static long getSerialVersionUid() {
        return serialVersionUID;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o){
            return true;
        }
        if (!(o instanceof CscpWorkGroup)){
            return false;
        }
        CscpWorkGroup that = (CscpWorkGroup) o;
        return Objects.equals(id, that.id) &&
                Objects.equals(groupName, that.groupName) &&
                Objects.equals(description, that.description) &&
                Objects.equals(orgId, that.orgId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, groupName, description, orgId);
    }
}