package com.ctsi.ssdc.admin.domain;

import com.ctsi.ssdc.annocation.AutoId;
import com.ctsi.ssdc.util.LongtoStringSerialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Data;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * @author MyBatis Generator
*/
@Data
public class CscpMenus implements Serializable {

    /** 子部门 */
    private List<CscpMenus> children = new ArrayList<CscpMenus>();

    public List<CscpMenus> getChildren() {
        return children;
    }

    public void setChildren(List<CscpMenus> children) {
        this.children = children;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.id
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    @AutoId(primaryKey = "id")
    @JsonSerialize(using = LongtoStringSerialize.class)
    //change
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.name
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.icon
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.title
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.url
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.http_method
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    private String httpMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.component
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    private String component;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.parent_id
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    //change
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.type
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.permission_code
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    private String permissionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.orderby
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    private Integer orderby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_menus
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    private static final long serialVersionUID = 1L;

    private List<Long> roleId;

    private List<String> roleName;

    private Integer flag;

    public Integer getFlag() {
        return flag;
    }

    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    public List<String> getRoleName() {
        return roleName;
    }

    public void setRoleName(List<String> roleName) {
        this.roleName = roleName;
    }

    public List<Long> getRoleId() {
        return roleId;
    }

    public void setRoleId(List<Long> roleId) {
        this.roleId = roleId;
    }


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getHttpMethod() {
        return httpMethod;
    }

    public void setHttpMethod(String httpMethod) {
        this.httpMethod = httpMethod;
    }

    public String getComponent() {
        return component;
    }

    public void setComponent(String component) {
        this.component = component;
    }

    public Long getParentId() {
        return parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getPermissionCode() {
        return permissionCode;
    }

    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode;
    }

    public Integer getOrderby() {
        return orderby;
    }

    public void setOrderby(Integer orderby) {
        this.orderby = orderby;
    }

    public static long getSerialVersionUid() {
        return serialVersionUID;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof CscpMenus)) {
            return false;
        }
        CscpMenus cscpMenus = (CscpMenus) o;
        return id.equals(cscpMenus.id) &&
                name.equals(cscpMenus.name) &&
                icon.equals(cscpMenus.icon) &&
                title.equals(cscpMenus.title) &&
                url.equals(cscpMenus.url) &&
                httpMethod.equals(cscpMenus.httpMethod) &&
                component.equals(cscpMenus.component) &&
                parentId.equals(cscpMenus.parentId) &&
                type.equals(cscpMenus.type) &&
                permissionCode.equals(cscpMenus.permissionCode) &&
                orderby.equals(cscpMenus.orderby);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, icon, title, url, httpMethod, component, parentId, type, permissionCode, orderby);
    }
}