package com.ctsi.ssdc.admin.domain;

import com.ctsi.ssdc.criteria.LongCriteria;
import com.ctsi.ssdc.criteria.StringCriteria;
import com.ctsi.ssdc.criteria.DateCriteria;
import com.ctsi.ssdc.example.BaseExample;
import io.swagger.annotations.ApiParam;
import org.apache.commons.lang3.StringUtils;
import java.util.Date;
import java.util.ArrayList;
import java.util.List;

/**
 * @author ctsi-biyi-generator
 */
public class CscpUserDetailExample extends BaseExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    protected org.springframework.data.domain.Pageable page;
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    public void setPage(org.springframework.data.domain.Pageable page) {
        this.page = page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    public org.springframework.data.domain.Pageable getPage() {
        return page;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private static final String LIKE_FORMAT = "%%%s%%";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.id
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private LongCriteria id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.user_id
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private LongCriteria userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.family_name
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private StringCriteria familyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.name
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private StringCriteria name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.mobile
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private StringCriteria mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.email
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private StringCriteria email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.last_login
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private DateCriteria lastLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.disc_title
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private StringCriteria discTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.disc_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private StringCriteria discDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.register_time
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private DateCriteria registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.admin_flag
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private StringCriteria adminFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.dept_id
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private LongCriteria deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_detail.tenant_id
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private LongCriteria tenantId;

    // 第三方登录表示
    private StringCriteria thirdType;

    public StringCriteria getThirdType() {
        return thirdType;
    }

    public void setThirdType(StringCriteria thirdType) {
        this.thirdType = thirdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public CscpUserDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    @Override
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public LongCriteria getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public void setId(LongCriteria id) {
        this. id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private void buildIdCriteria(Criteria criteria) {
        if (this.getId() == null) {
            return;
        }
        if (this.getId().getEquals() != null) {
            criteria.andIdEqualTo(this.getId().getEquals());
        } else {
            if (this.getId().getGreaterOrEqualThan() != null) {
                criteria.andIdGreaterThanOrEqualTo(this.getId().getGreaterOrEqualThan());
            }
            if (this.getId().getLessOrEqualThan() != null) {
                criteria.andIdLessThanOrEqualTo(this.getId().getLessOrEqualThan());
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public LongCriteria getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public void setUserId(LongCriteria userId) {
        this. userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private void buildUserIdCriteria(Criteria criteria) {
        if (this.getUserId() == null) {
            return;
        }
        if (this.getUserId().getEquals() != null) {
            criteria.andUserIdEqualTo(this.getUserId().getEquals());
        } else {
            if (this.getUserId().getGreaterOrEqualThan() != null) {
                criteria.andUserIdGreaterThanOrEqualTo(this.getUserId().getGreaterOrEqualThan());
            }
            if (this.getUserId().getLessOrEqualThan() != null) {
                criteria.andUserIdLessThanOrEqualTo(this.getUserId().getLessOrEqualThan());
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public StringCriteria getFamilyName() {
        return familyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public void setFamilyName(StringCriteria familyName) {
        this. familyName = familyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private void buildFamilyNameCriteria(Criteria criteria) {
        if (this.getFamilyName() == null) {
            return;
        }
        if (this.getFamilyName().getEquals() != null) {
            criteria.andFamilyNameEqualTo(this.getFamilyName().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getFamilyName().getContains())) {
                criteria.andFamilyNameLike(String.format(LIKE_FORMAT, this.getFamilyName().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public StringCriteria getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public void setName(StringCriteria name) {
        this. name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private void buildNameCriteria(Criteria criteria) {
        if (this.getName() == null) {
            return;
        }
        if (this.getName().getEquals() != null) {
            criteria.andNameEqualTo(this.getName().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getName().getContains())) {
                criteria.andNameLike(String.format(LIKE_FORMAT, this.getName().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public StringCriteria getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public void setMobile(StringCriteria mobile) {
        this. mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private void buildMobileCriteria(Criteria criteria) {
        if (this.getMobile() == null) {
            return;
        }
        if (this.getMobile().getEquals() != null) {
            criteria.andMobileEqualTo(this.getMobile().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getMobile().getContains())) {
                criteria.andMobileLike(String.format(LIKE_FORMAT, this.getMobile().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public StringCriteria getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public void setEmail(StringCriteria email) {
        this. email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private void buildEmailCriteria(Criteria criteria) {
        if (this.getEmail() == null) {
            return;
        }
        if (this.getEmail().getEquals() != null) {
            criteria.andEmailEqualTo(this.getEmail().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getEmail().getContains())) {
                criteria.andEmailLike(String.format(LIKE_FORMAT, this.getEmail().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public DateCriteria getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public void setLastLogin(DateCriteria lastLogin) {
        this. lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private void buildLastLoginCriteria(Criteria criteria) {
        if (this.getLastLogin() == null) {
            return;
        }
        if (this.getLastLogin().getEquals() != null) {
            criteria.andLastLoginEqualTo(this.getLastLogin().getEquals());
        } else {
            if (this.getLastLogin().getGreaterOrEqualThan() != null) {
                criteria.andLastLoginGreaterThanOrEqualTo(this.getLastLogin().getGreaterOrEqualThan());
            }
            if (this.getLastLogin().getLessOrEqualThan() != null) {
                criteria.andLastLoginLessThanOrEqualTo(this.getLastLogin().getLessOrEqualThan());
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public StringCriteria getDiscTitle() {
        return discTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public void setDiscTitle(StringCriteria discTitle) {
        this. discTitle = discTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private void buildDiscTitleCriteria(Criteria criteria) {
        if (this.getDiscTitle() == null) {
            return;
        }
        if (this.getDiscTitle().getEquals() != null) {
            criteria.andDiscTitleEqualTo(this.getDiscTitle().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getDiscTitle().getContains())) {
                criteria.andDiscTitleLike(String.format(LIKE_FORMAT, this.getDiscTitle().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public StringCriteria getDiscDetail() {
        return discDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public void setDiscDetail(StringCriteria discDetail) {
        this. discDetail = discDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private void buildDiscDetailCriteria(Criteria criteria) {
        if (this.getDiscDetail() == null) {
            return;
        }
        if (this.getDiscDetail().getEquals() != null) {
            criteria.andDiscDetailEqualTo(this.getDiscDetail().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getDiscDetail().getContains())) {
                criteria.andDiscDetailLike(String.format(LIKE_FORMAT, this.getDiscDetail().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public DateCriteria getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public void setRegisterTime(DateCriteria registerTime) {
        this. registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private void buildRegisterTimeCriteria(Criteria criteria) {
        if (this.getRegisterTime() == null) {
            return;
        }
        if (this.getRegisterTime().getEquals() != null) {
            criteria.andRegisterTimeEqualTo(this.getRegisterTime().getEquals());
        } else {
            if (this.getRegisterTime().getGreaterOrEqualThan() != null) {
                criteria.andRegisterTimeGreaterThanOrEqualTo(this.getRegisterTime().getGreaterOrEqualThan());
            }
            if (this.getRegisterTime().getLessOrEqualThan() != null) {
                criteria.andRegisterTimeLessThanOrEqualTo(this.getRegisterTime().getLessOrEqualThan());
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public StringCriteria getAdminFlag() {
        return adminFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public void setAdminFlag(StringCriteria adminFlag) {
        this. adminFlag = adminFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private void buildAdminFlagCriteria(Criteria criteria) {
        if (this.getAdminFlag() == null) {
            return;
        }
        if (this.getAdminFlag().getEquals() != null) {
            criteria.andAdminFlagEqualTo(this.getAdminFlag().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getAdminFlag().getContains())) {
                criteria.andAdminFlagLike(String.format(LIKE_FORMAT, this.getAdminFlag().getContains()));
            }
        }
    }

    private void buildThirdTypeCriteria(Criteria criteria) {
        if (this.getThirdType() == null) {
            return;
        }
        if (this.getThirdType().getEquals() != null) {
            criteria.andThirdTypeEqualTo(this.getThirdType().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getThirdType().getContains())) {
                criteria.andThirdTypeLike(String.format(LIKE_FORMAT, this.getThirdType().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public LongCriteria getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public void setDeptId(LongCriteria deptId) {
        this. deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private void buildDeptIdCriteria(Criteria criteria) {
        if (this.getDeptId() == null) {
            return;
        }
        if (this.getDeptId().getEquals() != null) {
            criteria.andDeptIdEqualTo(this.getDeptId().getEquals());
        } else {
            if (this.getDeptId().getGreaterOrEqualThan() != null) {
                criteria.andDeptIdGreaterThanOrEqualTo(this.getDeptId().getGreaterOrEqualThan());
            }
            if (this.getDeptId().getLessOrEqualThan() != null) {
                criteria.andDeptIdLessThanOrEqualTo(this.getDeptId().getLessOrEqualThan());
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public LongCriteria getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public void setTenantId(LongCriteria tenantId) {
        this. tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    private void buildTenantIdCriteria(Criteria criteria) {
        if (this.getTenantId() == null) {
            return;
        }
        if (this.getTenantId().getEquals() != null) {
            criteria.andTenantIdEqualTo(this.getTenantId().getEquals());
        } else {
            if (this.getTenantId().getGreaterOrEqualThan() != null) {
                criteria.andTenantIdGreaterThanOrEqualTo(this.getTenantId().getGreaterOrEqualThan());
            }
            if (this.getTenantId().getLessOrEqualThan() != null) {
                criteria.andTenantIdLessThanOrEqualTo(this.getTenantId().getLessOrEqualThan());
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    @Override
    public Object buildCriteria() {
        Criteria criteria = this.createCriteria();
        this.buildIdCriteria(criteria);
        this.buildUserIdCriteria(criteria);
        this.buildFamilyNameCriteria(criteria);
        this.buildNameCriteria(criteria);
        this.buildMobileCriteria(criteria);
        this.buildEmailCriteria(criteria);
        this.buildLastLoginCriteria(criteria);
        this.buildDiscTitleCriteria(criteria);
        this.buildDiscDetailCriteria(criteria);
        this.buildRegisterTimeCriteria(criteria);
        this.buildAdminFlagCriteria(criteria);
        this.buildDeptIdCriteria(criteria);
        this.buildTenantIdCriteria(criteria);
        return criteria;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    protected abstract static class BaseGeneratedCriteria {
        protected List<Criterion> criteria;

        protected BaseGeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andFamilyNameIsNull() {
            addCriterion("family_name is null");
            return (Criteria) this;
        }

        public Criteria andFamilyNameIsNotNull() {
            addCriterion("family_name is not null");
            return (Criteria) this;
        }

        public Criteria andFamilyNameEqualTo(String value) {
            addCriterion("family_name =", value, "familyName");
            return (Criteria) this;
        }

        public Criteria andFamilyNameNotEqualTo(String value) {
            addCriterion("family_name <>", value, "familyName");
            return (Criteria) this;
        }

        public Criteria andFamilyNameGreaterThan(String value) {
            addCriterion("family_name >", value, "familyName");
            return (Criteria) this;
        }

        public Criteria andFamilyNameGreaterThanOrEqualTo(String value) {
            addCriterion("family_name >=", value, "familyName");
            return (Criteria) this;
        }

        public Criteria andFamilyNameLessThan(String value) {
            addCriterion("family_name <", value, "familyName");
            return (Criteria) this;
        }

        public Criteria andFamilyNameLessThanOrEqualTo(String value) {
            addCriterion("family_name <=", value, "familyName");
            return (Criteria) this;
        }

        public Criteria andFamilyNameLike(String value) {
            addCriterion("family_name like", value, "familyName");
            return (Criteria) this;
        }

        public Criteria andFamilyNameNotLike(String value) {
            addCriterion("family_name not like", value, "familyName");
            return (Criteria) this;
        }

        public Criteria andFamilyNameIn(List<String> values) {
            addCriterion("family_name in", values, "familyName");
            return (Criteria) this;
        }

        public Criteria andFamilyNameNotIn(List<String> values) {
            addCriterion("family_name not in", values, "familyName");
            return (Criteria) this;
        }

        public Criteria andFamilyNameBetween(String value1, String value2) {
            addCriterion("family_name between", value1, value2, "familyName");
            return (Criteria) this;
        }

        public Criteria andFamilyNameNotBetween(String value1, String value2) {
            addCriterion("family_name not between", value1, value2, "familyName");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }
        public Criteria andImgPathIsNull() {
            addCriterion("img_path is null");
            return (Criteria) this;
        }

        public Criteria andImgPathIsNotNull() {
            addCriterion("img_path is not null");
            return (Criteria) this;
        }

        public Criteria andImgPathEqualTo(String value) {
            addCriterion("img_path =", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathNotEqualTo(String value) {
            addCriterion("img_path <>", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathGreaterThan(String value) {
            addCriterion("img_path >", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathGreaterThanOrEqualTo(String value) {
            addCriterion("img_path >=", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathLessThan(String value) {
            addCriterion("img_path <", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathLessThanOrEqualTo(String value) {
            addCriterion("img_path <=", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathLike(String value) {
            addCriterion("img_path like", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathNotLike(String value) {
            addCriterion("img_path not like", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathIn(List<String> values) {
            addCriterion("img_path in", values, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathNotIn(List<String> values) {
            addCriterion("img_path not in", values, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathBetween(String value1, String value2) {
            addCriterion("img_path between", value1, value2, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathNotBetween(String value1, String value2) {
            addCriterion("img_path not between", value1, value2, "imgPath");
            return (Criteria) this;
        }

        public Criteria andLastLoginIsNull() {
            addCriterion("last_login is null");
            return (Criteria) this;
        }

        public Criteria andLastLoginIsNotNull() {
            addCriterion("last_login is not null");
            return (Criteria) this;
        }

        public Criteria andLastLoginEqualTo(Date value) {
            addCriterion("last_login =", value, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginNotEqualTo(Date value) {
            addCriterion("last_login <>", value, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginGreaterThan(Date value) {
            addCriterion("last_login >", value, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginGreaterThanOrEqualTo(Date value) {
            addCriterion("last_login >=", value, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginLessThan(Date value) {
            addCriterion("last_login <", value, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginLessThanOrEqualTo(Date value) {
            addCriterion("last_login <=", value, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginIn(List<Date> values) {
            addCriterion("last_login in", values, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginNotIn(List<Date> values) {
            addCriterion("last_login not in", values, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginBetween(Date value1, Date value2) {
            addCriterion("last_login between", value1, value2, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginNotBetween(Date value1, Date value2) {
            addCriterion("last_login not between", value1, value2, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andDiscTitleIsNull() {
            addCriterion("disc_title is null");
            return (Criteria) this;
        }

        public Criteria andDiscTitleIsNotNull() {
            addCriterion("disc_title is not null");
            return (Criteria) this;
        }

        public Criteria andDiscTitleEqualTo(String value) {
            addCriterion("disc_title =", value, "discTitle");
            return (Criteria) this;
        }

        public Criteria andDiscTitleNotEqualTo(String value) {
            addCriterion("disc_title <>", value, "discTitle");
            return (Criteria) this;
        }

        public Criteria andDiscTitleGreaterThan(String value) {
            addCriterion("disc_title >", value, "discTitle");
            return (Criteria) this;
        }

        public Criteria andDiscTitleGreaterThanOrEqualTo(String value) {
            addCriterion("disc_title >=", value, "discTitle");
            return (Criteria) this;
        }

        public Criteria andDiscTitleLessThan(String value) {
            addCriterion("disc_title <", value, "discTitle");
            return (Criteria) this;
        }

        public Criteria andDiscTitleLessThanOrEqualTo(String value) {
            addCriterion("disc_title <=", value, "discTitle");
            return (Criteria) this;
        }

        public Criteria andDiscTitleLike(String value) {
            addCriterion("disc_title like", value, "discTitle");
            return (Criteria) this;
        }

        public Criteria andDiscTitleNotLike(String value) {
            addCriterion("disc_title not like", value, "discTitle");
            return (Criteria) this;
        }

        public Criteria andDiscTitleIn(List<String> values) {
            addCriterion("disc_title in", values, "discTitle");
            return (Criteria) this;
        }

        public Criteria andDiscTitleNotIn(List<String> values) {
            addCriterion("disc_title not in", values, "discTitle");
            return (Criteria) this;
        }

        public Criteria andDiscTitleBetween(String value1, String value2) {
            addCriterion("disc_title between", value1, value2, "discTitle");
            return (Criteria) this;
        }

        public Criteria andDiscTitleNotBetween(String value1, String value2) {
            addCriterion("disc_title not between", value1, value2, "discTitle");
            return (Criteria) this;
        }

        public Criteria andDiscDetailIsNull() {
            addCriterion("disc_detail is null");
            return (Criteria) this;
        }

        public Criteria andDiscDetailIsNotNull() {
            addCriterion("disc_detail is not null");
            return (Criteria) this;
        }

        public Criteria andDiscDetailEqualTo(String value) {
            addCriterion("disc_detail =", value, "discDetail");
            return (Criteria) this;
        }

        public Criteria andDiscDetailNotEqualTo(String value) {
            addCriterion("disc_detail <>", value, "discDetail");
            return (Criteria) this;
        }

        public Criteria andDiscDetailGreaterThan(String value) {
            addCriterion("disc_detail >", value, "discDetail");
            return (Criteria) this;
        }

        public Criteria andDiscDetailGreaterThanOrEqualTo(String value) {
            addCriterion("disc_detail >=", value, "discDetail");
            return (Criteria) this;
        }

        public Criteria andDiscDetailLessThan(String value) {
            addCriterion("disc_detail <", value, "discDetail");
            return (Criteria) this;
        }

        public Criteria andDiscDetailLessThanOrEqualTo(String value) {
            addCriterion("disc_detail <=", value, "discDetail");
            return (Criteria) this;
        }

        public Criteria andDiscDetailLike(String value) {
            addCriterion("disc_detail like", value, "discDetail");
            return (Criteria) this;
        }

        public Criteria andDiscDetailNotLike(String value) {
            addCriterion("disc_detail not like", value, "discDetail");
            return (Criteria) this;
        }

        public Criteria andDiscDetailIn(List<String> values) {
            addCriterion("disc_detail in", values, "discDetail");
            return (Criteria) this;
        }

        public Criteria andDiscDetailNotIn(List<String> values) {
            addCriterion("disc_detail not in", values, "discDetail");
            return (Criteria) this;
        }

        public Criteria andDiscDetailBetween(String value1, String value2) {
            addCriterion("disc_detail between", value1, value2, "discDetail");
            return (Criteria) this;
        }

        public Criteria andDiscDetailNotBetween(String value1, String value2) {
            addCriterion("disc_detail not between", value1, value2, "discDetail");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIsNull() {
            addCriterion("register_time is null");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIsNotNull() {
            addCriterion("register_time is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeEqualTo(Date value) {
            addCriterion("register_time =", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotEqualTo(Date value) {
            addCriterion("register_time <>", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeGreaterThan(Date value) {
            addCriterion("register_time >", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("register_time >=", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeLessThan(Date value) {
            addCriterion("register_time <", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeLessThanOrEqualTo(Date value) {
            addCriterion("register_time <=", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIn(List<Date> values) {
            addCriterion("register_time in", values, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotIn(List<Date> values) {
            addCriterion("register_time not in", values, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeBetween(Date value1, Date value2) {
            addCriterion("register_time between", value1, value2, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotBetween(Date value1, Date value2) {
            addCriterion("register_time not between", value1, value2, "registerTime");
            return (Criteria) this;
        }

        public Criteria andAdminFlagIsNull() {
            addCriterion("admin_flag is null");
            return (Criteria) this;
        }

        public Criteria andAdminFlagIsNotNull() {
            addCriterion("admin_flag is not null");
            return (Criteria) this;
        }

        public Criteria andAdminFlagEqualTo(String value) {
            addCriterion("admin_flag =", value, "adminFlag");
            return (Criteria) this;
        }

        public Criteria andAdminFlagNotEqualTo(String value) {
            addCriterion("admin_flag <>", value, "adminFlag");
            return (Criteria) this;
        }

        public Criteria andAdminFlagGreaterThan(String value) {
            addCriterion("admin_flag >", value, "adminFlag");
            return (Criteria) this;
        }

        public Criteria andAdminFlagGreaterThanOrEqualTo(String value) {
            addCriterion("admin_flag >=", value, "adminFlag");
            return (Criteria) this;
        }

        public Criteria andAdminFlagLessThan(String value) {
            addCriterion("admin_flag <", value, "adminFlag");
            return (Criteria) this;
        }

        public Criteria andAdminFlagLessThanOrEqualTo(String value) {
            addCriterion("admin_flag <=", value, "adminFlag");
            return (Criteria) this;
        }

        public Criteria andAdminFlagLike(String value) {
            addCriterion("admin_flag like", value, "adminFlag");
            return (Criteria) this;
        }

        public Criteria andAdminFlagNotLike(String value) {
            addCriterion("admin_flag not like", value, "adminFlag");
            return (Criteria) this;
        }

        public Criteria andAdminFlagIn(List<String> values) {
            addCriterion("admin_flag in", values, "adminFlag");
            return (Criteria) this;
        }

        public Criteria andAdminFlagNotIn(List<String> values) {
            addCriterion("admin_flag not in", values, "adminFlag");
            return (Criteria) this;
        }

        public Criteria andAdminFlagBetween(String value1, String value2) {
            addCriterion("admin_flag between", value1, value2, "adminFlag");
            return (Criteria) this;
        }

        public Criteria andAdminFlagNotBetween(String value1, String value2) {
            addCriterion("admin_flag not between", value1, value2, "adminFlag");
            return (Criteria) this;
        }



        public Criteria andThirdTypeIsNull() {
            addCriterion("third_type is null");
            return (Criteria) this;
        }

        public Criteria andThirdTypeIsNotNull() {
            addCriterion("third_type is not null");
            return (Criteria) this;
        }

        public Criteria andThirdTypeEqualTo(String value) {
            addCriterion("third_type =", value, "thirdType");
            return (Criteria) this;
        }

        public Criteria andThirdTypeNotEqualTo(String value) {
            addCriterion("third_type <>", value, "thirdType");
            return (Criteria) this;
        }

        public Criteria andThirdTypeGreaterThan(String value) {
            addCriterion("third_type >", value, "thirdType");
            return (Criteria) this;
        }

        public Criteria andThirdTypeGreaterThanOrEqualTo(String value) {
            addCriterion("third_type >=", value, "ThirdType");
            return (Criteria) this;
        }

        public Criteria andThirdTypeLessThan(String value) {
            addCriterion("third_type <", value, "thirdType");
            return (Criteria) this;
        }

        public Criteria andThirdTypeLessThanOrEqualTo(String value) {
            addCriterion("third_type <=", value, "thirdType");
            return (Criteria) this;
        }

        public Criteria andThirdTypeLike(String value) {
            addCriterion("third_type like", value, "thirdType");
            return (Criteria) this;
        }

        public Criteria andThirdTypeNotLike(String value) {
            addCriterion("third_type not like", value, "thirdType");
            return (Criteria) this;
        }

        public Criteria andThirdTypeIn(List<String> values) {
            addCriterion("third_type in", values, "thirdType");
            return (Criteria) this;
        }

        public Criteria andThirdTypeNotIn(List<String> values) {
            addCriterion("third_type not in", values, "thirdType");
            return (Criteria) this;
        }

        public Criteria andThirdTypeBetween(String value1, String value2) {
            addCriterion("third_type between", value1, value2, "thirdType");
            return (Criteria) this;
        }

        public Criteria andThirdTypeNotBetween(String value1, String value2) {
            addCriterion("third_type not between", value1, value2, "thirdType");
            return (Criteria) this;
        }



        public Criteria andDeptIdIsNull() {
            addCriterion("dept_id is null");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNotNull() {
            addCriterion("dept_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeptIdEqualTo(Long value) {
            addCriterion("dept_id =", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotEqualTo(Long value) {
            addCriterion("dept_id <>", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThan(Long value) {
            addCriterion("dept_id >", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThanOrEqualTo(Long value) {
            addCriterion("dept_id >=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThan(Long value) {
            addCriterion("dept_id <", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThanOrEqualTo(Long value) {
            addCriterion("dept_id <=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIn(List<Long> values) {
            addCriterion("dept_id in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotIn(List<Long> values) {
            addCriterion("dept_id not in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdBetween(Long value1, Long value2) {
            addCriterion("dept_id between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotBetween(Long value1, Long value2) {
            addCriterion("dept_id not between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNull() {
            addCriterion("tenant_id is null");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNotNull() {
            addCriterion("tenant_id is not null");
            return (Criteria) this;
        }

        public Criteria andTenantIdEqualTo(Long value) {
            addCriterion("tenant_id =", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotEqualTo(Long value) {
            addCriterion("tenant_id <>", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThan(Long value) {
            addCriterion("tenant_id >", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThanOrEqualTo(Long value) {
            addCriterion("tenant_id >=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThan(Long value) {
            addCriterion("tenant_id <", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThanOrEqualTo(Long value) {
            addCriterion("tenant_id <=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdIn(List<Long> values) {
            addCriterion("tenant_id in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotIn(List<Long> values) {
            addCriterion("tenant_id not in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdBetween(Long value1, Long value2) {
            addCriterion("tenant_id between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotBetween(Long value1, Long value2) {
            addCriterion("tenant_id not between", value1, value2, "tenantId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cscp_user_detail
     *
     * @mbg.generated do_not_delete_during_merge Fri Jan 07 17:05:06 CST 2022
     */
    public static class Criteria extends BaseGeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cscp_user_detail
     *
     * @mbg.generated Fri Jan 07 17:05:06 CST 2022
     */
    public static class Criterion {
        @ApiParam(hidden=true)
        private String condition;

        @ApiParam(hidden=true)
        private Object value;

        @ApiParam(hidden=true)
        private Object secondValue;

        @ApiParam(hidden=true)
        private boolean noValue;

        @ApiParam(hidden=true)
        private boolean singleValue;

        @ApiParam(hidden=true)
        private boolean betweenValue;

        @ApiParam(hidden=true)
        private boolean listValue;

        @ApiParam(hidden=true)
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}