package com.ctsi.ssdc.customize.repository;

import com.ctsi.ssdc.customize.domain.CscpCustomizeModel;
import com.ctsi.ssdc.customize.domain.CscpCustomizeModelExample.Criteria;
import com.ctsi.ssdc.customize.domain.CscpCustomizeModelExample.Criterion;
import com.ctsi.ssdc.customize.domain.CscpCustomizeModelExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;


/**
 * CscpCustomizeModelSqlProvider
 *
 * @author hx
 * @date 2022-09-01 10:11:14
*/

public class CscpCustomizeModelSqlProvider {

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model
     */
    public String countByExample(CscpCustomizeModelExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("cscp_customize_model");
        applyWhere(sql, example, false);
        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model
     */
    public String deleteByExample(CscpCustomizeModelExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("cscp_customize_model");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model
     */
    public String insertSelective(CscpCustomizeModel record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("cscp_customize_model");

        if (record.getModelId() != null) {
            sql.VALUES("model_id", "#{modelId,jdbcType=BIGINT}");
        }
        if (record.getModelType() != null) {
            sql.VALUES("model_type", "#{modelType,jdbcType=VARCHAR}");
        }
        if (record.getModelName() != null) {
            sql.VALUES("model_name", "#{modelName,jdbcType=VARCHAR}");
        }
        if (record.getModelIdentify() != null) {
            sql.VALUES("model_identify", "#{modelIdentify,jdbcType=VARCHAR}");
        }
        if (record.getTableName() != null) {
            sql.VALUES("table_name", "#{tableName,jdbcType=VARCHAR}");
        }
        if (record.getTableId() != null) {
            sql.VALUES("table_id", "#{tableId,jdbcType=BIGINT}");
        }
        if (record.getTableDescription() != null) {
            sql.VALUES("table_description", "#{tableDescription,jdbcType=VARCHAR}");
        }
        if (record.getModuleName() != null) {
            sql.VALUES("module_name", "#{moduleName,jdbcType=VARCHAR}");
        }
        if (record.getModuleId() != null) {
            sql.VALUES("module_id", "#{moduleId,jdbcType=BIGINT}");
        }
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=DATE}");
        }
        if (record.getCreatedBy() != null) {
            sql.VALUES("created_by", "#{createdBy,jdbcType=BIGINT}");
        }
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=DATE}");
        }
        if (record.getUpdateBy() != null) {
            sql.VALUES("update_by", "#{updateBy,jdbcType=BIGINT}");
        }
        if (record.getTenantId() != null) {
            sql.VALUES("tenant_id", "#{tenantId,jdbcType=BIGINT}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model
     */
    public String selectByExample(CscpCustomizeModelExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("model_id");
        } else {
            sql.SELECT("model_id");
        }
        sql.SELECT("model_type");
        sql.SELECT("model_name");
        sql.SELECT("model_identify");
        sql.SELECT("table_name");
        sql.SELECT("table_id");
        sql.SELECT("table_description");
        sql.SELECT("module_name");
        sql.SELECT("module_id");
        sql.SELECT("create_time");
        sql.SELECT("created_by");
        sql.SELECT("update_time");
        sql.SELECT("update_by");
        sql.SELECT("tenant_id");
        sql.SELECT("create_mode");
        sql.FROM("cscp_customize_model");
        applyWhere(sql, example, false);

        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CscpCustomizeModel record = (CscpCustomizeModel) parameter.get("record");
        CscpCustomizeModelExample example = (CscpCustomizeModelExample) parameter.get("example");

        SQL sql = new SQL();
        sql.UPDATE("cscp_customize_model");

        if (record.getModelId() != null) {
        sql.SET("model_id = #{modelId,jdbcType=BIGINT}");
        }
        if (record.getModelType() != null) {
        sql.SET("model_type = #{modelType,jdbcType=VARCHAR}");
        }
        if (record.getModelName() != null) {
        sql.SET("model_name = #{modelName,jdbcType=VARCHAR}");
        }
        if (record.getModelIdentify() != null) {
        sql.SET("model_identify = #{modelIdentify,jdbcType=VARCHAR}");
        }
        if (record.getTableName() != null) {
        sql.SET("table_name = #{tableName,jdbcType=VARCHAR}");
        }
        if (record.getTableId() != null) {
        sql.SET("table_id = #{tableId,jdbcType=BIGINT}");
        }
        if (record.getTableDescription() != null) {
        sql.SET("table_description = #{tableDescription,jdbcType=VARCHAR}");
        }
        if (record.getModuleName() != null) {
        sql.SET("module_name = #{moduleName,jdbcType=VARCHAR}");
        }
        if (record.getCreateMode() != null) {
            sql.SET("create_mode = #{createMode,jdbcType=VARCHAR}");
        }
        if (record.getModuleId() != null) {
        sql.SET("module_id = #{moduleId,jdbcType=BIGINT}");
        }
        if (record.getCreateTime() != null) {
        sql.SET("create_time = #{createTime,jdbcType=DATE}");
        }
        if (record.getCreatedBy() != null) {
        sql.SET("created_by = #{createdBy,jdbcType=BIGINT}");
        }
        if (record.getUpdateTime() != null) {
        sql.SET("update_time = #{updateTime,jdbcType=DATE}");
        }
        if (record.getUpdateBy() != null) {
        sql.SET("update_by = #{updateBy,jdbcType=BIGINT}");
        }
        if (record.getTenantId() != null) {
        sql.SET("tenant_id = #{tenantId,jdbcType=BIGINT}");
        }
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_customize_model");
        sql.SET("model_id = #{modelId,jdbcType=BIGINT}");
        sql.SET("model_type = #{modelType,jdbcType=VARCHAR}");
        sql.SET("model_name = #{modelName,jdbcType=VARCHAR}");
        sql.SET("model_identify = #{modelIdentify,jdbcType=VARCHAR}");
        sql.SET("table_name = #{tableName,jdbcType=VARCHAR}");
        sql.SET("table_id = #{tableId,jdbcType=BIGINT}");
        sql.SET("table_description = #{tableDescription,jdbcType=VARCHAR}");
        sql.SET("module_name = #{moduleName,jdbcType=VARCHAR}");
        sql.SET("module_id = #{moduleId,jdbcType=BIGINT}");
        sql.SET("create_time = #{createTime,jdbcType=DATE}");
        sql.SET("created_by = #{createdBy,jdbcType=BIGINT}");
        sql.SET("update_time = #{updateTime,jdbcType=DATE}");
        sql.SET("update_by = #{updateBy,jdbcType=BIGINT}");
        sql.SET("tenant_id = #{tenantId,jdbcType=BIGINT}");
        sql.SET("create_mode = #{createMode,jdbcType=BIGINT}");
        CscpCustomizeModelExample example = (CscpCustomizeModelExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model
     */
    public String updateByPrimaryKeySelective(CscpCustomizeModel record) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_customize_model");

        if (record.getModelType() != null) {
            sql.SET("model_type = #{modelType,jdbcType=VARCHAR}");
        }
        if (record.getModelName() != null) {
            sql.SET("model_name = #{modelName,jdbcType=VARCHAR}");
        }
        if (record.getModelIdentify() != null) {
            sql.SET("model_identify = #{modelIdentify,jdbcType=VARCHAR}");
        }
        if (record.getTableName() != null) {
            sql.SET("table_name = #{tableName,jdbcType=VARCHAR}");
        }
        if (record.getTableId() != null) {
            sql.SET("table_id = #{tableId,jdbcType=BIGINT}");
        }
        if (record.getTableDescription() != null) {
            sql.SET("table_description = #{tableDescription,jdbcType=VARCHAR}");
        }
        if (record.getModuleName() != null) {
            sql.SET("module_name = #{moduleName,jdbcType=VARCHAR}");
        }
        if (record.getModuleId() != null) {
            sql.SET("module_id = #{moduleId,jdbcType=BIGINT}");
        }
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=DATE}");
        }
        if (record.getCreatedBy() != null) {
            sql.SET("created_by = #{createdBy,jdbcType=BIGINT}");
        }
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=DATE}");
        }
        if (record.getUpdateBy() != null) {
            sql.SET("update_by = #{updateBy,jdbcType=BIGINT}");
        }
        if (record.getTenantId() != null) {
            sql.SET("tenant_id = #{tenantId,jdbcType=BIGINT}");
        }
        if (record.getCreateMode() != null) {
            sql.SET("create_mode = #{cretaMode,jdbcType=BIGINT}");
        }
        sql.WHERE("model_id = #{modelId,jdbcType=BIGINT}");

        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model
     */
    protected void applyWhere(SQL sql, CscpCustomizeModelExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1Th;
        String parmPhrase2;
        String parmPhrase2Th;
        String parmPhrase3;
        String parmPhrase3Th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1Th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2Th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3Th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}
