package com.ctsi.ssdc.customize.repository;

import com.ctsi.ssdc.customize.domain.CscpCustomizeModelType;
import com.ctsi.ssdc.customize.domain.CscpCustomizeModelTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

/**
 * CscpCustomizeModelTypeRepository
 *
 * @author hx
 * @date 2022-08-29 16:33:42
 */

@Mapper
public interface CscpCustomizeModelTypeRepository extends com.ctsi.ssdc.repository.BaseRepository<CscpCustomizeModelType, Long, CscpCustomizeModelTypeExample> {
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model_type
     *
     * @date 2022-08-29 16:33:42
     */
    @SelectProvider(type=CscpCustomizeModelTypeSqlProvider.class, method="countByExample")
    @Override
    long countByExample(CscpCustomizeModelTypeExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model_type
     *
     * @date 2022-08-29 16:33:42
     */
    @DeleteProvider(type=CscpCustomizeModelTypeSqlProvider.class, method="deleteByExample")
    @Override
    int deleteByExample(CscpCustomizeModelTypeExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model_type
     *
     * @date 2022-08-29 16:33:42
     */
    @Delete({
            "delete from cscp_customize_model_type",
            "where model_type_id = #{modelTypeId,jdbcType=BIGINT}"
    })
    @Override
    int deleteByPrimaryKey(Long modelTypeId);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model_type
     *
     *
     * @date 2022-08-29 16:33:42
     */
    @Insert({
            "insert into cscp_customize_model_type (",
            "model_type_id,",
            "model_type,",
            "model_name,",
            "create_time,",
            "created_by,",
            "update_time,",
            "update_by,",
            "tenant_id",
            ") values (",
            "#{modelTypeId,jdbcType=BIGINT}, ",
            "#{modelType,jdbcType=VARCHAR}, ",
            "#{modelName,jdbcType=VARCHAR}, ",
            "#{createTime,jdbcType=DATE}, ",
            "#{createdBy,jdbcType=BIGINT}, ",
            "#{updateTime,jdbcType=DATE}, ",
            "#{updateBy,jdbcType=BIGINT}, ",
            "#{tenantId,jdbcType=BIGINT}",

            ")"

    })
    @Override
    int insert(CscpCustomizeModelType record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model_type
     *
     * @date 2022-08-29 16:33:42
     */
    @InsertProvider(type=CscpCustomizeModelTypeSqlProvider.class, method="insertSelective")
    @Override
    int insertSelective(CscpCustomizeModelType record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model_type
     *
     * @date 2022-08-29 16:33:42
     */
    @SelectProvider(type=CscpCustomizeModelTypeSqlProvider.class, method="selectByExample")
    @Results({
            @Result(column="model_type_id", property="modelTypeId", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="model_type", property="modelType", jdbcType=JdbcType.VARCHAR),
            @Result(column="model_name", property="modelName", jdbcType=JdbcType.VARCHAR),
            @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
            @Result(column="created_by", property="createdBy", jdbcType=JdbcType.BIGINT),
            @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
            @Result(column="update_by", property="updateBy", jdbcType=JdbcType.BIGINT),
            @Result(column="tenant_id", property="tenantId", jdbcType=JdbcType.BIGINT)
    })

    @Override
    List<CscpCustomizeModelType> selectByExample(CscpCustomizeModelTypeExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model_type
     *
     * @date 2022-08-29 16:33:42
     */
    @Select({
            "select",
            "model_type_id,",
            "model_type,",
            "model_name,",
            "create_time,",
            "created_by,",
            "update_time,",
            "update_by,",
            "tenant_id",
            "from cscp_customize_model_type",
            "where model_type_id = #{modelTypeId,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column="model_type_id", property="modelTypeId", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="model_type", property="modelType", jdbcType=JdbcType.VARCHAR),
            @Result(column="model_name", property="modelName", jdbcType=JdbcType.VARCHAR),
            @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
            @Result(column="created_by", property="createdBy", jdbcType=JdbcType.BIGINT),
            @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
            @Result(column="update_by", property="updateBy", jdbcType=JdbcType.BIGINT),
            @Result(column="tenant_id", property="tenantId", jdbcType=JdbcType.BIGINT)
    })
    @Override
    CscpCustomizeModelType selectByPrimaryKey(Long modelTypeId);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model_type
     *
     * @date 2022-08-29 16:33:42
     */
    @UpdateProvider(type=CscpCustomizeModelTypeSqlProvider.class, method="updateByExampleSelective")
    @Override
    int updateByExampleSelective(@Param("record") CscpCustomizeModelType record, @Param("example") CscpCustomizeModelTypeExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model_type
     *
     * @date 2022-08-29 16:33:42
     */
    @UpdateProvider(type=CscpCustomizeModelTypeSqlProvider.class, method="updateByExample")
    @Override
    int updateByExample(@Param("record") CscpCustomizeModelType record, @Param("example") CscpCustomizeModelTypeExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model_type
     *
     *@date 2022-08-29 16:33:42
     */
    @UpdateProvider(type=CscpCustomizeModelTypeSqlProvider.class, method="updateByPrimaryKeySelective")
    @Override
    int updateByPrimaryKeySelective(CscpCustomizeModelType record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model_type
     *
     * @date 2022-08-29 16:33:42
     */
    @Update({
            "update cscp_customize_model_type",
            "set ",
            "model_type_id = #{modelTypeId,jdbcType=BIGINT},",
            "model_type = #{modelType,jdbcType=VARCHAR},",
            "model_name = #{modelName,jdbcType=VARCHAR},",
            "create_time = #{createTime,jdbcType=DATE},",
            "created_by = #{createdBy,jdbcType=BIGINT},",
            "update_time = #{updateTime,jdbcType=DATE},",
            "update_by = #{updateBy,jdbcType=BIGINT},",
            "tenant_id = #{tenantId,jdbcType=BIGINT}",

            "where model_type_id = #{modelTypeId,jdbcType=BIGINT}"
    })
    @Override
    int updateByPrimaryKey(CscpCustomizeModelType record);

    /**
     * 批量删除
     * @param modelTypeIds
     */
    @Delete("<script>" +
            "delete from cscp_customize_model_type where model_type_id in" +
            "<foreach collection=\"modelTypeIds\" item=\"modelTypeId\" open=\"(\" separator=\",\" close=\")\">" +
            "#{modelTypeId}" +
            "</foreach>" +
            "</script>")
    void deleteByIds(@Param("modelTypeIds") List<Long> modelTypeIds);


}





