package com.ctsi.ssdc.customize.repository;

import com.ctsi.ssdc.customize.domain.CscpCustomizeModel;
import com.ctsi.ssdc.customize.domain.CscpCustomizeModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

/**
 * CscpCustomizeModelRepository
 *
 * @author hx
 * @date 2022-08-31 09:40:19
 */

@Mapper
public interface CscpCustomizeModelRepository extends com.ctsi.ssdc.repository.BaseRepository<CscpCustomizeModel, Long, CscpCustomizeModelExample> {
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model
     *
     * @date 2022-08-31 09:40:19
     */
    @SelectProvider(type=CscpCustomizeModelSqlProvider.class, method="countByExample")
    @Override
    long countByExample(CscpCustomizeModelExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model
     *
     * @date 2022-08-31 09:40:19
     */
    @DeleteProvider(type=CscpCustomizeModelSqlProvider.class, method="deleteByExample")
    @Override
    int deleteByExample(CscpCustomizeModelExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model
     *
     * @date 2022-08-31 09:40:19
     */
    @Delete({
            "delete from cscp_customize_model",
            "where model_id = #{modelId,jdbcType=BIGINT}"
    })
    @Override
    int deleteByPrimaryKey(Long modelId);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model
     *
     *
     * @date 2022-08-31 09:40:19
     */
    @Insert({
            "insert into cscp_customize_model (",
            "model_id,",
            "model_type,",
            "model_name,",
            "model_identify,",
            "table_name,",
            "table_id,",
            "table_description,",
            "module_name,",
            "module_id,",
            "create_time,",
            "created_by,",
            "update_time,",
            "update_by,",
            "tenant_id,",
            "create_mode",
            ") values (",
            "#{modelId,jdbcType=BIGINT}, ",
            "#{modelType,jdbcType=VARCHAR}, ",
            "#{modelName,jdbcType=VARCHAR}, ",
            "#{modelIdentify,jdbcType=VARCHAR}, ",
            "#{tableName,jdbcType=VARCHAR}, ",
            "#{tableId,jdbcType=BIGINT}, ",
            "#{tableDescription,jdbcType=VARCHAR}, ",
            "#{moduleName,jdbcType=VARCHAR}, ",
            "#{moduleId,jdbcType=BIGINT}, ",
            "#{createTime,jdbcType=DATE}, ",
            "#{createdBy,jdbcType=BIGINT}, ",
            "#{updateTime,jdbcType=DATE}, ",
            "#{updateBy,jdbcType=BIGINT}, ",
            "#{tenantId,jdbcType=BIGINT},",
            "#{createMode,jdbcType=VARCHAR}",
            ")"

    })
    @Override
    int insert(CscpCustomizeModel record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model
     *
     * @date 2022-08-31 09:40:19
     */
    @InsertProvider(type=CscpCustomizeModelSqlProvider.class, method="insertSelective")
    @Override
    int insertSelective(CscpCustomizeModel record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model
     *
     * @date 2022-08-31 09:40:19
     */
    @SelectProvider(type=CscpCustomizeModelSqlProvider.class, method="selectByExample")
    @Results({
            @Result(column="model_id", property="modelId", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="model_type", property="modelType", jdbcType=JdbcType.VARCHAR),
            @Result(column="model_name", property="modelName", jdbcType=JdbcType.VARCHAR),
            @Result(column="model_identify", property="modelIdentify", jdbcType=JdbcType.VARCHAR),
            @Result(column="table_name", property="tableName", jdbcType=JdbcType.VARCHAR),
            @Result(column="table_id", property="tableId", jdbcType=JdbcType.BIGINT),
            @Result(column="table_description", property="tableDescription", jdbcType=JdbcType.VARCHAR),
            @Result(column="module_name", property="moduleName", jdbcType=JdbcType.VARCHAR),
            @Result(column="module_id", property="moduleId", jdbcType=JdbcType.BIGINT),
            @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
            @Result(column="created_by", property="createdBy", jdbcType=JdbcType.BIGINT),
            @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
            @Result(column="update_by", property="updateBy", jdbcType=JdbcType.BIGINT),
            @Result(column="create_mode", property="createMode", jdbcType=JdbcType.VARCHAR),
            @Result(column="tenant_id", property="tenantId", jdbcType=JdbcType.BIGINT)
    })

    @Override
    List<CscpCustomizeModel> selectByExample(CscpCustomizeModelExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model
     *
     * @date 2022-08-31 09:40:19
     */
    @Select({
            "select",
            "model_id,",
            "model_type,",
            "model_name,",
            "model_identify,",
            "table_name,",
            "table_id,",
            "table_description,",
            "module_name,",
            "module_id,",
            "create_time,",
            "created_by,",
            "update_time,",
            "update_by,",
            "create_mode,",
            "tenant_id",
            "from cscp_customize_model",
            "where model_id = #{modelId,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column="model_id", property="modelId", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="model_type", property="modelType", jdbcType=JdbcType.VARCHAR),
            @Result(column="model_name", property="modelName", jdbcType=JdbcType.VARCHAR),
            @Result(column="model_identify", property="modelIdentify", jdbcType=JdbcType.VARCHAR),
            @Result(column="table_name", property="tableName", jdbcType=JdbcType.VARCHAR),
            @Result(column="table_id", property="tableId", jdbcType=JdbcType.BIGINT),
            @Result(column="table_description", property="tableDescription", jdbcType=JdbcType.VARCHAR),
            @Result(column="module_name", property="moduleName", jdbcType=JdbcType.VARCHAR),
            @Result(column="module_id", property="moduleId", jdbcType=JdbcType.BIGINT),
            @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
            @Result(column="created_by", property="createdBy", jdbcType=JdbcType.BIGINT),
            @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
            @Result(column="update_by", property="updateBy", jdbcType=JdbcType.BIGINT),
            @Result(column="create_mode", property="createMode", jdbcType=JdbcType.VARCHAR),
            @Result(column="tenant_id", property="tenantId", jdbcType=JdbcType.BIGINT)
    })
    @Override
    CscpCustomizeModel selectByPrimaryKey(Long modelId);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model
     *
     * @date 2022-08-31 09:40:19
     */
    @UpdateProvider(type=CscpCustomizeModelSqlProvider.class, method="updateByExampleSelective")
    @Override
    int updateByExampleSelective(@Param("record") CscpCustomizeModel record, @Param("example") CscpCustomizeModelExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model
     *
     * @date 2022-08-31 09:40:19
     */
    @UpdateProvider(type=CscpCustomizeModelSqlProvider.class, method="updateByExample")
    @Override
    int updateByExample(@Param("record") CscpCustomizeModel record, @Param("example") CscpCustomizeModelExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model
     *
     *@date 2022-08-31 09:40:19
     */
    @UpdateProvider(type=CscpCustomizeModelSqlProvider.class, method="updateByPrimaryKeySelective")
    @Override
    int updateByPrimaryKeySelective(CscpCustomizeModel record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_model
     *
     * @date 2022-08-31 09:40:19
     */
    @Update({
            "update cscp_customize_model",
            "set ",
            "model_id = #{modelId,jdbcType=BIGINT},",
            "model_type = #{modelType,jdbcType=VARCHAR},",
            "model_name = #{modelName,jdbcType=VARCHAR},",
            "model_identify = #{modelIdentify,jdbcType=VARCHAR},",
            "table_name = #{tableName,jdbcType=VARCHAR},",
            "table_id = #{tableId,jdbcType=BIGINT},",
            "table_description = #{tableDescription,jdbcType=VARCHAR},",
            "module_name = #{moduleName,jdbcType=VARCHAR},",
            "module_id = #{moduleId,jdbcType=BIGINT},",
            "create_time = #{createTime,jdbcType=DATE},",
            "created_by = #{createdBy,jdbcType=BIGINT},",
            "update_time = #{updateTime,jdbcType=DATE},",
            "update_by = #{updateBy,jdbcType=BIGINT},",
            "tenant_id = #{tenantId,jdbcType=BIGINT}",

            "where model_id = #{modelId,jdbcType=BIGINT}"
    })
    @Override
    int updateByPrimaryKey(CscpCustomizeModel record);

    /**
     * 批量删除
     * @param modelIds
     */
    @Delete("<script>" +
            "delete from cscp_customize_model where model_id in" +
            "<foreach collection=\"modelIds\" item=\"modelId\" open=\"(\" separator=\",\" close=\")\">" +
            "#{modelId}" +
            "</foreach>" +
            "</script>")
    void deleteByIds(@Param("modelIds") List<Long> modelIds);

    @Select({
            "select",
            "model_id,",
            "model_type,",
            "model_name,",
            "model_identify,",
            "table_name,",
            "table_id,",
            "table_description,",
            "module_name,",
            "module_id,",
            "create_time,",
            "created_by,",
            "update_time,",
            "update_by,",
            "create_mode,",
            "tenant_id",
            "from cscp_customize_model",
            "where module_id = #{moduleId,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column="model_id", property="modelId", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="model_type", property="modelType", jdbcType=JdbcType.VARCHAR),
            @Result(column="model_name", property="modelName", jdbcType=JdbcType.VARCHAR),
            @Result(column="model_identify", property="modelIdentify", jdbcType=JdbcType.VARCHAR),
            @Result(column="table_name", property="tableName", jdbcType=JdbcType.VARCHAR),
            @Result(column="table_id", property="tableId", jdbcType=JdbcType.BIGINT),
            @Result(column="table_description", property="tableDescription", jdbcType=JdbcType.VARCHAR),
            @Result(column="module_name", property="moduleName", jdbcType=JdbcType.VARCHAR),
            @Result(column="module_id", property="moduleId", jdbcType=JdbcType.BIGINT),
            @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
            @Result(column="created_by", property="createdBy", jdbcType=JdbcType.BIGINT),
            @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
            @Result(column="update_by", property="updateBy", jdbcType=JdbcType.BIGINT),
            @Result(column="create_mode", property="createMode", jdbcType=JdbcType.VARCHAR),
            @Result(column="tenant_id", property="tenantId", jdbcType=JdbcType.BIGINT)
    })
    List<CscpCustomizeModel> selectByModuleId(@Param("moduleId") Long moduleId);

    @Select({
            "<script>",
            "select",
            "model_id,",
            "model_type,",
            "model_name,",
            "model_identify,",
            "table_name,",
            "table_id,",
            "table_description,",
            "module_name,",
            "module_id,",
            "create_time,",
            "created_by,",
            "update_time,",
            "update_by,",
            "create_mode,",
            "tenant_id ",
            "from cscp_customize_model ",
            "where module_id in ",
            "<foreach collection=\"moduleId\" item=\"moduleId\" open=\"(\" separator=\",\" close=\")\">" ,
            "#{moduleId} ",
            "</foreach>" ,
            "</script>"
    })
    @Results({
            @Result(column="model_id", property="modelId", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="model_type", property="modelType", jdbcType=JdbcType.VARCHAR),
            @Result(column="model_name", property="modelName", jdbcType=JdbcType.VARCHAR),
            @Result(column="model_identify", property="modelIdentify", jdbcType=JdbcType.VARCHAR),
            @Result(column="table_name", property="tableName", jdbcType=JdbcType.VARCHAR),
            @Result(column="table_id", property="tableId", jdbcType=JdbcType.BIGINT),
            @Result(column="table_description", property="tableDescription", jdbcType=JdbcType.VARCHAR),
            @Result(column="module_name", property="moduleName", jdbcType=JdbcType.VARCHAR),
            @Result(column="module_id", property="moduleId", jdbcType=JdbcType.BIGINT),
            @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
            @Result(column="created_by", property="createdBy", jdbcType=JdbcType.BIGINT),
            @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
            @Result(column="update_by", property="updateBy", jdbcType=JdbcType.BIGINT),
            @Result(column="create_mode", property="createMode", jdbcType=JdbcType.VARCHAR),
            @Result(column="tenant_id", property="tenantId", jdbcType=JdbcType.BIGINT)
    })
    List<CscpCustomizeModel> selectByModuleIds(@Param("moduleId") List<Long> moduleId);
}





