package com.ctsi.ssdc.customize.repository;

import com.ctsi.ssdc.customize.domain.CscpCustomizeVfieldPage;
import com.ctsi.ssdc.customize.domain.CscpCustomizeVfieldPageExample;
import com.ctsi.ssdc.gen.repository.CscpCustomizeVfieldSqlProvider;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

/**
 * CscpCustomizeVfieldRepository
 *
 * @author hx
 * @date 2022-06-01 16:21:03
 */

@Mapper
public interface CscpCustomizeVfieldPageRepository extends com.ctsi.ssdc.repository.BaseRepository<CscpCustomizeVfieldPage, Long, CscpCustomizeVfieldPageExample> {
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_vfield_page
     *
     * @date 2022-06-01 16:21:03
     */
    @SelectProvider(type= CscpCustomizeVfieldSqlProvider.class, method="countByExample")
    @Override
    long countByExample(CscpCustomizeVfieldPageExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_vfield_page
     *
     * @date 2022-06-01 16:21:03
     */
    @DeleteProvider(type=CscpCustomizeVfieldSqlProvider.class, method="deleteByExample")
    @Override
    int deleteByExample(CscpCustomizeVfieldPageExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_vfield_page
     *
     * @date 2022-06-01 16:21:03
     */
    @Delete({
            "delete from cscp_customize_vfield_page",
            "where field_id = #{fieldId,jdbcType=BIGINT}"
    })
    @Override
    int deleteByPrimaryKey(Long fieldId);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_vfield_page
     *
     *
     * @date 2022-06-01 16:21:03
     */
    @Insert({
            "insert into cscp_customize_vfield_page (",
            "field_id,",
            "page_id,",
            "field_name,",
            "field_comment,",
            "field_query,",
            "query_type,",
            "control_type,",
            "field_list,",
            "field_width,",
            "field_order,",
            "field_dic,",
            "field_options,",
            "is_form,",
            "component_type,",
            "tenant_id,",
            "created_time,",
            "created_by,",
            "update_time,",
            "update_by,",
            "del_flag,",
            "status,",
            "field_type",
            ") values (",
            "#{fieldId,jdbcType=BIGINT}, ",
            "#{pageId,jdbcType=BIGINT}, ",
            "#{fieldName,jdbcType=VARCHAR}, ",
            "#{fieldComment,jdbcType=VARCHAR}, ",
            "#{fieldQuery,jdbcType=VARCHAR}, ",
            "#{queryType,jdbcType=VARCHAR}, ",
            "#{controlType,jdbcType=VARCHAR}, ",
            "#{fieldList,jdbcType=VARCHAR}, ",
            "#{fieldWidth,jdbcType=DOUBLE}, ",
            "#{fieldOrder,jdbcType=INTEGER}, ",
            "#{fieldDic,jdbcType=VARCHAR}, ",
            "#{fieldOptions,jdbcType=VARCHAR}, ",
            "#{isForm,jdbcType=VARCHAR}, ",
            "#{componentType,jdbcType=VARCHAR}, ",
            "#{tenantId,jdbcType=BIGINT}, ",
            "#{createdTime,jdbcType=DATE}, ",
            "#{createdBy,jdbcType=BIGINT}, ",
            "#{updateTime,jdbcType=DATE}, ",
            "#{updateBy,jdbcType=BIGINT}, ",
            "#{delFlag,jdbcType=VARCHAR}, ",
            "#{status,jdbcType=VARCHAR}, ",
            "#{fieldType,jdbcType=INTEGER}",

            ")"

    })
    @Override
    int insert(CscpCustomizeVfieldPage record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_vfield_page
     *
     * @date 2022-06-01 16:21:03
     */
    @InsertProvider(type=CscpCustomizeVfieldSqlProvider.class, method="insertSelective")
    @Override
    int insertSelective(CscpCustomizeVfieldPage record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_vfield_page
     *
     * @date 2022-06-01 16:21:03
     */
    @SelectProvider(type=CscpCustomizeVfieldPageSqlProvider.class, method="selectByExample")
    @Results({
            @Result(column="field_id", property="fieldId", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="page_id", property="pageId", jdbcType=JdbcType.BIGINT),
            @Result(column="field_name", property="fieldName", jdbcType=JdbcType.VARCHAR),
            @Result(column="field_comment", property="fieldComment", jdbcType=JdbcType.VARCHAR),
            @Result(column="field_query", property="fieldQuery", jdbcType=JdbcType.VARCHAR),
            @Result(column="query_type", property="queryType", jdbcType=JdbcType.VARCHAR),
            @Result(column="control_type", property="controlType", jdbcType=JdbcType.VARCHAR),
            @Result(column="field_list", property="fieldList", jdbcType=JdbcType.VARCHAR),
            @Result(column="field_width", property="fieldWidth", jdbcType=JdbcType.DOUBLE),
            @Result(column="field_order", property="fieldOrder", jdbcType=JdbcType.INTEGER),
            @Result(column="field_dic", property="fieldDic", jdbcType=JdbcType.VARCHAR),
            @Result(column="field_options", property="fieldOptions", jdbcType=JdbcType.VARCHAR),
            @Result(column="tenant_id", property="tenantId", jdbcType=JdbcType.BIGINT),
            @Result(column="created_time", property="createdTime", jdbcType=JdbcType.DATE),
            @Result(column="created_by", property="createdBy", jdbcType=JdbcType.BIGINT),
            @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
            @Result(column="update_by", property="updateBy", jdbcType=JdbcType.BIGINT),
            @Result(column="del_flag", property="delFlag", jdbcType=JdbcType.VARCHAR),
            @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
            @Result(column="field_type", property="fieldType", jdbcType=JdbcType.INTEGER)
    })

    @Override
    List<CscpCustomizeVfieldPage> selectByExample(CscpCustomizeVfieldPageExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_vfield_page
     *
     * @date 2022-06-01 16:21:03
     */
    @Select({
            "select",
            "field_id,",
            "page_id,",
            "field_name,",
            "field_comment,",
            "field_query,",
            "query_type,",
            "control_type,",
            "field_list,",
            "field_width,",
            "field_order,",
            "field_dic,",
            "field_options,",
            "tenant_id,",
            "created_time,",
            "created_by,",
            "update_time,",
            "update_by,",
            "del_flag,",
            "status,",
            "field_type",
            "is_form",
            "component_type",
            "from cscp_customize_vfield_page",
            "where field_id = #{fieldId,jdbcType=BIGINT}"
    })
    @Results(id="fieldsMap",value = {
            @Result(column="field_id", property="fieldId", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="page_id", property="pageId", jdbcType=JdbcType.BIGINT),
            @Result(column="field_name", property="fieldName", jdbcType=JdbcType.VARCHAR),
            @Result(column="field_comment", property="fieldComment", jdbcType=JdbcType.VARCHAR),
            @Result(column="field_query", property="fieldQuery", jdbcType=JdbcType.VARCHAR),
            @Result(column="query_type", property="queryType", jdbcType=JdbcType.VARCHAR),
            @Result(column="control_type", property="controlType", jdbcType=JdbcType.VARCHAR),
            @Result(column="field_list", property="fieldList", jdbcType=JdbcType.VARCHAR),
            @Result(column="field_width", property="fieldWidth", jdbcType=JdbcType.DOUBLE),
            @Result(column="field_order", property="fieldOrder", jdbcType=JdbcType.INTEGER),
            @Result(column="field_dic", property="fieldDic", jdbcType=JdbcType.VARCHAR),
            @Result(column="field_options", property="fieldOptions", jdbcType=JdbcType.VARCHAR),
            @Result(column="tenant_id", property="tenantId", jdbcType=JdbcType.BIGINT),
            @Result(column="created_time", property="createdTime", jdbcType=JdbcType.DATE),
            @Result(column="created_by", property="createdBy", jdbcType=JdbcType.BIGINT),
            @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE),
            @Result(column="update_by", property="updateBy", jdbcType=JdbcType.BIGINT),
            @Result(column="del_flag", property="delFlag", jdbcType=JdbcType.VARCHAR),
            @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
            @Result(column="field_type", property="fieldType", jdbcType=JdbcType.INTEGER),
            @Result(column="is_form", property="isForm", jdbcType=JdbcType.VARCHAR),
            @Result(column="component_type", property="componentType", jdbcType=JdbcType.VARCHAR)
    })
    @Override
    CscpCustomizeVfieldPage selectByPrimaryKey(Long fieldId);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_vfield_page
     *
     * @date 2022-06-01 16:21:03
     */
    @UpdateProvider(type=CscpCustomizeVfieldPageSqlProvider.class, method="updateByExampleSelective")
    @Override
    int updateByExampleSelective(@Param("record") CscpCustomizeVfieldPage record, @Param("example") CscpCustomizeVfieldPageExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_vfield_page
     *
     * @date 2022-06-01 16:21:03
     */
    @UpdateProvider(type=CscpCustomizeVfieldPageSqlProvider.class, method="updateByExample")
    @Override
    int updateByExample(@Param("record") CscpCustomizeVfieldPage record, @Param("example") CscpCustomizeVfieldPageExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_vfield_page
     *
     *@date 2022-06-01 16:21:03
     */
    @UpdateProvider(type=CscpCustomizeVfieldPageSqlProvider.class, method="updateByPrimaryKeySelective")
    @Override
    int updateByPrimaryKeySelective(CscpCustomizeVfieldPage record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_customize_vfield_page
     *
     * @date 2022-06-01 16:21:03
     */
    @Update({
            "update cscp_customize_vfield_page",
            "set ",
            "field_id = #{fieldId,jdbcType=BIGINT},",
            "page_id = #{pageId,jdbcType=BIGINT},",
            "field_name = #{fieldName,jdbcType=VARCHAR},",
            "field_comment = #{fieldComment,jdbcType=VARCHAR},",
            "field_query = #{fieldQuery,jdbcType=VARCHAR},",
            "query_type = #{queryType,jdbcType=VARCHAR},",
            "control_type = #{controlType,jdbcType=VARCHAR},",
            "field_list = #{fieldList,jdbcType=VARCHAR},",
            "field_width = #{fieldWidth,jdbcType=DOUBLE},",
            "field_order = #{fieldOrder,jdbcType=INTEGER},",
            "field_dic = #{fieldDic,jdbcType=VARCHAR},",
            "field_options = #{fieldOptions,jdbcType=VARCHAR},",
            "is_form = #{isForm,jdbcType=VARCHAR},",
            "component_type = #{componentType,jdbcType=VARCHAR},",
            "tenant_id = #{tenantId,jdbcType=BIGINT},",
            "created_time = #{createdTime,jdbcType=DATE},",
            "created_by = #{createdBy,jdbcType=BIGINT},",
            "update_time = #{updateTime,jdbcType=DATE},",
            "update_by = #{updateBy,jdbcType=BIGINT},",
            "del_flag = #{delFlag,jdbcType=VARCHAR},",
            "status = #{status,jdbcType=VARCHAR},",
            "field_type = #{fieldType,jdbcType=INTEGER}",

            "where field_id = #{fieldId,jdbcType=BIGINT}"
    })
    @Override
    int updateByPrimaryKey(CscpCustomizeVfieldPage record);

    /**
     * 批量删除
     * @param fieldIds
     */
    @Delete("<script>" +
            "delete from cscp_customize_vfield_page where field_id in" +
            "<foreach collection=\"fieldIds\" item=\"fieldId\" open=\"(\" separator=\",\" close=\")\">" +
            "#{fieldId}" +
            "</foreach>" +
            "</script>")
    void deleteByIds(@Param("fieldIds") List<Long> fieldIds);

    /**
     * 根据pageId查询字段列表
     */

    @Select({"select * from cscp_customize_vfield_page where page_id = #{pageId} order by field_order"})
    @ResultMap(value = "fieldsMap")
    List<CscpCustomizeVfieldPage> getListByPageId(Long pageId);


    /**
     * 根据pageId查询字段列表
     */

    @Select({"<script>" +
            "select * from cscp_customize_vfield_page where page_id in " +
            "<foreach collection=\"pageIds\" item=\"pageId\" open=\"(\" separator=\",\" close=\")\">" +
            "#{pageId}" +
            "</foreach>" +
            " order by field_order " +
            "</script>"})
    @ResultMap(value = "fieldsMap")
    List<CscpCustomizeVfieldPage> getListByPageIds(@Param("pageIds") List<Long> pageIds);



    @Delete("delete from cscp_customize_vfield_page where page_id = #{pageId}")
    void deleteByPageId(Long pageId);


    /**
     * 批量删除
     * @param pageIds
     */
    @Delete("<script>" +
            "delete from cscp_customize_vfield_page where page_id in" +
            "<foreach collection=\"pageIds\" item=\"pageId\" open=\"(\" separator=\",\" close=\")\">" +
            "#{pageId}" +
            "</foreach>" +
            "</script>")
    void deleteByPageIdBatch(@Param("pageIds") List<Long> pageIds);
}





