package com.ctsi.ssdc.log.repository;

import com.ctsi.ssdc.log.domain.CscpComponentCallLog;
import com.ctsi.ssdc.log.domain.CscpComponentCallLogExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

/**
 * CscpComponentCallLogRepository
 *
 * @author hx
 * @date 2022-03-19 11:01:42
 */

@Mapper
public interface CscpComponentCallLogRepository extends com.ctsi.ssdc.repository.BaseRepository<CscpComponentCallLog, Long, CscpComponentCallLogExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_component_call_log
     *
     * @date 2022-03-19 11:01:42
     */
    @SelectProvider(type=CscpComponentCallLogSqlProvider.class, method="countByExample")
    @Override
    long countByExample(CscpComponentCallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_component_call_log
     *
     * @date 2022-03-19 11:01:42
     */
    @DeleteProvider(type=CscpComponentCallLogSqlProvider.class, method="deleteByExample")
    @Override
    int deleteByExample(CscpComponentCallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_component_call_log
     *
     * @date 2022-03-19 11:01:42
     */
    @Delete({
            "delete from cscp_component_call_log",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_component_call_log
     *
     *
     * @date 2022-03-19 11:01:42
     */
    @Insert({
            "insert into cscp_component_call_log (",
            "id,",
            "company,",
            "project_name,",
            "component_name,",
            "component_method_name,",
            "call_time,",
            "upload_flag",
            ") values (",
            "#{id,jdbcType=BIGINT}, ",
            "#{company,jdbcType=VARCHAR}, ",
            "#{projectName,jdbcType=VARCHAR}, ",
            "#{componentName,jdbcType=VARCHAR}, ",
            "#{componentMethodName,jdbcType=VARCHAR}, ",
            "#{callTime,jdbcType=DATE}, ",
            "#{uploadFlag,jdbcType=INTEGER}",

            ")"

    })
    @Override
    int insert(CscpComponentCallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_component_call_log
     *
     * @date 2022-03-19 11:01:42
     */
    @InsertProvider(type=CscpComponentCallLogSqlProvider.class, method="insertSelective")
    @Override
    int insertSelective(CscpComponentCallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_component_call_log
     *
     * @date 2022-03-19 11:01:42
     */
    @SelectProvider(type=CscpComponentCallLogSqlProvider.class, method="selectByExample")
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="company", property="company", jdbcType=JdbcType.VARCHAR),
            @Result(column="project_name", property="projectName", jdbcType=JdbcType.VARCHAR),
            @Result(column="component_name", property="componentName", jdbcType=JdbcType.VARCHAR),
            @Result(column="component_method_name", property="componentMethodName", jdbcType=JdbcType.VARCHAR),
            @Result(column="call_time", property="callTime", jdbcType=JdbcType.DATE),
            @Result(column="upload_flag", property="uploadFlag", jdbcType=JdbcType.INTEGER)
    })

    @Override
    List<CscpComponentCallLog> selectByExample(CscpComponentCallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_component_call_log
     *
     * @date 2022-03-19 11:01:42
     */
    @Select({
            "select",
            "id,",
            "company,",
            "project_name,",
            "component_name,",
            "component_method_name,",
            "call_time,",
            "upload_flag",
            "from cscp_component_call_log",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="company", property="company", jdbcType=JdbcType.VARCHAR),
            @Result(column="project_name", property="projectName", jdbcType=JdbcType.VARCHAR),
            @Result(column="component_name", property="componentName", jdbcType=JdbcType.VARCHAR),
            @Result(column="component_method_name", property="componentMethodName", jdbcType=JdbcType.VARCHAR),
            @Result(column="call_time", property="callTime", jdbcType=JdbcType.DATE),
            @Result(column="upload_flag", property="uploadFlag", jdbcType=JdbcType.INTEGER)
    })
    @Override
    CscpComponentCallLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_component_call_log
     *
     * @date 2022-03-19 11:01:42
     */
    @UpdateProvider(type=CscpComponentCallLogSqlProvider.class, method="updateByExampleSelective")
    @Override
    int updateByExampleSelective(@Param("record") CscpComponentCallLog record, @Param("example") CscpComponentCallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_component_call_log
     *
     * @date 2022-03-19 11:01:42
     */
    @UpdateProvider(type=CscpComponentCallLogSqlProvider.class, method="updateByExample")
    @Override
    int updateByExample(@Param("record") CscpComponentCallLog record, @Param("example") CscpComponentCallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_component_call_log
     *
     *@date 2022-03-19 11:01:42
     */
    @UpdateProvider(type=CscpComponentCallLogSqlProvider.class, method="updateByPrimaryKeySelective")
    @Override
    int updateByPrimaryKeySelective(CscpComponentCallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_component_call_log
     *
     * @date 2022-03-19 11:01:42
     */
    @Update({
            "update cscp_component_call_log",
            "set ",
            "id = #{id,jdbcType=BIGINT},",
            "company = #{company,jdbcType=VARCHAR},",
            "project_name = #{projectName,jdbcType=VARCHAR},",
            "component_name = #{componentName,jdbcType=VARCHAR},",
            "component_method_name = #{componentMethodName,jdbcType=VARCHAR},",
            "call_time = #{callTime,jdbcType=DATE},",
            "upload_flag = #{uploadFlag,jdbcType=INTEGER}",

            "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int updateByPrimaryKey(CscpComponentCallLog record);

    /**
     * 批量删除
     * @param ids
     */
    @Delete("<script>" +
            "delete from cscp_component_call_log where id in" +
            "<foreach collection=\"ids\" item=\"id\" open=\"(\" separator=\",\" close=\")\">" +
            "#{id}" +
            "</foreach>" +
            "</script>")
    void deleteByIds(@Param("ids") List<Long> ids);

    /**
     * 批量更新
     * @param ids
     */
    @Update("<script>" +
            "update cscp_component_call_log set upload_flag = 1  where id in" +
            "<foreach collection=\"ids\" item=\"id\" open=\"(\" separator=\",\" close=\")\">" +
            "#{id}" +
            "</foreach>" +
            "</script>")
    void updateByIds(@Param("ids") List<Long> ids);

    /**
     * 根据主键更新
     * @param id
     */
    @Update({
            "update cscp_component_call_log",
            "set ",
            "upload_flag = 1",
            "where id = #{id,jdbcType=BIGINT}"
    })
    void updateById(Long id);
}





