package com.ctsi.monitor.repository;

import com.ctsi.monitor.domain.MonitorJvm;
import com.ctsi.monitor.domain.MonitorMem;
import com.ctsi.monitor.domain.MonitorMemExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

/**
 * MonitorMemRepository
 *
 * @author hx
 * @date 2022-05-27 14:01:32
 */

@Mapper
public interface MonitorMemRepository extends com.ctsi.ssdc.repository.BaseRepository<MonitorMem, Long, MonitorMemExample> {
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_mem
     *
     * @date 2022-05-27 14:01:32
     */
    @SelectProvider(type=MonitorMemSqlProvider.class, method="countByExample")
    @Override
    long countByExample(MonitorMemExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_mem
     *
     * @date 2022-05-27 14:01:32
     */
    @DeleteProvider(type=MonitorMemSqlProvider.class, method="deleteByExample")
    @Override
    int deleteByExample(MonitorMemExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_mem
     *
     * @date 2022-05-27 14:01:32
     */
    @Delete({
            "delete from monitor_mem",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_mem
     *
     *
     * @date 2022-05-27 14:01:32
     */
    @Insert({
            "insert into monitor_mem (",
            "id,",
            "total,",
            "used,",
            "free,",
            "usages,",
            "time",
            ") values (",
            "#{id,jdbcType=BIGINT}, ",
            "#{total,jdbcType=DOUBLE}, ",
            "#{used,jdbcType=DOUBLE}, ",
            "#{free,jdbcType=DOUBLE}, ",
            "#{usages,jdbcType=DOUBLE}, ",
            "#{time,jdbcType=DATE}",

            ")"

    })
    @Override
    int insert(MonitorMem record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_mem
     *
     * @date 2022-05-27 14:01:32
     */
    @InsertProvider(type=MonitorMemSqlProvider.class, method="insertSelective")
    @Override
    int insertSelective(MonitorMem record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_mem
     *
     * @date 2022-05-27 14:01:32
     */
    @SelectProvider(type=MonitorMemSqlProvider.class, method="selectByExample")
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="total", property="total", jdbcType=JdbcType.DOUBLE),
            @Result(column="used", property="used", jdbcType=JdbcType.DOUBLE),
            @Result(column="free", property="free", jdbcType=JdbcType.DOUBLE),
            @Result(column="usages", property="usages", jdbcType=JdbcType.DOUBLE),
            @Result(column="time", property="time", jdbcType=JdbcType.DATE)
    })

    @Override
    List<MonitorMem> selectByExample(MonitorMemExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_mem
     *
     * @date 2022-05-27 14:01:32
     */
    @Select({
            "select",
            "id,",
            "total,",
            "used,",
            "free,",
            "usages,",
            "time",
            "from monitor_mem",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="total", property="total", jdbcType=JdbcType.DOUBLE),
            @Result(column="used", property="used", jdbcType=JdbcType.DOUBLE),
            @Result(column="free", property="free", jdbcType=JdbcType.DOUBLE),
            @Result(column="usages", property="usages", jdbcType=JdbcType.DOUBLE),
            @Result(column="time", property="time", jdbcType=JdbcType.DATE)
    })
    @Override
    MonitorMem selectByPrimaryKey(Long id);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_mem
     *
     * @date 2022-05-27 14:01:32
     */
    @UpdateProvider(type=MonitorMemSqlProvider.class, method="updateByExampleSelective")
    @Override
    int updateByExampleSelective(@Param("record") MonitorMem record, @Param("example") MonitorMemExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_mem
     *
     * @date 2022-05-27 14:01:32
     */
    @UpdateProvider(type=MonitorMemSqlProvider.class, method="updateByExample")
    @Override
    int updateByExample(@Param("record") MonitorMem record, @Param("example") MonitorMemExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_mem
     *
     *@date 2022-05-27 14:01:32
     */
    @UpdateProvider(type=MonitorMemSqlProvider.class, method="updateByPrimaryKeySelective")
    @Override
    int updateByPrimaryKeySelective(MonitorMem record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_mem
     *
     * @date 2022-05-27 14:01:32
     */
    @Update({
            "update monitor_mem",
            "set ",
            "id = #{id,jdbcType=BIGINT},",
            "total = #{total,jdbcType=DOUBLE},",
            "used = #{used,jdbcType=DOUBLE},",
            "free = #{free,jdbcType=DOUBLE},",
            "usages = #{usages,jdbcType=DOUBLE},",
            "time = #{time,jdbcType=DATE}",

            "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int updateByPrimaryKey(MonitorMem record);

    /**
     * 批量删除
     * @param ids
     */
    @Delete("<script>" +
            "delete from monitor_mem where id in" +
            "<foreach collection=\"ids\" item=\"id\" open=\"(\" separator=\",\" close=\")\">" +
            "#{id}" +
            "</foreach>" +
            "</script>")
    void deleteByIds(@Param("ids") List<Long> ids);

    /**
     * 根据时间查询
     * @param startTime
     * @param endTime
     * */
    @Select({
            "select",
            "total,",
            "used,",
            "free,",
            "usages,",
            "time ",
            "from monitor_mem",
            "where time between #{startTime} and #{endTime} "
    })
    List<MonitorMem> selectByTime(@Param("startTime") Date startTime, @Param("endTime") Date endTime);

    /**
     * 根据时间查询
     *
     * */
    @Select({
            "select",
            "total,",
            "used,",
            "free,",
            "usages,",
            "time ",
            "from monitor_mem",
            " order by time desc limit 10"
    })
    List<MonitorMem> getMsgUp10();




    /***
     * 清空表数据（定时任务使用）
     */
    @Update({" Truncate table monitor_mem "})
    void truncateMem();

}





