package com.ctsi.monitor.repository;

import com.ctsi.monitor.domain.MonitorMem;
import com.ctsi.monitor.domain.MonitorMemExample.Criteria;
import com.ctsi.monitor.domain.MonitorMemExample.Criterion;
import com.ctsi.monitor.domain.MonitorMemExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;


/**
 * MonitorMemSqlProvider
 *
 * @author hx
 * @date 2022-05-27 14:01:32
*/

public class MonitorMemSqlProvider {

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_mem
     */
    public String countByExample(MonitorMemExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("monitor_mem");
        applyWhere(sql, example, false);
        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_mem
     */
    public String deleteByExample(MonitorMemExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("monitor_mem");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_mem
     */
    public String insertSelective(MonitorMem record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("monitor_mem");

        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        if (record.getTotal() != null) {
            sql.VALUES("total", "#{total,jdbcType=DOUBLE}");
        }
        if (record.getUsed() != null) {
            sql.VALUES("used", "#{used,jdbcType=DOUBLE}");
        }
        if (record.getFree() != null) {
            sql.VALUES("free", "#{free,jdbcType=DOUBLE}");
        }
        if (record.getUsages() != null) {
            sql.VALUES("usages", "#{usages,jdbcType=DOUBLE}");
        }
        if (record.getTime() != null) {
            sql.VALUES("time", "#{time,jdbcType=DATE}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_mem
     */
    public String selectByExample(MonitorMemExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("total");
        sql.SELECT("used");
        sql.SELECT("free");
        sql.SELECT("usages");
        sql.SELECT("time");
        sql.FROM("monitor_mem");
        applyWhere(sql, example, false);

        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_mem
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        MonitorMem record = (MonitorMem) parameter.get("record");
        MonitorMemExample example = (MonitorMemExample) parameter.get("example");

        SQL sql = new SQL();
        sql.UPDATE("monitor_mem");

        if (record.getId() != null) {
        sql.SET("id = #{id,jdbcType=BIGINT}");
        }
        if (record.getTotal() != null) {
        sql.SET("total = #{total,jdbcType=DOUBLE}");
        }
        if (record.getUsed() != null) {
        sql.SET("used = #{used,jdbcType=DOUBLE}");
        }
        if (record.getFree() != null) {
        sql.SET("free = #{free,jdbcType=DOUBLE}");
        }
        if (record.getUsages() != null) {
        sql.SET("usages = #{usages,jdbcType=DOUBLE}");
        }
        if (record.getTime() != null) {
        sql.SET("time = #{time,jdbcType=DATE}");
        }
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_mem
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("monitor_mem");
        sql.SET("id = #{id,jdbcType=BIGINT}");
        sql.SET("total = #{total,jdbcType=DOUBLE}");
        sql.SET("used = #{used,jdbcType=DOUBLE}");
        sql.SET("free = #{free,jdbcType=DOUBLE}");
        sql.SET("usages = #{usages,jdbcType=DOUBLE}");
        sql.SET("time = #{time,jdbcType=DATE}");

        MonitorMemExample example = (MonitorMemExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_mem
     */
    public String updateByPrimaryKeySelective(MonitorMem record) {
        SQL sql = new SQL();
        sql.UPDATE("monitor_mem");

        if (record.getTotal() != null) {
            sql.SET("total = #{total,jdbcType=DOUBLE}");
        }
        if (record.getUsed() != null) {
            sql.SET("used = #{used,jdbcType=DOUBLE}");
        }
        if (record.getFree() != null) {
            sql.SET("free = #{free,jdbcType=DOUBLE}");
        }
        if (record.getUsages() != null) {
            sql.SET("usages = #{usages,jdbcType=DOUBLE}");
        }
        if (record.getTime() != null) {
            sql.SET("time = #{time,jdbcType=DATE}");
        }
        sql.WHERE("id = #{id,jdbcType=BIGINT}");

        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_mem
     */
    protected void applyWhere(SQL sql, MonitorMemExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1Th;
        String parmPhrase2;
        String parmPhrase2Th;
        String parmPhrase3;
        String parmPhrase3Th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1Th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2Th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3Th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}
