package com.ctsi.monitor.repository;

import com.ctsi.monitor.domain.MonitorCpu;
import com.ctsi.monitor.domain.MonitorCpuExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

/**
 * MonitorCpuRepository
 *
 * @author hx
 * @date 2022-05-27 11:21:43
 */

@Mapper
public interface MonitorCpuRepository extends com.ctsi.ssdc.repository.BaseRepository<MonitorCpu, Long, MonitorCpuExample> {
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_cpu
     *
     * @date 2022-05-27 11:21:43
     */
    @SelectProvider(type=MonitorCpuSqlProvider.class, method="countByExample")
    @Override
    long countByExample(MonitorCpuExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_cpu
     *
     * @date 2022-05-27 11:21:43
     */
    @DeleteProvider(type=MonitorCpuSqlProvider.class, method="deleteByExample")
    @Override
    int deleteByExample(MonitorCpuExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_cpu
     *
     * @date 2022-05-27 11:21:43
     */
    @Delete({
            "delete from monitor_cpu",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_cpu
     *
     *
     * @date 2022-05-27 11:21:43
     */
    @Insert({
            "insert into monitor_cpu (",
            "id,",
            "cpuNum,",
            "total,",
            "sys,",
            "used,",
            "wait,",
            "free,",
            "usages,",
            "time",
            ") values (",
            "#{id,jdbcType=BIGINT}, ",
            "#{cpunum,jdbcType=INTEGER}, ",
            "#{total,jdbcType=DECIMAL}, ",
            "#{sys,jdbcType=DECIMAL}, ",
            "#{used,jdbcType=DECIMAL}, ",
            "#{wait,jdbcType=DECIMAL}, ",
            "#{free,jdbcType=DECIMAL}, ",
            "#{usages,jdbcType=DECIMAL}, ",
            "#{time,jdbcType=DATE}",

            ")"

    })
    @Override
    int insert(MonitorCpu record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_cpu
     *
     * @date 2022-05-27 11:21:43
     */
    @InsertProvider(type=MonitorCpuSqlProvider.class, method="insertSelective")
    @Override
    int insertSelective(MonitorCpu record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_cpu
     *
     * @date 2022-05-27 11:21:43
     */
    @SelectProvider(type=MonitorCpuSqlProvider.class, method="selectByExample")
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="cpuNum", property="cpunum", jdbcType=JdbcType.INTEGER),
            @Result(column="total", property="total", jdbcType=JdbcType.DECIMAL),
            @Result(column="sys", property="sys", jdbcType=JdbcType.DECIMAL),
            @Result(column="used", property="used", jdbcType=JdbcType.DECIMAL),
            @Result(column="wait", property="wait", jdbcType=JdbcType.DECIMAL),
            @Result(column="free", property="free", jdbcType=JdbcType.DECIMAL),
            @Result(column="usages", property="usages", jdbcType=JdbcType.DECIMAL),
            @Result(column="time", property="time", jdbcType=JdbcType.DATE)
    })

    @Override
    List<MonitorCpu> selectByExample(MonitorCpuExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_cpu
     *
     * @date 2022-05-27 11:21:43
     */
    @Select({
            "select",
            "id,",
            "cpuNum,",
            "total,",
            "sys,",
            "used,",
            "wait,",
            "free,",
            "usages,",
            "time",
            "from monitor_cpu",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="cpuNum", property="cpunum", jdbcType=JdbcType.INTEGER),
            @Result(column="total", property="total", jdbcType=JdbcType.DECIMAL),
            @Result(column="sys", property="sys", jdbcType=JdbcType.DECIMAL),
            @Result(column="used", property="used", jdbcType=JdbcType.DECIMAL),
            @Result(column="wait", property="wait", jdbcType=JdbcType.DECIMAL),
            @Result(column="free", property="free", jdbcType=JdbcType.DECIMAL),
            @Result(column="usages", property="usages", jdbcType=JdbcType.DECIMAL),
            @Result(column="time", property="time", jdbcType=JdbcType.DATE)
    })
    @Override
    MonitorCpu selectByPrimaryKey(Long id);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_cpu
     *
     * @date 2022-05-27 11:21:43
     */
    @UpdateProvider(type=MonitorCpuSqlProvider.class, method="updateByExampleSelective")
    @Override
    int updateByExampleSelective(@Param("record") MonitorCpu record, @Param("example") MonitorCpuExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_cpu
     *
     * @date 2022-05-27 11:21:43
     */
    @UpdateProvider(type=MonitorCpuSqlProvider.class, method="updateByExample")
    @Override
    int updateByExample(@Param("record") MonitorCpu record, @Param("example") MonitorCpuExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_cpu
     *
     *@date 2022-05-27 11:21:43
     */
    @UpdateProvider(type=MonitorCpuSqlProvider.class, method="updateByPrimaryKeySelective")
    @Override
    int updateByPrimaryKeySelective(MonitorCpu record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table monitor_cpu
     *
     * @date 2022-05-27 11:21:43
     */
    @Update({
            "update monitor_cpu",
            "set ",
            "id = #{id,jdbcType=BIGINT},",
            "cpuNum = #{cpunum,jdbcType=INTEGER},",
            "total = #{total,jdbcType=DECIMAL},",
            "sys = #{sys,jdbcType=DECIMAL},",
            "used = #{used,jdbcType=DECIMAL},",
            "wait = #{wait,jdbcType=DECIMAL},",
            "free = #{free,jdbcType=DECIMAL},",
            "usages = #{usages,jdbcType=DECIMAL},",
            "time = #{time,jdbcType=DATE}",

            "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int updateByPrimaryKey(MonitorCpu record);

    /**
     * 批量删除
     * @param ids
     */
    @Delete("<script>" +
            "delete from monitor_cpu where id in" +
            "<foreach collection=\"ids\" item=\"id\" open=\"(\" separator=\",\" close=\")\">" +
            "#{id}" +
            "</foreach>" +
            "</script>")
    void deleteByIds(@Param("ids") List<Long> ids);

    /**
     * 根据时间查询
     * @param startTime
     * @param endTime
     * */
    @Select({
            "select",
            "cpunum,",
            "total,",
            "sys,",
            "used,",
            "wait,",
            "free,",
            "usages,",
            "time ",
            "from monitor_cpu",
            "where time between #{startTime} and #{endTime} "
    })
    List<MonitorCpu> selectByTime(@Param("startTime") Date startTime, @Param("endTime") Date endTime);



    /**
     * 根据时间查询
     * @param startTime
     * @param endTime
     * */
    @Select({
            "select",
            "cpunum,",
            "total,",
            "sys,",
            "used,",
            "wait,",
            "free,",
            "usages,",
            "time ",
            "from monitor_cpu",
            "order by time desc limit 10 "
    })
    List<MonitorCpu> getMsgUp10();

    /***
     * 清空表数据（定时任务使用）
     */
    @Update({" Truncate table monitor_cpu "})
    void truncateCpu();
}





