package com.ctsi.flow.multi.repository;

import com.ctsi.flow.multi.domain.CscpFlowTaskMultiRule;
import com.ctsi.flow.multi.domain.CscpFlowTaskMultiRuleExample.Criteria;
import com.ctsi.flow.multi.domain.CscpFlowTaskMultiRuleExample.Criterion;
import com.ctsi.flow.multi.domain.CscpFlowTaskMultiRuleExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;


/**
 * CscpFlowTaskMultiRuleSqlProvider
 *
 * @author hx
 * @date 2022-12-01 15:33:44
 */

public class CscpFlowTaskMultiRuleSqlProvider {

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_multi_rule
     */
    public String countByExample(CscpFlowTaskMultiRuleExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("cscp_flow_task_multi_rule");
        applyWhere(sql, example, false);
        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_multi_rule
     */
    public String deleteByExample(CscpFlowTaskMultiRuleExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("cscp_flow_task_multi_rule");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_multi_rule
     */
    public String insertSelective(CscpFlowTaskMultiRule record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("cscp_flow_task_multi_rule");

        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        if (record.getTaskDefinitionKey() != null) {
            sql.VALUES("task_definition_key", "#{taskDefinitionKey,jdbcType=VARCHAR}");
        }
        if (record.getTaskMulti() != null) {
            sql.VALUES("task_multi", "#{taskMulti,jdbcType=VARCHAR}");
        }
        if (record.getScheme() != null) {
            sql.VALUES("scheme", "#{scheme,jdbcType=INTEGER}");
        }
        if (record.getCreator() != null) {
            sql.VALUES("creator", "#{creator,jdbcType=VARCHAR}");
        }
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=DATE}");
        }
        if (record.getUpdater() != null) {
            sql.VALUES("updater", "#{updater,jdbcType=VARCHAR}");
        }
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=DATE}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_multi_rule
     */
    public String selectByExample(CscpFlowTaskMultiRuleExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("task_definition_key");
        sql.SELECT("task_multi");
        sql.SELECT("scheme");
        sql.SELECT("creator");
        sql.SELECT("create_time");
        sql.SELECT("updater");
        sql.SELECT("update_time");
        sql.FROM("cscp_flow_task_multi_rule");
        applyWhere(sql, example, false);

        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_multi_rule
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CscpFlowTaskMultiRule record = (CscpFlowTaskMultiRule) parameter.get("record");
        CscpFlowTaskMultiRuleExample example = (CscpFlowTaskMultiRuleExample) parameter.get("example");

        SQL sql = new SQL();
        sql.UPDATE("cscp_flow_task_multi_rule");

        if (record.getId() != null) {
            sql.SET("id = #{id,jdbcType=BIGINT}");
        }
        if (record.getTaskDefinitionKey() != null) {
            sql.SET("task_definition_key = #{taskDefinitionKey,jdbcType=VARCHAR}");
        }
        if (record.getTaskMulti() != null) {
            sql.SET("task_multi = #{taskMulti,jdbcType=VARCHAR}");
        }
        if (record.getScheme() != null) {
            sql.SET("scheme = #{scheme,jdbcType=INTEGER}");
        }
        if (record.getCreator() != null) {
            sql.SET("creator = #{creator,jdbcType=VARCHAR}");
        }
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=DATE}");
        }
        if (record.getUpdater() != null) {
            sql.SET("updater = #{updater,jdbcType=VARCHAR}");
        }
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=DATE}");
        }
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_multi_rule
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_flow_task_multi_rule");
        sql.SET("id = #{id,jdbcType=BIGINT}");
        sql.SET("task_definition_key = #{taskDefinitionKey,jdbcType=VARCHAR}");
        sql.SET("task_multi = #{taskMulti,jdbcType=VARCHAR}");
        sql.SET("scheme = #{scheme,jdbcType=INTEGER}");
        sql.SET("creator = #{creator,jdbcType=VARCHAR}");
        sql.SET("create_time = #{createTime,jdbcType=DATE}");
        sql.SET("updater = #{updater,jdbcType=VARCHAR}");
        sql.SET("update_time = #{updateTime,jdbcType=DATE}");

        CscpFlowTaskMultiRuleExample example = (CscpFlowTaskMultiRuleExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_multi_rule
     */
    public String updateByPrimaryKeySelective(CscpFlowTaskMultiRule record) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_flow_task_multi_rule");

        if (record.getTaskDefinitionKey() != null) {
            sql.SET("task_definition_key = #{taskDefinitionKey,jdbcType=VARCHAR}");
        }
        if (record.getTaskMulti() != null) {
            sql.SET("task_multi = #{taskMulti,jdbcType=VARCHAR}");
        }
        if (record.getScheme() != null) {
            sql.SET("scheme = #{scheme,jdbcType=INTEGER}");
        }
        if (record.getCreator() != null) {
            sql.SET("creator = #{creator,jdbcType=VARCHAR}");
        }
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=DATE}");
        }
        if (record.getUpdater() != null) {
            sql.SET("updater = #{updater,jdbcType=VARCHAR}");
        }
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=DATE}");
        }
        sql.WHERE("id = #{id,jdbcType=BIGINT}");

        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_multi_rule
     */
    protected void applyWhere(SQL sql, CscpFlowTaskMultiRuleExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1Th;
        String parmPhrase2;
        String parmPhrase2Th;
        String parmPhrase3;
        String parmPhrase3Th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1Th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2Th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3Th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}
