package com.ctsi.flow.multi.repository;

import com.ctsi.flow.multi.domain.CscpFlowTaskMultiRule;
import com.ctsi.flow.multi.domain.CscpFlowTaskMultiRuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

/**
 * CscpFlowTaskMultiRuleRepository
 *
 * @author hx
 * @date 2022-10-24 16:49:41
 */

@Mapper
public interface CscpFlowTaskMultiRuleRepository extends com.ctsi.ssdc.repository.BaseRepository<CscpFlowTaskMultiRule, Long, CscpFlowTaskMultiRuleExample> {
    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_multi_rule
     *
     * @date 2022-12-01 15:33:44
     */
    @SelectProvider(type=CscpFlowTaskMultiRuleSqlProvider.class, method="countByExample")
    @Override
    long countByExample(CscpFlowTaskMultiRuleExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_multi_rule
     *
     * @date 2022-12-01 15:33:44
     */
    @DeleteProvider(type=CscpFlowTaskMultiRuleSqlProvider.class, method="deleteByExample")
    @Override
    int deleteByExample(CscpFlowTaskMultiRuleExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_multi_rule
     *
     * @date 2022-12-01 15:33:44
     */
    @Delete({
            "delete from cscp_flow_task_multi_rule",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_multi_rule
     *
     *
     * @date 2022-12-01 15:33:44
     */
    @Insert({
            "insert into cscp_flow_task_multi_rule (",
            "id,",
            "task_definition_key,",
            "task_multi,",
            "scheme,",
            "creator,",
            "create_time,",
            "updater,",
            "update_time",
            ") values (",
            "#{id,jdbcType=BIGINT}, ",
            "#{taskDefinitionKey,jdbcType=VARCHAR}, ",
            "#{taskMulti,jdbcType=VARCHAR}, ",
            "#{scheme,jdbcType=INTEGER}, ",
            "#{creator,jdbcType=VARCHAR}, ",
            "#{createTime,jdbcType=DATE}, ",
            "#{updater,jdbcType=VARCHAR}, ",
            "#{updateTime,jdbcType=DATE}",

            ")"

    })
    @Override
    int insert(CscpFlowTaskMultiRule record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_multi_rule
     *
     * @date 2022-12-01 15:33:44
     */
    @InsertProvider(type=CscpFlowTaskMultiRuleSqlProvider.class, method="insertSelective")
    @Override
    int insertSelective(CscpFlowTaskMultiRule record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_multi_rule
     *
     * @date 2022-12-01 15:33:44
     */
    @SelectProvider(type=CscpFlowTaskMultiRuleSqlProvider.class, method="selectByExample")
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="task_definition_key", property="taskDefinitionKey", jdbcType=JdbcType.VARCHAR),
            @Result(column="task_multi", property="taskMulti", jdbcType=JdbcType.VARCHAR),
            @Result(column="scheme", property="scheme", jdbcType=JdbcType.INTEGER),
            @Result(column="creator", property="creator", jdbcType=JdbcType.VARCHAR),
            @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
            @Result(column="updater", property="updater", jdbcType=JdbcType.VARCHAR),
            @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE)
    })

    @Override
    List<CscpFlowTaskMultiRule> selectByExample(CscpFlowTaskMultiRuleExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_multi_rule
     *
     * @date 2022-12-01 15:33:44
     */
    @Select({
            "select",
            "id,",
            "task_definition_key,",
            "task_multi,",
            "scheme,",
            "creator,",
            "create_time,",
            "updater,",
            "update_time",
            "from cscp_flow_task_multi_rule",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.BIGINT,id=true ),
            @Result(column="task_definition_key", property="taskDefinitionKey", jdbcType=JdbcType.VARCHAR),
            @Result(column="task_multi", property="taskMulti", jdbcType=JdbcType.VARCHAR),
            @Result(column="scheme", property="scheme", jdbcType=JdbcType.INTEGER),
            @Result(column="creator", property="creator", jdbcType=JdbcType.VARCHAR),
            @Result(column="create_time", property="createTime", jdbcType=JdbcType.DATE),
            @Result(column="updater", property="updater", jdbcType=JdbcType.VARCHAR),
            @Result(column="update_time", property="updateTime", jdbcType=JdbcType.DATE)
    })
    @Override
    CscpFlowTaskMultiRule selectByPrimaryKey(Long id);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_multi_rule
     *
     * @date 2022-12-01 15:33:44
     */
    @UpdateProvider(type=CscpFlowTaskMultiRuleSqlProvider.class, method="updateByExampleSelective")
    @Override
    int updateByExampleSelective(@Param("record") CscpFlowTaskMultiRule record, @Param("example") CscpFlowTaskMultiRuleExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_multi_rule
     *
     * @date 2022-12-01 15:33:44
     */
    @UpdateProvider(type=CscpFlowTaskMultiRuleSqlProvider.class, method="updateByExample")
    @Override
    int updateByExample(@Param("record") CscpFlowTaskMultiRule record, @Param("example") CscpFlowTaskMultiRuleExample example);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_multi_rule
     *
     *@date 2022-12-01 15:33:44
     */
    @UpdateProvider(type=CscpFlowTaskMultiRuleSqlProvider.class, method="updateByPrimaryKeySelective")
    @Override
    int updateByPrimaryKeySelective(CscpFlowTaskMultiRule record);

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_flow_task_multi_rule
     *
     * @date 2022-12-01 15:33:44
     */
    @Update({
            "update cscp_flow_task_multi_rule",
            "set ",
            "id = #{id,jdbcType=BIGINT},",
            "task_definition_key = #{taskDefinitionKey,jdbcType=VARCHAR},",
            "task_multi = #{taskMulti,jdbcType=VARCHAR},",
            "scheme = #{scheme,jdbcType=INTEGER},",
            "creator = #{creator,jdbcType=VARCHAR},",
            "create_time = #{createTime,jdbcType=DATE},",
            "updater = #{updater,jdbcType=VARCHAR},",
            "update_time = #{updateTime,jdbcType=DATE}",

            "where id = #{id,jdbcType=BIGINT}"
    })
    @Override
    int updateByPrimaryKey(CscpFlowTaskMultiRule record);

    /**
     * 批量删除
     * @param ids
     */
    @Delete("<script>" +
            "delete from cscp_flow_task_multi_rule where id in" +
            "<foreach collection=\"ids\" item=\"id\" open=\"(\" separator=\",\" close=\")\">" +
            "#{id}" +
            "</foreach>" +
            "</script>")
    void deleteByIds(@Param("ids") List<Long> ids);


    /**
     * 按key删除
     * @param taskKey
     */
    @Delete({
            "delete from cscp_flow_task_multi_rule",
            "where task_definition_key = #{taskKey,jdbcType=VARCHAR}"
    })
    void deleteMultiByKey(@Param("taskKey") String taskKey);

    /**
     * 按key修改
     * @param record
     */
    @Update({"<script>" +
            "update cscp_flow_task_multi_rule "+
            "set "+
            "<if test='taskMulti != null and taskMulti != \"\"'>task_multi = #{taskMulti},</if>"+
            "scheme = #{scheme,jdbcType=INTEGER} "+
            "where task_definition_key = #{taskDefinitionKey,jdbcType=VARCHAR}"+
            "</script>"})
    int updateByKey(CscpFlowTaskMultiRule record);

}





