package com.ctsi.ssdc.dic.domain;

import com.ctsi.ssdc.criteria.IntegerCriteria;
import com.ctsi.ssdc.criteria.LongCriteria;
import com.ctsi.ssdc.criteria.StringCriteria;
import com.ctsi.ssdc.example.BaseExample;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.annotations.ApiParam;
import java.util.ArrayList;
import java.util.List;
import org.apache.commons.lang3.StringUtils;

/**
 * @author ctsi-biyi-generator
*/
public class CscpHxDicItemExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    private static final String LIKE_FORMAT = "%%%s%%";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_hx_dic_item.item_id
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    private LongCriteria itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_hx_dic_item.dic_id
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    private LongCriteria dicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_hx_dic_item.item_code
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    private StringCriteria itemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_hx_dic_item.item_value
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    private StringCriteria itemValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_hx_dic_item.item_sort
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    private IntegerCriteria itemSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_hx_dic_item.description
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    private StringCriteria description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_hx_dic_item.item_parent_id
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    private LongCriteria itemParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_hx_dic_item.ancestors
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    private StringCriteria ancestors;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public CscpHxDicItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    @Override
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public LongCriteria getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public void setItemId(LongCriteria itemId) {
        this. itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    private void buildItemIdCriteria(Criteria criteria) {
        if (this.getItemId() == null) {
            return;
        }
        if (this.getItemId().getEquals() != null) {
            criteria.andItemIdEqualTo(this.getItemId().getEquals());
        } else {
            if (this.getItemId().getGreaterOrEqualThan() != null) {
                criteria.andItemIdGreaterThanOrEqualTo(this.getItemId().getGreaterOrEqualThan());
            }
            if (this.getItemId().getLessOrEqualThan() != null) {
                criteria.andItemIdLessThanOrEqualTo(this.getItemId().getLessOrEqualThan());
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public LongCriteria getDicId() {
        return dicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public void setDicId(LongCriteria dicId) {
        this. dicId = dicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    private void buildDicIdCriteria(Criteria criteria) {
        if (this.getDicId() == null) {
            return;
        }
        if (this.getDicId().getEquals() != null) {
            criteria.andDicIdEqualTo(this.getDicId().getEquals());
        } else {
            if (this.getDicId().getGreaterOrEqualThan() != null) {
                criteria.andDicIdGreaterThanOrEqualTo(this.getDicId().getGreaterOrEqualThan());
            }
            if (this.getDicId().getLessOrEqualThan() != null) {
                criteria.andDicIdLessThanOrEqualTo(this.getDicId().getLessOrEqualThan());
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public StringCriteria getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public void setItemCode(StringCriteria itemCode) {
        this. itemCode = itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    private void buildItemCodeCriteria(Criteria criteria) {
        if (this.getItemCode() == null) {
            return;
        }
        if (this.getItemCode().getEquals() != null) {
            criteria.andItemCodeEqualTo(this.getItemCode().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getItemCode().getContains())) {
                criteria.andItemCodeLike(String.format(LIKE_FORMAT, this.getItemCode().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public StringCriteria getItemValue() {
        return itemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public void setItemValue(StringCriteria itemValue) {
        this. itemValue = itemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    private void buildItemValueCriteria(Criteria criteria) {
        if (this.getItemValue() == null) {
            return;
        }
        if (this.getItemValue().getEquals() != null) {
            criteria.andItemValueEqualTo(this.getItemValue().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getItemValue().getContains())) {
                criteria.andItemValueLike(String.format(LIKE_FORMAT, this.getItemValue().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public IntegerCriteria getItemSort() {
        return itemSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public void setItemSort(IntegerCriteria itemSort) {
        this. itemSort = itemSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    private void buildItemSortCriteria(Criteria criteria) {
        if (this.getItemSort() == null) {
            return;
        }
        if (this.getItemSort().getEquals() != null) {
            criteria.andItemSortEqualTo(this.getItemSort().getEquals());
        } else {
            if (this.getItemSort().getGreaterOrEqualThan() != null) {
                criteria.andItemSortGreaterThanOrEqualTo(this.getItemSort().getGreaterOrEqualThan());
            }
            if (this.getItemSort().getLessOrEqualThan() != null) {
                criteria.andItemSortLessThanOrEqualTo(this.getItemSort().getLessOrEqualThan());
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public StringCriteria getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public void setDescription(StringCriteria description) {
        this. description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    private void buildDescriptionCriteria(Criteria criteria) {
        if (this.getDescription() == null) {
            return;
        }
        if (this.getDescription().getEquals() != null) {
            criteria.andDescriptionEqualTo(this.getDescription().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getDescription().getContains())) {
                criteria.andDescriptionLike(String.format(LIKE_FORMAT, this.getDescription().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public LongCriteria getItemParentId() {
        return itemParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public void setItemParentId(LongCriteria itemParentId) {
        this. itemParentId = itemParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    private void buildItemParentIdCriteria(Criteria criteria) {
        if (this.getItemParentId() == null) {
            return;
        }
        if (this.getItemParentId().getEquals() != null) {
            criteria.andItemParentIdEqualTo(this.getItemParentId().getEquals());
        } else {
            if (this.getItemParentId().getGreaterOrEqualThan() != null) {
                criteria.andItemParentIdGreaterThanOrEqualTo(this.getItemParentId().getGreaterOrEqualThan());
            }
            if (this.getItemParentId().getLessOrEqualThan() != null) {
                criteria.andItemParentIdLessThanOrEqualTo(this.getItemParentId().getLessOrEqualThan());
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public StringCriteria getAncestors() {
        return ancestors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public void setAncestors(StringCriteria ancestors) {
        this. ancestors = ancestors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    private void buildAncestorsCriteria(Criteria criteria) {
        if (this.getAncestors() == null) {
            return;
        }
        if (this.getAncestors().getEquals() != null) {
            criteria.andAncestorsEqualTo(this.getAncestors().getEquals());
        } else {
            if (StringUtils.isNotBlank(this.getAncestors().getContains())) {
                criteria.andAncestorsLike(String.format(LIKE_FORMAT, this.getAncestors().getContains()));
            }
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    @Override
    public Object buildCriteria() {
        Criteria criteria = this.createCriteria();
        this.buildItemIdCriteria(criteria);
        this.buildDicIdCriteria(criteria);
        this.buildItemCodeCriteria(criteria);
        this.buildItemValueCriteria(criteria);
        this.buildItemSortCriteria(criteria);
        this.buildDescriptionCriteria(criteria);
        this.buildItemParentIdCriteria(criteria);
        this.buildAncestorsCriteria(criteria);
        return criteria;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    protected abstract static class BaseGeneratedCriteria {
        protected List<Criterion> criteria;

        protected BaseGeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andItemIdIsNull() {
            addCriterion("item_id is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("item_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(Long value) {
            addCriterion("item_id =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(Long value) {
            addCriterion("item_id <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(Long value) {
            addCriterion("item_id >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(Long value) {
            addCriterion("item_id >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(Long value) {
            addCriterion("item_id <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(Long value) {
            addCriterion("item_id <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<Long> values) {
            addCriterion("item_id in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<Long> values) {
            addCriterion("item_id not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(Long value1, Long value2) {
            addCriterion("item_id between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(Long value1, Long value2) {
            addCriterion("item_id not between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andDicIdIsNull() {
            addCriterion("dic_id is null");
            return (Criteria) this;
        }

        public Criteria andDicIdIsNotNull() {
            addCriterion("dic_id is not null");
            return (Criteria) this;
        }

        public Criteria andDicIdEqualTo(Long value) {
            addCriterion("dic_id =", value, "dicId");
            return (Criteria) this;
        }

        public Criteria andDicIdNotEqualTo(Long value) {
            addCriterion("dic_id <>", value, "dicId");
            return (Criteria) this;
        }

        public Criteria andDicIdGreaterThan(Long value) {
            addCriterion("dic_id >", value, "dicId");
            return (Criteria) this;
        }

        public Criteria andDicIdGreaterThanOrEqualTo(Long value) {
            addCriterion("dic_id >=", value, "dicId");
            return (Criteria) this;
        }

        public Criteria andDicIdLessThan(Long value) {
            addCriterion("dic_id <", value, "dicId");
            return (Criteria) this;
        }

        public Criteria andDicIdLessThanOrEqualTo(Long value) {
            addCriterion("dic_id <=", value, "dicId");
            return (Criteria) this;
        }

        public Criteria andDicIdIn(List<Long> values) {
            addCriterion("dic_id in", values, "dicId");
            return (Criteria) this;
        }

        public Criteria andDicIdNotIn(List<Long> values) {
            addCriterion("dic_id not in", values, "dicId");
            return (Criteria) this;
        }

        public Criteria andDicIdBetween(Long value1, Long value2) {
            addCriterion("dic_id between", value1, value2, "dicId");
            return (Criteria) this;
        }

        public Criteria andDicIdNotBetween(Long value1, Long value2) {
            addCriterion("dic_id not between", value1, value2, "dicId");
            return (Criteria) this;
        }

        public Criteria andItemCodeIsNull() {
            addCriterion("item_code is null");
            return (Criteria) this;
        }

        public Criteria andItemCodeIsNotNull() {
            addCriterion("item_code is not null");
            return (Criteria) this;
        }

        public Criteria andItemCodeEqualTo(String value) {
            addCriterion("item_code =", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeNotEqualTo(String value) {
            addCriterion("item_code <>", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeGreaterThan(String value) {
            addCriterion("item_code >", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeGreaterThanOrEqualTo(String value) {
            addCriterion("item_code >=", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeLessThan(String value) {
            addCriterion("item_code <", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeLessThanOrEqualTo(String value) {
            addCriterion("item_code <=", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeLike(String value) {
            addCriterion("item_code like", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeNotLike(String value) {
            addCriterion("item_code not like", value, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeIn(List<String> values) {
            addCriterion("item_code in", values, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeNotIn(List<String> values) {
            addCriterion("item_code not in", values, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeBetween(String value1, String value2) {
            addCriterion("item_code between", value1, value2, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemCodeNotBetween(String value1, String value2) {
            addCriterion("item_code not between", value1, value2, "itemCode");
            return (Criteria) this;
        }

        public Criteria andItemValueIsNull() {
            addCriterion("item_value is null");
            return (Criteria) this;
        }

        public Criteria andItemValueIsNotNull() {
            addCriterion("item_value is not null");
            return (Criteria) this;
        }

        public Criteria andItemValueEqualTo(String value) {
            addCriterion("item_value =", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueNotEqualTo(String value) {
            addCriterion("item_value <>", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueGreaterThan(String value) {
            addCriterion("item_value >", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueGreaterThanOrEqualTo(String value) {
            addCriterion("item_value >=", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueLessThan(String value) {
            addCriterion("item_value <", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueLessThanOrEqualTo(String value) {
            addCriterion("item_value <=", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueLike(String value) {
            addCriterion("item_value like", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueNotLike(String value) {
            addCriterion("item_value not like", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueIn(List<String> values) {
            addCriterion("item_value in", values, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueNotIn(List<String> values) {
            addCriterion("item_value not in", values, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueBetween(String value1, String value2) {
            addCriterion("item_value between", value1, value2, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueNotBetween(String value1, String value2) {
            addCriterion("item_value not between", value1, value2, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemSortIsNull() {
            addCriterion("item_sort is null");
            return (Criteria) this;
        }

        public Criteria andItemSortIsNotNull() {
            addCriterion("item_sort is not null");
            return (Criteria) this;
        }

        public Criteria andItemSortEqualTo(Integer value) {
            addCriterion("item_sort =", value, "itemSort");
            return (Criteria) this;
        }

        public Criteria andItemSortNotEqualTo(Integer value) {
            addCriterion("item_sort <>", value, "itemSort");
            return (Criteria) this;
        }

        public Criteria andItemSortGreaterThan(Integer value) {
            addCriterion("item_sort >", value, "itemSort");
            return (Criteria) this;
        }

        public Criteria andItemSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("item_sort >=", value, "itemSort");
            return (Criteria) this;
        }

        public Criteria andItemSortLessThan(Integer value) {
            addCriterion("item_sort <", value, "itemSort");
            return (Criteria) this;
        }

        public Criteria andItemSortLessThanOrEqualTo(Integer value) {
            addCriterion("item_sort <=", value, "itemSort");
            return (Criteria) this;
        }

        public Criteria andItemSortIn(List<Integer> values) {
            addCriterion("item_sort in", values, "itemSort");
            return (Criteria) this;
        }

        public Criteria andItemSortNotIn(List<Integer> values) {
            addCriterion("item_sort not in", values, "itemSort");
            return (Criteria) this;
        }

        public Criteria andItemSortBetween(Integer value1, Integer value2) {
            addCriterion("item_sort between", value1, value2, "itemSort");
            return (Criteria) this;
        }

        public Criteria andItemSortNotBetween(Integer value1, Integer value2) {
            addCriterion("item_sort not between", value1, value2, "itemSort");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andItemParentIdIsNull() {
            addCriterion("item_parent_id is null");
            return (Criteria) this;
        }

        public Criteria andItemParentIdIsNotNull() {
            addCriterion("item_parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemParentIdEqualTo(Long value) {
            addCriterion("item_parent_id =", value, "itemParentId");
            return (Criteria) this;
        }

        public Criteria andItemParentIdNotEqualTo(Long value) {
            addCriterion("item_parent_id <>", value, "itemParentId");
            return (Criteria) this;
        }

        public Criteria andItemParentIdGreaterThan(Long value) {
            addCriterion("item_parent_id >", value, "itemParentId");
            return (Criteria) this;
        }

        public Criteria andItemParentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("item_parent_id >=", value, "itemParentId");
            return (Criteria) this;
        }

        public Criteria andItemParentIdLessThan(Long value) {
            addCriterion("item_parent_id <", value, "itemParentId");
            return (Criteria) this;
        }

        public Criteria andItemParentIdLessThanOrEqualTo(Long value) {
            addCriterion("item_parent_id <=", value, "itemParentId");
            return (Criteria) this;
        }

        public Criteria andItemParentIdIn(List<Long> values) {
            addCriterion("item_parent_id in", values, "itemParentId");
            return (Criteria) this;
        }

        public Criteria andItemParentIdNotIn(List<Long> values) {
            addCriterion("item_parent_id not in", values, "itemParentId");
            return (Criteria) this;
        }

        public Criteria andItemParentIdBetween(Long value1, Long value2) {
            addCriterion("item_parent_id between", value1, value2, "itemParentId");
            return (Criteria) this;
        }

        public Criteria andItemParentIdNotBetween(Long value1, Long value2) {
            addCriterion("item_parent_id not between", value1, value2, "itemParentId");
            return (Criteria) this;
        }

        public Criteria andAncestorsIsNull() {
            addCriterion("ancestors is null");
            return (Criteria) this;
        }

        public Criteria andAncestorsIsNotNull() {
            addCriterion("ancestors is not null");
            return (Criteria) this;
        }

        public Criteria andAncestorsEqualTo(String value) {
            addCriterion("ancestors =", value, "ancestors");
            return (Criteria) this;
        }

        public Criteria andAncestorsNotEqualTo(String value) {
            addCriterion("ancestors <>", value, "ancestors");
            return (Criteria) this;
        }

        public Criteria andAncestorsGreaterThan(String value) {
            addCriterion("ancestors >", value, "ancestors");
            return (Criteria) this;
        }

        public Criteria andAncestorsGreaterThanOrEqualTo(String value) {
            addCriterion("ancestors >=", value, "ancestors");
            return (Criteria) this;
        }

        public Criteria andAncestorsLessThan(String value) {
            addCriterion("ancestors <", value, "ancestors");
            return (Criteria) this;
        }

        public Criteria andAncestorsLessThanOrEqualTo(String value) {
            addCriterion("ancestors <=", value, "ancestors");
            return (Criteria) this;
        }

        public Criteria andAncestorsLike(String value) {
            addCriterion("ancestors like", value, "ancestors");
            return (Criteria) this;
        }

        public Criteria andAncestorsNotLike(String value) {
            addCriterion("ancestors not like", value, "ancestors");
            return (Criteria) this;
        }

        public Criteria andAncestorsIn(List<String> values) {
            addCriterion("ancestors in", values, "ancestors");
            return (Criteria) this;
        }

        public Criteria andAncestorsNotIn(List<String> values) {
            addCriterion("ancestors not in", values, "ancestors");
            return (Criteria) this;
        }

        public Criteria andAncestorsBetween(String value1, String value2) {
            addCriterion("ancestors between", value1, value2, "ancestors");
            return (Criteria) this;
        }

        public Criteria andAncestorsNotBetween(String value1, String value2) {
            addCriterion("ancestors not between", value1, value2, "ancestors");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated do_not_delete_during_merge Thu Feb 10 18:11:40 CST 2022
     */
    public static class Criteria extends BaseGeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cscp_hx_dic_item
     *
     * @mbg.generated Thu Feb 10 18:11:40 CST 2022
     */
    public static class Criterion {
        @ApiParam(hidden=true)
        private String condition;

        @ApiParam(hidden=true)
        private Object value;

        @ApiParam(hidden=true)
        private Object secondValue;

        @ApiParam(hidden=true)
        private boolean noValue;

        @ApiParam(hidden=true)
        private boolean singleValue;

        @ApiParam(hidden=true)
        private boolean betweenValue;

        @ApiParam(hidden=true)
        private boolean listValue;

        @ApiParam(hidden=true)
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}