# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    application:
        name: udp6hx
    profiles:
         active: dev,swagger,enc
    jackson:
        serialization.write_dates_as_timestamps: false
        date-format: yyyy-MM-dd HH:mm:ss
    mvc:
        favicon:
            enabled: false
    activiti:
        check-process-definitions: false
        #  开启历史数据表
        db-history-used: true
        #  历史数据保存粒度
        # 1.none：不保存任何历史数据；
        # 2.activity：保存流程实例和流程行为
        # 3.audit：+流程任务及其属性
        # 4.full：所有（细节数据，流程参数等）
        history-level: audit
        asyncExecutorEnabled: false
        asyncExecutorActivate: false
        deployment-mode:  never-fail
#    redis:
#        #数据库索引
#        database: 0
#        host: 127.0.0.1
#        port: 6380
#        password: 123456
#        jedis:
#            pool:
#                #最大连接数
#                max-active: 8
#                #最大阻塞等待时间(负数表示没限制)
#                max-wait: -1
#                #最大空闲
#                max-idle: 8
#                #最小空闲
#                min-idle: 0
#                #连接超时时间
#        timeout: 10000
management:
    endpoints:
        web:
            #监控接口
            exposure:
                include: "info,health,prometheus"

ctsi:
    swagger:
        default-include-pattern: /api/.*
        title: ctsi API
        description: ctsi API documentation
        version: 0.0.1
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url:
    #saas模式：true,非saas模式false,默认false
    saasModel: false
    #错误码相关配置项
    error-code:
        constants-class-list:
            - com.ctsi.ssdc.errorcode.enums.ErrorCodeConstants
#            - com.ctsi.ssdc.admin.enums.ErrorCodeConstants

##MP配置
##mapper的xml文件的扫描路径

mybatis-plus:
#    mapper-locations: classpath:/mybatis-config.xml
    mapper-locations: classpath:mybatisplus/mapper/*.xml
#    type-aliases-package: com.ctsi.ssdc.mybatis.plus
    global-config:
        db-config:
            #配置逻辑删除字段为0是未删除
            logic-not-delete-value: 0
            #配置逻辑删除字段为1是删除
            logic-delete-value: 1
    #打印sql语句
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl