package com.ctsi.ssdc.admin.domain.dto;

import com.ctsi.ssdc.util.LongtoStringSerialize;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.io.Serializable;
import java.time.ZoneId;
import java.time.ZonedDateTime;

/**
 * @author MyBatis Generator
*/
public class CscpLogLoginDTO implements Serializable {
	
	public final static String ERROR = "error";
	
	public final static String SUCCESS = "success";
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_login.id
     *
     * @mbg.generated Fri Aug 03 08:51:06 CST 2018
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long id;

    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long teantId;

    public Long getTeantId() {
        return teantId;
    }

    public void setTeantId(Long teantId) {
        this.teantId = teantId;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_login.user_name
     *
     * @mbg.generated Fri Aug 03 08:51:06 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_login.ip
     *
     * @mbg.generated Fri Aug 03 08:51:06 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_login.message
     *
     * @mbg.generated Fri Aug 03 08:51:06 CST 2018
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_login.time
     *
     * @mbg.generated Fri Aug 03 08:51:06 CST 2018
     */
    private ZonedDateTime time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_login.status
     *
     * @mbg.generated Fri Aug 03 08:51:06 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_log_login
     *
     * @mbg.generated Fri Aug 03 08:51:06 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_log_login.id
     *
     * @return the value of cscp_log_login.id
     *
     * @mbg.generated Fri Aug 03 08:51:06 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_log_login.id
     *
     * @param id the value for cscp_log_login.id
     *
     * @mbg.generated Fri Aug 03 08:51:06 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_log_login.user_name
     *
     * @return the value of cscp_log_login.user_name
     *
     * @mbg.generated Fri Aug 03 08:51:06 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_log_login.user_name
     *
     * @param userName the value for cscp_log_login.user_name
     *
     * @mbg.generated Fri Aug 03 08:51:06 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_log_login.ip
     *
     * @return the value of cscp_log_login.ip
     *
     * @mbg.generated Fri Aug 03 08:51:06 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_log_login.ip
     *
     * @param ip the value for cscp_log_login.ip
     *
     * @mbg.generated Fri Aug 03 08:51:06 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_log_login.message
     *
     * @return the value of cscp_log_login.message
     *
     * @mbg.generated Fri Aug 03 08:51:06 CST 2018
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_log_login.message
     *
     * @param message the value for cscp_log_login.message
     *
     * @mbg.generated Fri Aug 03 08:51:06 CST 2018
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_log_login.time
     *
     * @return the value of cscp_log_login.time
     *
     * @mbg.generated Fri Aug 03 08:51:06 CST 2018
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
    public ZonedDateTime getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_log_login.time
     *
     * @param time the value for cscp_log_login.time
     *
     * @mbg.generated Fri Aug 03 08:51:06 CST 2018
     */
    public void setTime(ZonedDateTime time) {
        if(time!=null) {
            time=time.toInstant().atZone(ZoneId.systemDefault());
        }
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_log_login.status
     *
     * @return the value of cscp_log_login.status
     *
     * @mbg.generated Fri Aug 03 08:51:06 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_log_login.status
     *
     * @param status the value for cscp_log_login.status
     *
     * @mbg.generated Fri Aug 03 08:51:06 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_log_login
     *
     * @mbg.generated Fri Aug 03 08:51:06 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CscpLogLoginDTO other = (CscpLogLoginDTO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            &&(this.getTeantId() == null ? other.getTeantId() == null : this.getTeantId().equals(other.getTeantId()))
            && (this.getUserName() == null ?
                other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getIp() == null ? other.getIp() == null : this.getIp().equals(other.getIp()))
            && (this.getMessage() == null ? other.getMessage() == null : this.getMessage().equals(other.getMessage()))
            && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_log_login
     *
     * @mbg.generated Fri Aug 03 08:51:06 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTeantId() == null) ? 0 : getTeantId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getIp() == null) ? 0 : getIp().hashCode());
        result = prime * result + ((getMessage() == null) ? 0 : getMessage().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }
}