package com.ctsi.ssdc.admin.domain.dto;

import com.ctsi.ssdc.admin.domain.CscpPost;
import com.ctsi.ssdc.annocation.AutoId;
import com.ctsi.ssdc.util.LongtoStringSerialize;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.io.Serializable;
import java.time.ZonedDateTime;

public class CscpPostDTO implements Serializable {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_post.post_id
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    @AutoId(primaryKey = "post_id")
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_post.post_code
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_post.post_name
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    private String postName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_post.post_sort
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    private Integer postSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_post.status
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_post.create_by
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_post.create_time
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone="GMT+8")
    private ZonedDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_post.update_by
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_post.update_time
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone="GMT+8")
    private ZonedDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_post.remark
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    private String remark;

    /**
     * 租户id
     *
     */
    @JsonSerialize(using = LongtoStringSerialize.class)

    private Long tenantId;

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_post.post_id
     *
     * @return the value of cscp_post.post_id
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_post.post_id
     *
     * @param postId the value for cscp_post.post_id
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_post.post_code
     *
     * @return the value of cscp_post.post_code
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_post.post_code
     *
     * @param postCode the value for cscp_post.post_code
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_post.post_name
     *
     * @return the value of cscp_post.post_name
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    public String getPostName() {
        return postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_post.post_name
     *
     * @param postName the value for cscp_post.post_name
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    public void setPostName(String postName) {
        this.postName = postName == null ? null : postName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_post.post_sort
     *
     * @return the value of cscp_post.post_sort
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    public Integer getPostSort() {
        return postSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_post.post_sort
     *
     * @param postSort the value for cscp_post.post_sort
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    public void setPostSort(Integer postSort) {
        this.postSort = postSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_post.status
     *
     * @return the value of cscp_post.status
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_post.status
     *
     * @param status the value for cscp_post.status
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_post.create_by
     *
     * @return the value of cscp_post.create_by
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_post.create_by
     *
     * @param createBy the value for cscp_post.create_by
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_post.create_time
     *
     * @return the value of cscp_post.create_time
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    public ZonedDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_post.create_time
     *
     * @param createTime the value for cscp_post.create_time
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    public void setCreateTime(ZonedDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_post.update_by
     *
     * @return the value of cscp_post.update_by
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_post.update_by
     *
     * @param updateBy the value for cscp_post.update_by
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_post.update_time
     *
     * @return the value of cscp_post.update_time
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    public ZonedDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_post.update_time
     *
     * @param updateTime the value for cscp_post.update_time
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    public void setUpdateTime(ZonedDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_post.remark
     *
     * @return the value of cscp_post.remark
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_post.remark
     *
     * @param remark the value for cscp_post.remark
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_post
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CscpPost other = (CscpPost) that;
        return (this.getPostId() == null ? other.getPostId() == null : this.getPostId().equals(other.getPostId()))
                && (this.getPostCode() == null ? other.getPostCode() == null : this.getPostCode().equals(other.getPostCode()))
                && (this.getPostName() == null ? other.getPostName() == null : this.getPostName().equals(other.getPostName()))
                && (this.getPostSort() == null ? other.getPostSort() == null : this.getPostSort().equals(other.getPostSort()))
                && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
                && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
                && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
                && (this.getTenantId() == null ? other.getTenantId() == null : this.getTenantId().equals(other.getTenantId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_post
     *
     * @mbg.generated Thu Jan 06 10:12:18 CST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPostId() == null) ? 0 : getPostId().hashCode());
        result = prime * result + ((getPostCode() == null) ? 0 : getPostCode().hashCode());
        result = prime * result + ((getPostName() == null) ? 0 : getPostName().hashCode());
        result = prime * result + ((getPostSort() == null) ? 0 : getPostSort().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getTenantId() == null) ? 0 : getTenantId().hashCode());
        return result;
    }


}
