package com.ctsi.ssdc.admin.domain.dto;

import com.ctsi.ssdc.util.LongtoStringSerialize;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.io.Serializable;
import java.time.ZoneId;
import java.time.ZonedDateTime;

/**
 * @author MyBatis Generator
*/
public class CscpLogOperationDTO implements Serializable {
	
	public final static String ERROR = "error";
	
	public final static String SUCCESS = "success";
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.id
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long id;
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long teantId;

    public Long getTeantId() {
        return teantId;
    }

    public void setTeantId(Long teantId) {
        this.teantId = teantId;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.userid
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.username
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.uri
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    private String uri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.ip
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.params
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    private String params;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.method
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.message
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.status
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.time
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    private ZonedDateTime time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_log_operation.error
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    private String error;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_log_operation
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_log_operation.id
     *
     * @return the value of cscp_log_operation.id
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_log_operation.id
     *
     * @param id the value for cscp_log_operation.id
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_log_operation.userid
     *
     * @return the value of cscp_log_operation.userid
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_log_operation.userid
     *
     * @param userid the value for cscp_log_operation.userid
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_log_operation.username
     *
     * @return the value of cscp_log_operation.username
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_log_operation.username
     *
     * @param username the value for cscp_log_operation.username
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_log_operation.uri
     *
     * @return the value of cscp_log_operation.uri
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_log_operation.uri
     *
     * @param uri the value for cscp_log_operation.uri
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public void setUri(String uri) {
        this.uri = uri == null ? null : uri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_log_operation.ip
     *
     * @return the value of cscp_log_operation.ip
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_log_operation.ip
     *
     * @param ip the value for cscp_log_operation.ip
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_log_operation.params
     *
     * @return the value of cscp_log_operation.params
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_log_operation.params
     *
     * @param params the value for cscp_log_operation.params
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_log_operation.method
     *
     * @return the value of cscp_log_operation.method
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_log_operation.method
     *
     * @param method the value for cscp_log_operation.method
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_log_operation.message
     *
     * @return the value of cscp_log_operation.message
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_log_operation.message
     *
     * @param message the value for cscp_log_operation.message
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_log_operation.status
     *
     * @return the value of cscp_log_operation.status
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_log_operation.status
     *
     * @param status the value for cscp_log_operation.status
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_log_operation.time
     *
     * @return the value of cscp_log_operation.time
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
    public ZonedDateTime getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_log_operation.time
     *
     * @param time the value for cscp_log_operation.time
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public void setTime(ZonedDateTime time) {
        if(time!=null) {
            time=time.toInstant().atZone(ZoneId.systemDefault());
        }
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_log_operation.error
     *
     * @return the value of cscp_log_operation.error
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public String getError() {
        return error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_log_operation.error
     *
     * @param error the value for cscp_log_operation.error
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    public void setError(String error) {
        this.error = error == null ? null : error.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_log_operation
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CscpLogOperationDTO other = (CscpLogOperationDTO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getTeantId() == null ? other.getTeantId() == null : this.getTeantId().equals(other.getTeantId()))
            && (this.getUsername() == null ?
                other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getUri() == null ? other.getUri() == null : this.getUri().equals(other.getUri()))
            && (this.getIp() == null ? other.getIp() == null : this.getIp().equals(other.getIp()))
            && (this.getParams() == null ? other.getParams() == null : this.getParams().equals(other.getParams()))
            && (this.getMethod() == null ? other.getMethod() == null : this.getMethod().equals(other.getMethod()))
            && (this.getMessage() == null ? other.getMessage() == null : this.getMessage().equals(other.getMessage()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
            && (this.getError() == null ? other.getError() == null : this.getError().equals(other.getError()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_log_operation
     *
     * @mbg.generated Thu Aug 02 11:13:47 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTeantId() == null) ? 0 : getTeantId().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getUri() == null) ? 0 : getUri().hashCode());
        result = prime * result + ((getIp() == null) ? 0 : getIp().hashCode());
        result = prime * result + ((getParams() == null) ? 0 : getParams().hashCode());
        result = prime * result + ((getMethod() == null) ? 0 : getMethod().hashCode());
        result = prime * result + ((getMessage() == null) ? 0 : getMessage().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getError() == null) ? 0 : getError().hashCode());
        return result;
    }
}