package com.ctsi.ssdc.admin.domain.dto;

import com.ctsi.ssdc.admin.domain.CscpPost;
import com.ctsi.ssdc.admin.domain.CscpRoles;
import com.ctsi.ssdc.util.LongtoStringSerialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.io.Serializable;
import java.time.ZonedDateTime;
import java.util.List;

/**
 * @author MyBatis Generator
 */
public class CscpUserDetailDTO implements Serializable {

	private Boolean lockStatus;

	public Boolean getLockStatus() {
		return lockStatus;
	}

	public void setLockStatus(Boolean lockStatus) {
		this.lockStatus = lockStatus;
	}

	private String password;

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cscp_user_detail.id
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	@JsonSerialize(using = LongtoStringSerialize.class)
	private Long id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cscp_user_detail.user_id
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	@JsonSerialize(using = LongtoStringSerialize.class)
	private Long userId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cscp_user_detail.family_name
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	private String familyName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cscp_user_detail.name
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cscp_user_detail.mobile
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	private String mobile;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cscp_user_detail.email
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	private String email;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cscp_user_detail.img_path
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	private String imgPath;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cscp_user_detail.last_login
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	private ZonedDateTime lastLogin;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cscp_user_detail.disc_title
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	private String discTitle;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cscp_user_detail.disc_detail
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	private String discDetail;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cscp_user_detail.register_time
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	private ZonedDateTime registerTime;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table cscp_user_detail
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 用户管理员标志
	 * 0：普通用户
	 * 1：普通租户下的管理员
	 * 2：租户管理员（超级管理员）
	 */
	private String adminFlag;

	/**
	 *  部门id
	 */
	@JsonSerialize(using = LongtoStringSerialize.class)
	private Long deptId;


	/**
	 *  租户id
	 */
	@JsonSerialize(using = LongtoStringSerialize.class)
	private Long tenantId;
	/**
	 *  租户账号
	 */
	private String tenantAccount;

	public Long getTenantId() {
		return tenantId;
	}

	public void setTenantId(Long tenantId) {
		this.tenantId = tenantId;
	}

	public Long getDeptId() {
		return deptId;
	}

	public void setDeptId(Long deptId) {
		this.deptId = deptId;
	}

	public String getAdminFlag() {
		return adminFlag;
	}

	public void setAdminFlag(String adminFlag) {
		this.adminFlag = adminFlag;
	}

	public String getTenantAccount() {
		return tenantAccount;
	}

	public void setTenantAccount(String tenantAccount) {
		this.tenantAccount = tenantAccount;
	}

	/**
	 * 这个是自己添加的。在新建用户时，需要将用户名一同添加
	 */
	private String username;
	/**
	 * 保存用户角色
	 */
	private String roles;

	private String roleIds;

	private String roleNames;

	private List<CscpRoles> rolesList;

	private String posts;

	private String postIds;

	private String postNames;

	private List<CscpPost> postsList;

	List<String> groups;
	@JsonSerialize(using = LongtoStringSerialize.class)
	private Long orgId;

	public List<String> getGroups() {
		return groups;
	}

	public void setGroups(List<String> groups) {
		this.groups = groups;
	}

	public Long getOrgId() {
		return orgId;
	}

	public void setOrgId(Long orgId) {
		this.orgId = orgId;
	}

	public String getRoleIds() {
		return roleIds;
	}

	public void setRoleIds(String roleIds) {
		this.roleIds = roleIds;
	}

	public String getRoleNames() {
		return roleNames;
	}

	public void setRoleNames(String roleNames) {
		this.roleNames = roleNames;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getRoles() {
		return roles;
	}

	public void setRoles(String roles) {
		this.roles = roles;
	}

	public String getPosts() {
		return posts;
	}

	public void setPosts(String posts) {
		this.posts = posts;
	}

	public String getPostIds() {
		return postIds;
	}

	public void setPostIds(String postIds) {
		this.postIds = postIds;
	}

	public String getPostNames() {
		return postNames;
	}

	public void setPostNames(String postNames) {
		this.postNames = postNames;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cscp_user_detail.id
	 *
	 * @return the value of cscp_user_detail.id
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cscp_user_detail.id
	 *
	 * @param id
	 *            the value for cscp_user_detail.id
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cscp_user_detail.user_id
	 *
	 * @return the value of cscp_user_detail.user_id
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cscp_user_detail.user_id
	 *
	 * @param userId
	 *            the value for cscp_user_detail.user_id
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cscp_user_detail.family_name
	 *
	 * @return the value of cscp_user_detail.family_name
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public String getFamilyName() {
		return familyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cscp_user_detail.family_name
	 *
	 * @param familyName
	 *            the value for cscp_user_detail.family_name
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public void setFamilyName(String familyName) {
		this.familyName = familyName == null ? null : familyName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cscp_user_detail.name
	 *
	 * @return the value of cscp_user_detail.name
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cscp_user_detail.name
	 *
	 * @param name
	 *            the value for cscp_user_detail.name
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cscp_user_detail.mobile
	 *
	 * @return the value of cscp_user_detail.mobile
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cscp_user_detail.mobile
	 *
	 * @param mobile
	 *            the value for cscp_user_detail.mobile
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cscp_user_detail.email
	 *
	 * @return the value of cscp_user_detail.email
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cscp_user_detail.email
	 *
	 * @param email
	 *            the value for cscp_user_detail.email
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cscp_user_detail.img_path
	 *
	 * @return the value of cscp_user_detail.img_path
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public String getImgPath() {
		return imgPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cscp_user_detail.img_path
	 *
	 * @param imgPath
	 *            the value for cscp_user_detail.img_path
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public void setImgPath(String imgPath) {
		this.imgPath = imgPath == null ? null : imgPath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cscp_user_detail.last_login
	 *
	 * @return the value of cscp_user_detail.last_login
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public ZonedDateTime getLastLogin() {
		return lastLogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cscp_user_detail.last_login
	 *
	 * @param lastLogin
	 *            the value for cscp_user_detail.last_login
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public void setLastLogin(ZonedDateTime lastLogin) {
		this.lastLogin = lastLogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cscp_user_detail.disc_title
	 *
	 * @return the value of cscp_user_detail.disc_title
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public String getDiscTitle() {
		return discTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cscp_user_detail.disc_title
	 *
	 * @param discTitle
	 *            the value for cscp_user_detail.disc_title
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public void setDiscTitle(String discTitle) {
		this.discTitle = discTitle == null ? null : discTitle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cscp_user_detail.disc_detail
	 *
	 * @return the value of cscp_user_detail.disc_detail
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public String getDiscDetail() {
		return discDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cscp_user_detail.disc_detail
	 *
	 * @param discDetail
	 *            the value for cscp_user_detail.disc_detail
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public void setDiscDetail(String discDetail) {
		this.discDetail = discDetail == null ? null : discDetail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cscp_user_detail.register_time
	 *
	 * @return the value of cscp_user_detail.register_time
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public ZonedDateTime getRegisterTime() {
		return registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cscp_user_detail.register_time
	 *
	 * @param registerTime
	 *            the value for cscp_user_detail.register_time
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	public void setRegisterTime(ZonedDateTime registerTime) {
		this.registerTime = registerTime;
	}

	public List<CscpRoles> getRolesList() {
		return rolesList;
	}

	public void setRolesList(List<CscpRoles> rolesList) {
		this.rolesList = rolesList;
	}

	public List<CscpPost> getPostsList() {
		return postsList;
	}

	public void setPostsList(List<CscpPost> postsList) {
		this.postsList = postsList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cscp_user_detail
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		CscpUserDetailDTO other = (CscpUserDetailDTO) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getUserId() == null ?
				other.getUserId() == null : this.getUserId().equals(other.getUserId()))
				&& (this.getFamilyName() == null ? other.getFamilyName() == null
						: this.getFamilyName().equals(other.getFamilyName()))
				&& (this.getName() == null ?
				other.getName() == null : this.getName().equals(other.getName()))
				&& (this.getMobile() == null ?
				other.getMobile() == null :
				this.getMobile().equals(other.getMobile()))
				&& (this.getEmail() == null ?
				other.getEmail() == null : this.getEmail().equals(other.getEmail()))
				&& (this.getImgPath() == null ? other.getImgPath() == null
						: this.getImgPath().equals(other.getImgPath()))
				&& (this.getLastLogin() == null ? other.getLastLogin() == null
						: this.getLastLogin().equals(other.getLastLogin()))
				&& (this.getDiscTitle() == null ? other.getDiscTitle() == null
						: this.getDiscTitle().equals(other.getDiscTitle()))
				&& (this.getDiscDetail() == null ? other.getDiscDetail() == null
						: this.getDiscDetail().equals(other.getDiscDetail()))
				&& (this.getRegisterTime() == null ? other.getRegisterTime() == null
						: this.getRegisterTime().equals(other.getRegisterTime()))
				&& (this.getAdminFlag() == null ? other.getAdminFlag() == null
				: this.getAdminFlag().equals(other.getAdminFlag()))
				&& (this.getDeptId() == null ?
				other.getDeptId() == null : this.getDeptId().equals(other.getDeptId()))
				&& (this.getPassword() == null ?
				other.getPassword() == null : this.getPassword().equals(other.getPassword()))
				&& (this.getTenantId() == null ?
				other.getTenantId() == null : this.getTenantId().equals(other.getTenantId()))
				&& (this.getTenantAccount() == null ?
				other.getTenantAccount() == null : this.getTenantAccount().equals(other.getTenantAccount()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cscp_user_detail
	 *
	 * @mbg.generated Mon Apr 23 08:56:34 CST 2018
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
		result = prime * result + ((getFamilyName() == null) ? 0 : getFamilyName().hashCode());
		result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
		result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
		result = prime * result + ((getImgPath() == null) ? 0 : getImgPath().hashCode());
		result = prime * result + ((getLastLogin() == null) ? 0 : getLastLogin().hashCode());
		result = prime * result + ((getDiscTitle() == null) ? 0 : getDiscTitle().hashCode());
		result = prime * result + ((getDiscDetail() == null) ? 0 : getDiscDetail().hashCode());
		result = prime * result + ((getRegisterTime() == null) ? 0 : getRegisterTime().hashCode());
		result = prime * result + ((getAdminFlag() == null) ? 0 : getAdminFlag().hashCode());
		result = prime * result + ((getDeptId() == null) ? 0 : getDeptId().hashCode());
		result = prime * result + ((getTenantId() == null) ? 0 : getTenantId().hashCode());
		result = prime * result + ((getTenantAccount() == null) ? 0 : getTenantAccount().hashCode());
		result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
		return result;
	}
}