package com.ctsi.ssdc.admin.domain.dto;

import com.ctsi.ssdc.util.LongtoStringSerialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.io.Serializable;

/**
 * @author MyBatis Generator
*/
public class CscpOrgDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_org.id
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_org.org_name
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    private String orgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_org.description
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_org.parent_id
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long parentId;


    private Integer orderby;

    public Integer getOrderby() {
        return orderby;
    }

    public void setOrderby(Integer orderby) {
        this.orderby = orderby;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_org
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_org.id
     *
     * @return the value of cscp_org.id
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_org.id
     *
     * @param id the value for cscp_org.id
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_org.org_name
     *
     * @return the value of cscp_org.org_name
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_org.org_name
     *
     * @param orgName the value for cscp_org.org_name
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_org.description
     *
     * @return the value of cscp_org.description
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_org.description
     *
     * @param description the value for cscp_org.description
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_org.parent_id
     *
     * @return the value of cscp_org.parent_id
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_org.parent_id
     *
     * @param parentId the value for cscp_org.parent_id
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_org
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CscpOrgDTO other = (CscpOrgDTO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrgName() == null ? other.getOrgName() == null : this.getOrgName().equals(other.getOrgName()))
            && (this.getDescription() == null ?
                other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getParentId() == null ?
                other.getParentId() == null : this.getParentId().equals(other.getParentId()))
            && (this.getOrderby() == null ? other.getOrderby() == null : this.getOrderby().equals(other.getOrderby()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_org
     *
     * @mbg.generated Mon Apr 23 08:56:34 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrgName() == null) ? 0 : getOrgName().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
        result = prime * result + ((getOrderby() == null) ? 0 : getOrderby() .hashCode());
        return result;
    }
}