package com.ctsi.ssdc.admin.domain.dto;

import com.ctsi.ssdc.util.LongtoStringSerialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.io.Serializable;

/**
 * @author MyBatis Generator
*/
public class CscpWorkGroupDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_work_group.id
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_work_group.group_name
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_work_group.description
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_work_group.org_id
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_work_group
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_work_group.id
     *
     * @return the value of cscp_work_group.id
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_work_group.id
     *
     * @param id the value for cscp_work_group.id
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_work_group.group_name
     *
     * @return the value of cscp_work_group.group_name
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_work_group.group_name
     *
     * @param groupName the value for cscp_work_group.group_name
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_work_group.description
     *
     * @return the value of cscp_work_group.description
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_work_group.description
     *
     * @param description the value for cscp_work_group.description
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_work_group.org_id
     *
     * @return the value of cscp_work_group.org_id
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_work_group.org_id
     *
     * @param orgId the value for cscp_work_group.org_id
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }
    
    private CscpUserDetailDTO[] userDetailDtos;
    

    public CscpUserDetailDTO[] getUserDetail() {
        CscpUserDetailDTO[] temp = userDetailDtos;
        return temp;
    }

    public void setUserDetail(CscpUserDetailDTO[] cscpuserDetailDtos) {
        CscpUserDetailDTO[] temp = userDetailDtos;
        this.userDetailDtos = temp.clone();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_work_group
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CscpWorkGroupDTO other = (CscpWorkGroupDTO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getGroupName() == null ?
                other.getGroupName() == null : this.getGroupName().equals(other.getGroupName()))
            && (this.getDescription() == null ?
                other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_work_group
     *
     * @mbg.generated Mon Apr 23 08:56:33 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGroupName() == null) ? 0 : getGroupName().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        return result;
    }
}