package com.ctsi.ssdc.admin.domain.dto;

import com.ctsi.ssdc.util.LongtoStringSerialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.io.Serializable;
import java.util.List;

/**
 * @author MyBatis Generator
*/
public class CscpMenusDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.id
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    //change
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.name
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.icon
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.title
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.url
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.http_method
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    private String httpMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.component
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    private String component;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.parent_id
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    //change
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.type
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.permission_code
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    private String permissionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_menus.orderby
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */

    private Integer orderby;

//    @JsonSerialize(using = LongtoStringSerialize.class)
    private List<Long> roleId;

    private List<String> roleName;

    private Integer flag;

    private List<CscpMenusDTO> childMenusList;

    public Integer getFlag() {
        return flag;
    }

    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    public List<String> getRoleName() {
        return roleName;
    }

    public void setRoleName(List<String> roleName) {
        this.roleName = roleName;
    }

    public List<Long> getRoleId() {
        return roleId;
    }

    public void setRoleId(List<Long> roleId) {
        this.roleId = roleId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_menus
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_menus.id
     *
     * @return the value of cscp_menus.id
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_menus.id
     *
     * @param id the value for cscp_menus.id
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_menus.name
     *
     * @return the value of cscp_menus.name
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_menus.name
     *
     * @param name the value for cscp_menus.name
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_menus.icon
     *
     * @return the value of cscp_menus.icon
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_menus.icon
     *
     * @param icon the value for cscp_menus.icon
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_menus.title
     *
     * @return the value of cscp_menus.title
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_menus.title
     *
     * @param title the value for cscp_menus.title
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_menus.url
     *
     * @return the value of cscp_menus.url
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_menus.url
     *
     * @param url the value for cscp_menus.url
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_menus.http_method
     *
     * @return the value of cscp_menus.http_method
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public String getHttpMethod() {
        return httpMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_menus.http_method
     *
     * @param httpMethod the value for cscp_menus.http_method
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public void setHttpMethod(String httpMethod) {
        this.httpMethod = httpMethod == null ? null : httpMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_menus.component
     *
     * @return the value of cscp_menus.component
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_menus.component
     *
     * @param component the value for cscp_menus.component
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public void setComponent(String component) {
        this.component = component == null ? null : component.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_menus.parent_id
     *
     * @return the value of cscp_menus.parent_id
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_menus.parent_id
     *
     * @param parentId the value for cscp_menus.parent_id
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_menus.type
     *
     * @return the value of cscp_menus.type
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_menus.type
     *
     * @param type the value for cscp_menus.type
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_menus.permission_code
     *
     * @return the value of cscp_menus.permission_code
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public String getPermissionCode() {
        return permissionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_menus.permission_code
     *
     * @param permissionCode the value for cscp_menus.permission_code
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode == null ? null : permissionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_menus.orderby
     *
     * @return the value of cscp_menus.orderby
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public Integer getOrderby() {
        return orderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_menus.orderby
     *
     * @param orderby the value for cscp_menus.orderby
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    public void setOrderby(Integer orderby) {
        this.orderby = orderby;
    }


    public List<CscpMenusDTO> getChildMenusList() {
        return childMenusList;
    }

    public void setChildMenusList(List<CscpMenusDTO> childMenusList) {
        this.childMenusList = childMenusList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_menus
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CscpMenusDTO other = (CscpMenusDTO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getIcon() == null ? other.getIcon() == null : this.getIcon().equals(other.getIcon()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getHttpMethod() == null ?
                other.getHttpMethod() == null : this.getHttpMethod().equals(other.getHttpMethod()))
            && (this.getComponent() == null ?
                other.getComponent() == null : this.getComponent().equals(other.getComponent()))
            && (this.getParentId() == null ?
                other.getParentId() == null : this.getParentId().equals(other.getParentId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getPermissionCode() == null ?
                other.getPermissionCode() == null : this.getPermissionCode().equals(other.getPermissionCode()))
            && (this.getOrderby() == null ? other.getOrderby() == null : this.getOrderby().equals(other.getOrderby()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_menus
     *
     * @mbg.generated Tue Aug 28 09:53:39 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getIcon() == null) ? 0 : getIcon().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getHttpMethod() == null) ? 0 : getHttpMethod().hashCode());
        result = prime * result + ((getComponent() == null) ? 0 : getComponent().hashCode());
        result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getPermissionCode() == null) ? 0 : getPermissionCode().hashCode());
        result = prime * result + ((getOrderby() == null) ? 0 : getOrderby().hashCode());
        return result;
    }
    
    public String getStringValues() {
		return getId()
				+ "," + getTitle()
				+ "," + getIcon()
				+ "," + getUrl()
				+ "," + getParentId()
				+ "," + getType()
				+ "," + getOrderby()
				+ "," + getComponent();
    	
    }
}