package com.ctsi.ssdc.admin.domain.dto;

import com.ctsi.ssdc.util.LongtoStringSerialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.io.Serializable;

/**
 * @author MyBatis Generator
*/
public class CscpWorkGroupOrgDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_work_group_org.id
     *
     * @mbg.generated Thu May 03 10:11:12 CST 2018
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_work_group_org.group_id
     *
     * @mbg.generated Thu May 03 10:11:12 CST 2018
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_work_group_org.org_id
     *
     * @mbg.generated Thu May 03 10:11:12 CST 2018
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_work_group_org
     *
     * @mbg.generated Thu May 03 10:11:12 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_work_group_org.id
     *
     * @return the value of cscp_work_group_org.id
     *
     * @mbg.generated Thu May 03 10:11:12 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_work_group_org.id
     *
     * @param id the value for cscp_work_group_org.id
     *
     * @mbg.generated Thu May 03 10:11:12 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_work_group_org.group_id
     *
     * @return the value of cscp_work_group_org.group_id
     *
     * @mbg.generated Thu May 03 10:11:12 CST 2018
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_work_group_org.group_id
     *
     * @param groupId the value for cscp_work_group_org.group_id
     *
     * @mbg.generated Thu May 03 10:11:12 CST 2018
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_work_group_org.org_id
     *
     * @return the value of cscp_work_group_org.org_id
     *
     * @mbg.generated Thu May 03 10:11:12 CST 2018
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_work_group_org.org_id
     *
     * @param orgId the value for cscp_work_group_org.org_id
     *
     * @mbg.generated Thu May 03 10:11:12 CST 2018
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_work_group_org
     *
     * @mbg.generated Thu May 03 10:11:12 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CscpWorkGroupOrgDTO other = (CscpWorkGroupOrgDTO) that;
        return (this.getGroupId() == null ? other.getGroupId() == null : this.getGroupId().equals(other.getGroupId()))
            && (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_work_group_org
     *
     * @mbg.generated Thu May 03 10:11:12 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGroupId() == null) ? 0 : getGroupId().hashCode());
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        return result;
    }
}