package com.ctsi.ssdc.admin.domain.dto;

import com.ctsi.ssdc.util.LongtoStringSerialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.io.Serializable;

/**
 * @author MyBatis Generator
*/
public class CscpUserOrgDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_org.id
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_org.user_id
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_user_org.org_id
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cscp_user_org
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_user_org.id
     *
     * @return the value of cscp_user_org.id
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_user_org.id
     *
     * @param id the value for cscp_user_org.id
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_user_org.user_id
     *
     * @return the value of cscp_user_org.user_id
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_user_org.user_id
     *
     * @param userId the value for cscp_user_org.user_id
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_user_org.org_id
     *
     * @return the value of cscp_user_org.org_id
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_user_org.org_id
     *
     * @param orgId the value for cscp_user_org.org_id
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_org
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CscpUserOrgDTO other = (CscpUserOrgDTO) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
                && (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()));

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_user_org
     *
     * @mbg.generated Thu May 03 10:11:11 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        return result;
    }
}