package com.ctsi.ssdc.sysconfig.repository;

import com.ctsi.ssdc.sysconfig.domain.CscpSysConfig;
import com.ctsi.ssdc.sysconfig.domain.CscpSysConfigExample;
import com.ctsi.ssdc.sysconfig.domain.CscpSysConfigExample.Criteria;
import com.ctsi.ssdc.sysconfig.domain.CscpSysConfigExample.Criterion;
import org.apache.ibatis.jdbc.SQL;
import java.util.List;
import java.util.Map;


/**
 * CscpSysConfigSqlProvider
 *
 * @author hx
 * @date 2022-08-25 14:30:26
 */

public class CscpSysConfigSqlProvider {

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_sys_config
     */
    public String countByExample(CscpSysConfigExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("cscp_sys_config");
        applyWhere(sql, example, false);
        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_sys_config
     */
    public String deleteByExample(CscpSysConfigExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("cscp_sys_config");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_sys_config
     */
    public String insertSelective(CscpSysConfig record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("cscp_sys_config");

        if (record.getConfigId() != null) {
            sql.VALUES("config_id", "#{configId,jdbcType=BIGINT}");
        }
        if (record.getConfigName() != null) {
            sql.VALUES("config_name", "#{configName,jdbcType=VARCHAR}");
        }
        if (record.getConfigKey() != null) {
            sql.VALUES("config_key", "#{configKey,jdbcType=VARCHAR}");
        }
        if (record.getConfigValue() != null) {
            sql.VALUES("config_value", "#{configValue,jdbcType=VARCHAR}");
        }
        if (record.getConfigOption() != null) {
            sql.VALUES("config_option", "#{configOption,jdbcType=VARCHAR}");
        }
        if (record.getCreateBy() != null) {
            sql.VALUES("create_by", "#{createBy,jdbcType=BIGINT}");
        }
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=DATE}");
        }
        if (record.getUpdateBy() != null) {
            sql.VALUES("update_by", "#{updateBy,jdbcType=BIGINT}");
        }
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=DATE}");
        }
        if (record.getRemark() != null) {
            sql.VALUES("remark", "#{remark,jdbcType=VARCHAR}");
        }
        if (record.getConfigStatus() != null) {
            sql.VALUES("config_status", "#{configStatus,jdbcType=INTEGER}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_sys_config
     */
    public String selectByExample(CscpSysConfigExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("config_id");
        } else {
            sql.SELECT("config_id");
        }
        sql.SELECT("config_name");
        sql.SELECT("config_key");
        sql.SELECT("config_value");
        sql.SELECT("config_option");
        sql.SELECT("create_by");
        sql.SELECT("create_time");
        sql.SELECT("update_by");
        sql.SELECT("update_time");
        sql.SELECT("remark");
        sql.SELECT("config_status");
        sql.FROM("cscp_sys_config");
        applyWhere(sql, example, false);

        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }

        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_sys_config
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CscpSysConfig record = (CscpSysConfig) parameter.get("record");
        CscpSysConfigExample example = (CscpSysConfigExample) parameter.get("example");

        SQL sql = new SQL();
        sql.UPDATE("cscp_sys_config");

        if (record.getConfigId() != null) {
            sql.SET("config_id = #{configId,jdbcType=BIGINT}");
        }
        if (record.getConfigName() != null) {
            sql.SET("config_name = #{configName,jdbcType=VARCHAR}");
        }
        if (record.getConfigKey() != null) {
            sql.SET("config_key = #{configKey,jdbcType=VARCHAR}");
        }
        if (record.getConfigValue() != null) {
            sql.SET("config_value = #{configValue,jdbcType=VARCHAR}");
        }
        if (record.getConfigOption() != null) {
            sql.SET("config_option = #{configOption,jdbcType=VARCHAR}");
        }
        if (record.getCreateBy() != null) {
            sql.SET("create_by = #{createBy,jdbcType=BIGINT}");
        }
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=DATE}");
        }
        if (record.getUpdateBy() != null) {
            sql.SET("update_by = #{updateBy,jdbcType=BIGINT}");
        }
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=DATE}");
        }
        if (record.getRemark() != null) {
            sql.SET("remark = #{remark,jdbcType=VARCHAR}");
        }
        if (record.getConfigStatus() != null) {
            sql.SET("config_status = #{configStatus,jdbcType=INTEGER}");
        }
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_sys_config
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_sys_config");
        sql.SET("config_id = #{configId,jdbcType=BIGINT}");
        sql.SET("config_name = #{configName,jdbcType=VARCHAR}");
        sql.SET("config_key = #{configKey,jdbcType=VARCHAR}");
        sql.SET("config_value = #{configValue,jdbcType=VARCHAR}");
        sql.SET("config_option = #{configOption,jdbcType=VARCHAR}");
        sql.SET("create_by = #{createBy,jdbcType=BIGINT}");
        sql.SET("create_time = #{createTime,jdbcType=DATE}");
        sql.SET("update_by = #{updateBy,jdbcType=BIGINT}");
        sql.SET("update_time = #{updateTime,jdbcType=DATE}");
        sql.SET("remark = #{remark,jdbcType=VARCHAR}");
        sql.SET("config_status = #{configStatus,jdbcType=INTEGER}");

        CscpSysConfigExample example = (CscpSysConfigExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_sys_config
     */
    public String updateByPrimaryKeySelective(CscpSysConfig record) {
        SQL sql = new SQL();
        sql.UPDATE("cscp_sys_config");

        if (record.getConfigName() != null) {
            sql.SET("config_name = #{configName,jdbcType=VARCHAR}");
        }
        if (record.getConfigKey() != null) {
            sql.SET("config_key = #{configKey,jdbcType=VARCHAR}");
        }
        if (record.getConfigValue() != null) {
            sql.SET("config_value = #{configValue,jdbcType=VARCHAR}");
        }
        if (record.getConfigOption() != null) {
            sql.SET("config_option = #{configOption,jdbcType=VARCHAR}");
        }
        if (record.getCreateBy() != null) {
            sql.SET("create_by = #{createBy,jdbcType=BIGINT}");
        }
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=DATE}");
        }
        if (record.getUpdateBy() != null) {
            sql.SET("update_by = #{updateBy,jdbcType=BIGINT}");
        }
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=DATE}");
        }
        if (record.getRemark() != null) {
            sql.SET("remark = #{remark,jdbcType=VARCHAR}");
        }
        if (record.getConfigStatus() != null) {
            sql.SET("config_status = #{configStatus,jdbcType=INTEGER}");
        }
        sql.WHERE("config_id = #{configId,jdbcType=BIGINT}");

        return sql.toString();
    }


    /**
     * This method was generated by  Generator.
     * This method corresponds to the database table cscp_sys_config
     */
    protected void applyWhere(SQL sql, CscpSysConfigExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1Th;
        String parmPhrase2;
        String parmPhrase2Th;
        String parmPhrase3;
        String parmPhrase3Th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2Th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3Th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1Th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2Th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3Th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}
