package com.ctsi.ssdc.sensitiveword.domain;

import com.ctsi.ssdc.annocation.AutoId;
import com.ctsi.ssdc.sensitiveword.annotation.SysSensitiveWord;
import com.ctsi.ssdc.util.LongtoStringSerialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

/**
 * @author ctsi-biyi-generator
*/

public class CscpSensitiveWord implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_sensitive_word.id
     *
     */
    @AutoId(primaryKey = "id")
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_sensitive_word.sen_type_id
     *
     */
    @NotNull(message = "分类不可为空")
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long senTypeId;
    
    private String senTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_sensitive_word.sen_content
     *
     */
    @NotBlank(message = "敏感词不可为空")
    private String senContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_sensitive_word.sen_replace
     *
     */
    private String senReplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_sensitive_word.update_time
     *
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_sensitive_word.id
     *
     * @return the value of cscp_sensitive_word.id
     *
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_sensitive_word.id
     *
     * @param id the value for cscp_sensitive_word.id
     *
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_sensitive_word.sen_type_id
     *
     * @return the value of cscp_sensitive_word.sen_type_id
     *
     */
    public Long getSenTypeId() {
        return senTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_sensitive_word.sen_type_id
     *
     * @param senTypeId the value for cscp_sensitive_word.sen_type_id
     *
     */
    public void setSenTypeId(Long senTypeId) {
        this.senTypeId = senTypeId;
    }

    public String getSenTypeName() {
		return senTypeName;
	}

	public void setSenTypeName(String senTypeName) {
		this.senTypeName = senTypeName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_sensitive_word.sen_content
     *
     * @return the value of cscp_sensitive_word.sen_content
     *
     */
    public String getSenContent() {
        return senContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_sensitive_word.sen_content
     *
     * @param senContent the value for cscp_sensitive_word.sen_content
     *
     */
    public void setSenContent(String senContent) {
        this.senContent = senContent == null ? null : senContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_sensitive_word.sen_replace
     *
     * @return the value of cscp_sensitive_word.sen_replace
     *
     */
    public String getSenReplace() {
        return senReplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_sensitive_word.sen_replace
     *
     * @param senReplace the value for cscp_sensitive_word.sen_replace
     *
     */
    public void setSenReplace(String senReplace) {
        this.senReplace = senReplace == null ? null : senReplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_sensitive_word.update_time
     *
     * @return the value of cscp_sensitive_word.update_time
     *
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_sensitive_word.update_time
     *
     * @param updateTime the value for cscp_sensitive_word.update_time
     *
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_sensitive_word
     *
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CscpSensitiveWord other = (CscpSensitiveWord) that;
        return
                (this.getSenTypeId() == null ? other.getSenTypeId() == null : this.getSenTypeId().equals(other.getSenTypeId())) &&
             (this.getSenContent() == null ? other.getSenContent() == null : this.getSenContent().equals(other.getSenContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_sensitive_word
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSenTypeId() == null) ? 0 : getSenTypeId().hashCode());
        result = prime * result + ((getSenContent() == null) ? 0 : getSenContent().hashCode());
        return result;
    }
}