package com.ctsi.ssdc.sensitiveword.domain;

import com.ctsi.ssdc.annocation.AutoId;
import com.ctsi.ssdc.util.LongtoStringSerialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import javax.validation.constraints.NotBlank;
import java.io.Serializable;
import java.util.Date;

/**
 * @author ctsi-biyi-generator
*/
public class CscpSensitiveWordType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_sensitive_word_type.id
     *
     * @mbg.generated Tue May 28 08:39:59 CST 2019
     */
    @AutoId(primaryKey = "id")
    @JsonSerialize(using = LongtoStringSerialize.class)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_sensitive_word_type.sen_type_name
     *
     * @mbg.generated Tue May 28 08:39:59 CST 2019
     */
    @NotBlank(message = "分类名不可为空")
    private String senTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_sensitive_word_type.sen_type_order
     *
     * @mbg.generated Tue May 28 08:39:59 CST 2019
     */
    private Integer senTypeOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cscp_sensitive_word_type.update_time
     *
     * @mbg.generated Tue May 28 08:39:59 CST 2019
     */
    private Date updateTime;


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_sensitive_word_type.sen_type_name
     *
     * @return the value of cscp_sensitive_word_type.sen_type_name
     *
     * @mbg.generated Tue May 28 08:39:59 CST 2019
     */
    public String getSenTypeName() {
        return senTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_sensitive_word_type.sen_type_name
     *
     * @param senTypeName the value for cscp_sensitive_word_type.sen_type_name
     *
     * @mbg.generated Tue May 28 08:39:59 CST 2019
     */
    public void setSenTypeName(String senTypeName) {
        this.senTypeName = senTypeName == null ? null : senTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_sensitive_word_type.sen_type_order
     *
     * @return the value of cscp_sensitive_word_type.sen_type_order
     *
     * @mbg.generated Tue May 28 08:39:59 CST 2019
     */
    public Integer getSenTypeOrder() {
        return senTypeOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_sensitive_word_type.sen_type_order
     *
     * @param senTypeOrder the value for cscp_sensitive_word_type.sen_type_order
     *
     * @mbg.generated Tue May 28 08:39:59 CST 2019
     */
    public void setSenTypeOrder(Integer senTypeOrder) {
        this.senTypeOrder = senTypeOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cscp_sensitive_word_type.update_time
     *
     * @return the value of cscp_sensitive_word_type.update_time
     *
     * @mbg.generated Tue May 28 08:39:59 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cscp_sensitive_word_type.update_time
     *
     * @param updateTime the value for cscp_sensitive_word_type.update_time
     *
     * @mbg.generated Tue May 28 08:39:59 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_sensitive_word_type
     *
     * @mbg.generated Tue May 28 08:39:59 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CscpSensitiveWordType other = (CscpSensitiveWordType) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSenTypeName() == null ? other.getSenTypeName() == null : this.getSenTypeName().equals(other.getSenTypeName()))
            && (this.getSenTypeOrder() == null ? other.getSenTypeOrder() == null : this.getSenTypeOrder().equals(other.getSenTypeOrder()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cscp_sensitive_word_type
     *
     * @mbg.generated Tue May 28 08:39:59 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSenTypeName() == null) ? 0 : getSenTypeName().hashCode());
        result = prime * result + ((getSenTypeOrder() == null) ? 0 : getSenTypeOrder().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}